"use client";

import { useState } from "react";

type OperationRole = { step:string; key:"vision"|"control"|"field"; title:string; description:string; items:string[]; tags:[string,string]; tone:"teal"|"blue"|"warm" };
const roles:OperationRole[]=[
 {step:"01",key:"vision",title:"AI 분석 시스템",description:"CCTV 영상을 분석해 위험 객체와 판단 근거를 제공합니다.",items:["CCTV 실시간 영상 분석","낙하물·야생동물·이륜차 분류","위험 점수와 탐지 근거 생성"],tags:["위험 객체 분석","판단 근거 제공"],tone:"teal"},
 {step:"02",key:"control",title:"관제센터",description:"AI 분석 결과를 검토하고 사건 대응 방향을 결정합니다.",items:["AI 탐지 근거 확인","실제 위험 또는 오탐 판정","출동 담당자 배정","사건 상태 업데이트"],tags:["위험 여부 판단","대응 방향 결정"],tone:"blue"},
 {step:"03",key:"field",title:"현장 대응팀",description:"출동 요청을 받아 현장 조치와 결과를 공유합니다.",items:["출동 요청 확인 및 상태 등록","현장 도착과 조치 과정 기록","조치 결과와 전후 사진 공유"],tags:["현장 상태 등록","조치 결과 공유"],tone:"warm"},
];
const recordFields=[["사건 번호","RB-260714-0821"],["위험 유형","낙하물"],["현재 단계","관제 판단","progress"],["위치","중부고속도로 137.4K"],["동기화 상태","LIVE","live"],["최근 업데이트","08:28:02"]] as const;

function RoleIcon({type}:{type:OperationRole["key"]}){if(type==="vision")return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8V5a1 1 0 0 1 1-1h3M16 4h3a1 1 0 0 1 1 1v3M20 16v3a1 1 0 0 1-1 1h-3M8 20H5a1 1 0 0 1-1-1v-3"/><circle cx="12" cy="12" r="3.2"/></svg>;if(type==="control")return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="13" rx="2"/><path d="m9 10 2 2 4-4M8 21h8M12 17v4"/></svg>;return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><path d="m9 10 2 2 4-4"/></svg>}
function IncidentRecord(){return <article className="operation-record" aria-labelledby="operation-record-title"><header><div><h3 id="operation-record-title">하나의 사건 기록</h3></div><span className="operation-record__status"><i/>실시간 공유</span></header><dl>{recordFields.map(([label,value,state])=><div key={label}><dt>{label}</dt><dd className={state?`is-${state}`:undefined}>{value}</dd></div>)}</dl></article>}

export function OperationalOverview(){const[active,setActive]=useState(0);const role=roles[active];return <section className="operational-overview" aria-labelledby="operational-overview-title"><div className="operational-overview__copy"><p>OPERATIONAL OVERVIEW</p><h2 id="operational-overview-title">탐지부터 현장 대응까지<br/>하나의 흐름으로 연결합니다.</h2><p>AI 분석 시스템과 관제센터, 현장 대응팀이 하나의 사건 기록을 공유하며 각자의 역할을 이어서 수행합니다.</p><div className="operational-overview__chips"><span>AI 분석 시스템</span><span>관제센터</span><span>현장 대응팀</span></div><ul className="operational-overview__principles"><li>AI 분석 결과와 판단 근거 제공</li><li>관제센터의 대응 방향 결정</li><li>현장 조치와 결과 실시간 공유</li></ul></div><div className="operation-system" aria-label="AI 분석 시스템, 관제센터, 현장 대응팀이 연결되는 운영 구조"><div className="operation-system__roles">{roles.map((item,index)=><div className="operation-role-wrap" key={item.key}><button type="button" className={`operation-role operation-role--${item.tone} ${active===index?"is-selected":""}`} aria-pressed={active===index} onClick={()=>setActive(index)}><header><span className="operation-role__number">{item.step}</span><span className="operation-role__icon"><RoleIcon type={item.key}/></span></header><h3>{item.title}</h3><strong>{item.description}</strong><div className="operation-role__tags">{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div></button>{index<roles.length-1&&<div className="operation-transfer" aria-label={index===0?"분석 결과 공유":"출동 요청 전달"}><span>{index===0?"분석 결과 공유":"출동 요청 전달"}</span><i/></div>}</div>)}</div><section className={`operation-selection operation-selection--${role.tone}`} aria-live="polite"><p>현재 선택 주체 · {role.title}</p><h3>{role.description}</h3><ul>{role.items.map(item=><li key={item}>{item}</li>)}</ul></section><IncidentRecord/></div></section>}
