"use client";

/* eslint-disable @next/next/no-img-element -- Local object URLs require a native image element. */

import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {useAuth} from "@/components/auth/AuthContext";
import {createIdempotencyKey} from "@/lib/apiClient";
import {formatRiskGrade} from "@/features/control-dashboard/dashboardDomain";
import {createDispatchAdapter} from "./dispatchAdapterFactory";
import {dispatchStatusCopy,formatDispatchKst} from "./dispatchDomain";
import type {DispatchActionFilePurpose,DispatchActionReport,DispatchDetail,DispatchFilePhase} from "./dispatchTypes";
import {notifyDispatchChanged} from "./dispatchSync";
import "./dispatchAction.css";

const adapter=createDispatchAdapter();
type Step="report"|"photos"|"review";
type LocalPhoto={clientId:string;source:"linked"|"local";file:File|null;fileName:string;previewUrl:string|null;purpose:DispatchActionFilePurpose;phase:DispatchFilePhase;filePublicId:string|null;idempotencyKey:string;linkKey:string;displayOrder:number;error:string};
const phaseCopy:Record<DispatchFilePhase,string>={LOCAL:"업로드 대기",UPLOADING:"파일을 저장하고 있습니다.",UPLOADED:"파일 저장 완료",LINKING:"조치 기록에 연결하고 있습니다.",COMPLETED:"저장 완료",UPLOAD_FAILED:"파일 업로드에 실패했습니다.",LINK_FAILED:"파일은 저장됐지만 조치 기록에 연결하지 못했습니다."};
const errorCopy:Record<string,string>={DISPATCH_NOT_FOUND:"출동 정보를 확인할 수 없습니다.",DISPATCH_VERSION_CONFLICT:"다른 변경이 먼저 반영됐습니다. 최신 상태를 확인해 주세요.",DISPATCH_INVALID_STATE_TRANSITION:"현재 출동 단계에서는 조치 정보를 변경할 수 없습니다.",DISPATCH_ACTION_REPORT_REQUIRED:"조치 내용을 먼저 저장해 주세요.",AUTH_PERMISSION_DENIED:"현재 계정에는 현장 조치 정보를 등록할 권한이 없습니다."};
const svg=(kind:"report"|"photo"|"check"|"upload")=><svg viewBox="0 0 24 24" aria-hidden="true">{kind==="report"?<><path d="M6 3h9l4 4v14H6zM15 3v5h5M9 12h7M9 16h5"/></>:kind==="photo"?<><rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m5 17 4-4 3 3 2-2 5 3"/></>:kind==="upload"?<><path d="M12 16V4M8 8l4-4 4 4M5 20h14"/></>:<><circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/></>}</svg>;

export function DispatchActionWorkspace({publicId}:{publicId:string}){
 const{user}=useAuth(),canEdit=user?.apiPermissions.includes("DISPATCH.UPDATE_OWN")??false;
 const[detail,setDetail]=useState<DispatchDetail|null>(null),[report,setReport]=useState<DispatchActionReport|null>(null),[text,setText]=useState(""),[savedText,setSavedText]=useState(""),[photos,setPhotos]=useState<LocalPhoto[]>([]),[step,setStep]=useState<Step>("report"),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[confirming,setConfirming]=useState(false),[preview,setPreview]=useState<LocalPhoto|null>(null);
 const previewTrigger=useRef<HTMLButtonElement|null>(null);
 const photosRef=useRef<LocalPhoto[]>([]);
 const busyRef=useRef(false),dirtyRef=useRef(false),loadSequence=useRef(0),currentPublicIdRef=useRef(publicId);
 const operationIsCurrent=(operation:{publicId:string;sequence:number})=>operation.publicId===currentPublicIdRef.current&&operation.sequence===loadSequence.current;
 const load=useCallback(async()=>{const sequence=++loadSequence.current;busyRef.current=false;setBusy(false);photosRef.current.forEach(photo=>photo.source==="local"&&photo.previewUrl&&URL.revokeObjectURL?.(photo.previewUrl));photosRef.current=[];setLoading(true);setDetail(null);setReport(null);setText("");setSavedText("");setPhotos([]);setStep("report");setMessage("");setError("");setConfirming(false);setPreview(null);try{const[next,nextReport]=await Promise.all([adapter.detail(publicId),adapter.getActionReport(publicId)]);if(sequence!==loadSequence.current||publicId!==currentPublicIdRef.current)return;setDetail(next);setReport(nextReport);if(nextReport){setText(nextReport.detail);setSavedText(nextReport.detail);setPhotos(nextReport.files.map(file=>({clientId:`linked-${file.filePublicId}`,source:"linked",file:null,fileName:file.fileName,previewUrl:file.previewUrl??null,purpose:file.purpose,phase:"COMPLETED",filePublicId:file.filePublicId,idempotencyKey:"",linkKey:"",displayOrder:file.displayOrder,error:""})))}}catch{if(sequence===loadSequence.current&&publicId===currentPublicIdRef.current)setError("출동 정보를 불러오지 못했습니다.")}finally{if(sequence===loadSequence.current&&publicId===currentPublicIdRef.current)setLoading(false)}},[publicId]);
 useEffect(()=>{currentPublicIdRef.current=publicId;void load();const sequence=loadSequence.current;return()=>{loadSequence.current=sequence+1}},[load,publicId]);
 useEffect(()=>{photosRef.current=photos},[photos]);
 const dirty=text.trim()!==savedText||photos.some(photo=>photo.phase!=="COMPLETED")||(adapter.mode==="api"&&Boolean(report)&&detail?.status==="ACTION_IN_PROGRESS");
 useEffect(()=>{dirtyRef.current=dirty},[dirty]);
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault()};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 useEffect(()=>{const message="저장하지 않은 현장 조치 변경사항이 있습니다. 이동할까요?";const navigation=(window as typeof window&{navigation?:EventTarget}).navigation;if(navigation){const navigate=(event:Event)=>{const value=event as Event&{canIntercept?:boolean;destination?:{url?:string}};if(!dirtyRef.current||!value.canIntercept||!value.destination?.url||value.destination.url===window.location.href)return;if(!window.confirm(message))event.preventDefault()};navigation.addEventListener("navigate",navigate);return()=>navigation.removeEventListener("navigate",navigate)}const click=(event:MouseEvent)=>{if(!dirtyRef.current||event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const anchor=(event.target as Element|null)?.closest("a[href]") as HTMLAnchorElement|null;if(!anchor||anchor.target||anchor.hasAttribute("download"))return;const target=new URL(anchor.href,window.location.href);if(target.origin!==window.location.origin||target.href===window.location.href)return;if(!window.confirm(message)){event.preventDefault();event.stopPropagation()}};document.addEventListener("click",click,true);return()=>document.removeEventListener("click",click,true)},[]);
 useEffect(()=>()=>{const revoked=new Set<string>();photosRef.current.forEach(photo=>{if(photo.source!=="local"||!photo.previewUrl?.startsWith("blob:")||revoked.has(photo.previewUrl))return;revoked.add(photo.previewUrl);URL.revokeObjectURL?.(photo.previewUrl)})},[]);
 useEffect(()=>{if(!preview)return;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setPreview(null);requestAnimationFrame(()=>previewTrigger.current?.focus())}};document.addEventListener("keydown",close);return()=>{document.body.style.overflow="";document.removeEventListener("keydown",close)}},[preview]);
 const editable=Boolean(detail&&detail.status==="ACTION_IN_PROGRESS"&&canEdit&&Number.isInteger(detail.versionNo));
 const pending=photos.some(photo=>!["COMPLETED"].includes(photo.phase));
 const canComplete=editable&&Boolean(report)&&report?.detail===text.trim()&&!pending&&!busy;
 const save=async()=>{if(!detail||!editable||busyRef.current)return;const operation={publicId,sequence:loadSequence.current},value=text.trim();if(!value){setError("조치 상세 내용을 입력해 주세요.");return}busyRef.current=true;setBusy(true);setError("");try{const result=await adapter.saveActionReport(publicId,value,detail.versionNo,createIdempotencyKey(),detail);if(!operationIsCurrent(operation))return;if(result.ok){setReport(result.report);setDetail(result.detail);setText(value);setSavedText(value);setMessage(adapter.mode==="api"?"입력 내용을 완료 요청에 사용할 준비가 됐습니다.":"조치 내용을 저장했습니다.");setStep("photos")}else{setDetail(result.latest);setError(errorCopy[result.code]??"조치 내용을 확인하지 못했습니다.")}}catch{if(operationIsCurrent(operation))setError("조치 내용을 확인하지 못했습니다.")}finally{if(operationIsCurrent(operation)){busyRef.current=false;setBusy(false)}}};
 const patchPhoto=(clientId:string,patch:Partial<LocalPhoto>,operation?:{publicId:string;sequence:number})=>{if(operation&&!operationIsCurrent(operation))return;setPhotos(current=>current.map(photo=>photo.clientId===clientId?{...photo,...patch}:photo))};
 const linkPhoto=async(photo:LocalPhoto,filePublicId:string,operation={publicId,sequence:loadSequence.current})=>{patchPhoto(photo.clientId,{phase:"LINKING",filePublicId},operation);try{const linked=await adapter.linkActionFile(operation.publicId,filePublicId,photo.purpose,photo.displayOrder,photo.linkKey);if(!operationIsCurrent(operation))return;const previewUrl=linked.previewUrl??photo.previewUrl;if(photo.source==="local"&&photo.previewUrl?.startsWith("blob:")&&previewUrl!==photo.previewUrl)URL.revokeObjectURL?.(photo.previewUrl);patchPhoto(photo.clientId,{phase:"COMPLETED",filePublicId,error:"",fileName:linked.fileName,previewUrl},operation);setReport(current=>current?{...current,files:[...current.files.filter(file=>file.filePublicId!==filePublicId),linked]}:current)}catch{patchPhoto(photo.clientId,{phase:"LINK_FAILED",filePublicId,error:phaseCopy.LINK_FAILED},operation)}};
 const upload=async(photo:LocalPhoto,operation={publicId,sequence:loadSequence.current})=>{if(!photo.file)return;patchPhoto(photo.clientId,{phase:"UPLOADING",error:""},operation);try{const result=await adapter.uploadActionFile(photo.file,photo.purpose,photo.clientId,photo.idempotencyKey);if(!operationIsCurrent(operation))return;patchPhoto(photo.clientId,{phase:"UPLOADED",filePublicId:result.filePublicId},operation);await linkPhoto(photo,result.filePublicId,operation)}catch{patchPhoto(photo.clientId,{phase:"UPLOAD_FAILED",error:phaseCopy.UPLOAD_FAILED},operation)}};
 const selectFiles=(purpose:DispatchActionFilePurpose,files:FileList|null)=>{if(!files||!report)return;const additions=[...files].map((file,index)=>{const clientId=crypto.randomUUID(),previewUrl=URL.createObjectURL?.(file)??null;return{clientId,source:"local" as const,file,fileName:file.name,previewUrl,purpose,phase:"LOCAL" as const,filePublicId:null,idempotencyKey:createIdempotencyKey(),linkKey:createIdempotencyKey(),displayOrder:photos.filter(photo=>photo.purpose===purpose).length+index,error:""}});setPhotos(current=>[...current,...additions]);additions.forEach(photo=>void upload(photo))};
 const remove=(photo:LocalPhoto)=>{if(!["LOCAL","UPLOAD_FAILED"].includes(photo.phase))return;if(photo.previewUrl)URL.revokeObjectURL?.(photo.previewUrl);setPhotos(current=>current.filter(item=>item.clientId!==photo.clientId))};
 const complete=async()=>{if(!detail||!canComplete||busyRef.current)return;const operation={publicId,sequence:loadSequence.current};busyRef.current=true;setBusy(true);setError("");try{const result=await adapter.completeAction(publicId,detail.versionNo,createIdempotencyKey(),detail);if(!operationIsCurrent(operation))return;if(result.ok){setDetail(result.detail);setReport(result.report);setSavedText(result.report.detail);setConfirming(false);setMessage("현장 조치가 완료되었습니다.");notifyDispatchChanged()}else{setDetail(result.latest);setError(errorCopy[result.code]??"현장 조치를 완료하지 못했습니다.")}}catch{if(operationIsCurrent(operation))setError("현장 조치를 완료하지 못했습니다.")}finally{if(operationIsCurrent(operation)){busyRef.current=false;setBusy(false)}}};
 if(loading)return <Page><div className="dispatch-action-state" role="status">현장 조치 정보를 불러오는 중입니다.</div></Page>;
 if(error&&!detail)return <Page><div className="dispatch-action-state" role="alert"><strong>{error}</strong><button onClick={()=>void load()}>다시 확인</button></div></Page>;
 if(!detail)return <Page><div className="dispatch-action-state"><strong>출동 정보를 확인할 수 없습니다.</strong><Link href="/dispatch">내 출동 목록으로</Link></div></Page>;
 if(detail.status==="ACTION_COMPLETED")return <Page><Completed detail={detail} report={report}/></Page>;
 if(detail.status!=="ACTION_IN_PROGRESS")return <Page><Unavailable detail={detail}/></Page>;
 return <Page><main className="dispatch-action-shell"><Summary detail={detail}/><div className="dispatch-action-layout"><aside><ol aria-label="현장 조치 작성 단계">{[["report","1","조치 내용"],["photos","2","현장 사진"],["review","3","최종 확인"]].map(([key,no,label])=><li key={key} data-current={step===key}><i>{no}</i><span>{label}</span></li>)}</ol></aside><section className="dispatch-action-editor">
   {!canEdit&&<p className="dispatch-action-warning" role="alert">현재 계정에는 현장 조치 정보를 등록할 권한이 없습니다.</p>}{message&&<p className="dispatch-action-notice" role="status">{message}</p>}{error&&<p className="dispatch-action-warning" role="alert">{error}</p>}
   {step==="report"&&<section aria-labelledby="report-title"><header><span>{svg("report")}</span><div><h2 id="report-title">조치 상세 내용</h2><p>현장에서 수행한 조치와 현재 도로 상태를 작성해 주세요.</p></div></header><label htmlFor="action-detail">조치 상세 내용</label><textarea id="action-detail" value={text} onChange={event=>setText(event.target.value)} disabled={!editable||busy} aria-describedby="action-detail-help action-detail-count"/><small id="action-detail-help">{adapter.mode==="api"?"입력한 내용은 완료 요청 전까지 서버에 저장되지 않습니다.":"앞뒤 공백은 저장할 때 제거됩니다."}</small><small id="action-detail-count">{text.length}자</small><footer><button className="primary" type="button" onClick={()=>void save()} disabled={!editable||busy||!text.trim()} aria-busy={busy}>{busy?(adapter.mode==="api"?"확인 중":"저장 중"):(adapter.mode==="api"?"내용 확인":"조치 내용 저장")}</button></footer></section>}
   {step==="photos"&&<section aria-labelledby="photos-title"><header><span>{svg("photo")}</span><div><h2 id="photos-title">현장 사진</h2><p>조치 전·후 현장 상태를 구분해 등록합니다.</p></div></header>{adapter.mode==="api"&&<p className="dispatch-action-warning" role="status">현장 사진 등록 API는 현재 제공되지 않습니다. 조치 내용만 완료 요청에 포함됩니다.</p>}<div className="dispatch-photo-columns"><PhotoArea title="조치 전" description="위험 요소와 조치 시작 전 현장 상태를 등록합니다." purpose="ACTION_BEFORE" photos={photos} disabled={!editable||!report||adapter.mode==="api"} onSelect={selectFiles} onRemove={remove} onRetry={upload} onRelink={photo=>photo.filePublicId&&void linkPhoto(photo,photo.filePublicId)} onPreview={(photo,trigger)=>{previewTrigger.current=trigger;setPreview(photo)}}/><PhotoArea title="조치 후" description="조치가 끝난 뒤 도로와 주변 상태를 등록합니다." purpose="ACTION_AFTER" photos={photos} disabled={!editable||!report||adapter.mode==="api"} onSelect={selectFiles} onRemove={remove} onRetry={upload} onRelink={photo=>photo.filePublicId&&void linkPhoto(photo,photo.filePublicId)} onPreview={(photo,trigger)=>{previewTrigger.current=trigger;setPreview(photo)}}/></div><footer><button type="button" onClick={()=>setStep("report")}>조치 내용 수정</button><button className="primary" type="button" onClick={()=>setStep("review")} disabled={!report||pending}>최종 확인</button></footer></section>}
   {step==="review"&&<section aria-labelledby="review-title"><header><span>{svg("check")}</span><div><h2 id="review-title">최종 확인</h2><p>관제센터에 전달할 내용을 확인해 주세요.</p></div></header><dl className="dispatch-action-review"><div><dt>조치 유형</dt><dd>계약 미확정</dd></div><div><dt>조치 상세 내용</dt><dd>{report?.detail}</dd></div><div><dt>조치 전 사진</dt><dd>{photos.filter(photo=>photo.purpose==="ACTION_BEFORE").length}장</dd></div><div><dt>조치 후 사진</dt><dd>{photos.filter(photo=>photo.purpose==="ACTION_AFTER").length}장</dd></div></dl><p className="dispatch-action-guidance">현장 조치 완료 후 관제센터의 최종 확인을 기다립니다.<br/>이 단계에서는 사건이 자동으로 종료되지 않습니다.</p><footer><button onClick={()=>setStep("report")}>조치 내용 수정</button><button onClick={()=>setStep("photos")}>사진 수정</button><button className="primary" onClick={()=>setConfirming(true)} disabled={!canComplete}>현장 조치 완료</button></footer></section>}
  </section></div></main>{preview&&<Preview photo={preview} onClose={()=>{setPreview(null);requestAnimationFrame(()=>previewTrigger.current?.focus())}}/>}{confirming&&<Confirm busy={busy} onCancel={()=>setConfirming(false)} onConfirm={()=>void complete()}/>}</Page>;
}
function Page({children}:{children:React.ReactNode}){return <div className="dispatch-action-page">{children}</div>}
function Summary({detail}:{detail:DispatchDetail}){return <header className="dispatch-action-summary"><div><span>현장 조치 등록</span><h1>{detail.incident.incidentNo}</h1><p>{detail.incident.objectCategory} · {formatRiskGrade(detail.incident.riskGrade)} · {detail.incident.cctvName}</p><small>{detail.incident.roadName} · {detail.incident.roadSectionName}</small></div><div><b>{dispatchStatusCopy[detail.status]}</b><small>현장 도착 {detail.arrivedAt?formatDispatchKst(detail.arrivedAt):"정보 없음"} KST<br/>조치 시작 {detail.actionStartedAt?formatDispatchKst(detail.actionStartedAt):"정보 없음"} KST</small></div></header>}
function Unavailable({detail}:{detail:DispatchDetail}){return <main className="dispatch-action-shell"><Summary detail={detail}/><div className="dispatch-action-state"><strong>현재 단계에서는 현장 조치 정보를 등록할 수 없습니다.</strong><p>{detail.status==="ARRIVED"?"출동 상세에서 조치 시작을 먼저 등록해 주세요.":`현재 상태 · ${dispatchStatusCopy[detail.status]}`}</p><Link href={`/dispatch/${encodeURIComponent(detail.publicId)}`}>출동 상세로</Link></div></main>}
function Completed({detail,report}:{detail:DispatchDetail;report:DispatchActionReport|null}){return <main className="dispatch-action-shell"><Summary detail={detail}/><section className="dispatch-action-completed"><span>{svg("check")}</span><h2>현장 조치가 완료되었습니다.</h2><p>관제센터에서 조치 결과를 확인하고 있습니다.</p>{report?<dl><div><dt>조치 상세 내용</dt><dd>{report.detail}</dd></div><div><dt>조치 시작 시각</dt><dd>{detail.actionStartedAt?formatDispatchKst(detail.actionStartedAt):"정보 없음"} KST</dd></div><div><dt>조치 완료 시각</dt><dd>{detail.actionCompletedAt?formatDispatchKst(detail.actionCompletedAt):"정보 없음"} KST</dd></div><div><dt>조치 전 사진</dt><dd>{report.files.filter(file=>file.purpose==="ACTION_BEFORE").length}장</dd></div><div><dt>조치 후 사진</dt><dd>{report.files.filter(file=>file.purpose==="ACTION_AFTER").length}장</dd></div></dl>:<p>저장된 조치 결과를 다시 불러오는 기능은 현재 API에서 제공되지 않습니다.</p>}<Link href="/dispatch">내 출동 목록으로</Link></section></main>}
function PhotoArea({title,description,purpose,photos,disabled,onSelect,onRemove,onRetry,onRelink,onPreview}:{title:string;description:string;purpose:DispatchActionFilePurpose;photos:LocalPhoto[];disabled:boolean;onSelect:(purpose:DispatchActionFilePurpose,files:FileList|null)=>void;onRemove:(photo:LocalPhoto)=>void;onRetry:(photo:LocalPhoto)=>void;onRelink:(photo:LocalPhoto)=>void;onPreview:(photo:LocalPhoto,trigger:HTMLButtonElement)=>void}){const list=photos.filter(photo=>photo.purpose===purpose);return <section className="dispatch-photo-area"><header><h3>{title}</h3><p>{description}</p></header><div className="dispatch-file-actions"><label>{svg("upload")}카메라로 촬영<input type="file" accept="image/*" capture="environment" disabled={disabled} onChange={event=>onSelect(purpose,event.target.files)}/></label><label>갤러리에서 선택<input type="file" accept="image/*" multiple disabled={disabled} onChange={event=>onSelect(purpose,event.target.files)}/></label></div>{list.length?<ul>{list.map((photo,index)=><li key={photo.clientId} data-phase={photo.phase}>{photo.previewUrl?<button className="photo-preview" type="button" onClick={event=>onPreview(photo,event.currentTarget)}><img src={photo.previewUrl} alt={`${title} 사진 ${index+1}`}/></button>:<span className="photo-preview" aria-label="미리보기 불가">미리보기 없음</span>}<div><strong>{photo.fileName}</strong>{photo.file&&<small>{Math.ceil(photo.file.size/1024)} KB</small>}<span role={photo.phase.includes("FAILED")?"alert":"status"}>{phaseCopy[photo.phase]}</span></div>{photo.source==="local"&&["LOCAL","UPLOAD_FAILED"].includes(photo.phase)&&<button onClick={()=>onRemove(photo)}>목록에서 제거</button>}{photo.phase==="UPLOAD_FAILED"&&<button onClick={()=>void onRetry(photo)}>다시 업로드</button>}{photo.phase==="LINK_FAILED"&&<button onClick={()=>void onRelink(photo)}>기록 연결 다시 시도</button>}</li>)}</ul>:<p className="dispatch-photo-empty">선택한 사진이 없습니다.</p>}</section>}
function Preview({photo,onClose}:{photo:LocalPhoto;onClose:()=>void}){return <div className="dispatch-action-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="dispatch-preview-dialog" role="dialog" aria-modal="true" aria-label="현장 사진 미리보기"><img src={photo.previewUrl??""} alt={photo.purpose==="ACTION_BEFORE"?"조치 전 사진 미리보기":"조치 후 사진 미리보기"}/><button autoFocus onClick={onClose}>닫기</button></section></div>}
function Confirm({busy,onCancel,onConfirm}:{busy:boolean;onCancel:()=>void;onConfirm:()=>void}){return <div className="dispatch-action-backdrop"><section className="dispatch-confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="complete-title"><h2 id="complete-title">현장 조치를 완료할까요?</h2><p>저장된 조치 내용과 사진이 관제센터에 전달됩니다.<br/>완료 후에는 일반 편집이 제한될 수 있습니다.<br/>사건은 관제센터의 최종 확인 후 종료됩니다.</p><div><button autoFocus disabled={busy} onClick={onCancel}>계속 수정</button><button className="primary" disabled={busy} aria-busy={busy} onClick={onConfirm}>{busy?"처리 중":"현장 조치 완료"}</button></div></section></div>}
