// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import type {DispatchActionReport,DispatchAdapter,DispatchDetail} from "./dispatchTypes";
const mocks=vi.hoisted(()=>({adapter:{} as DispatchAdapter,permissions:["DISPATCH.UPDATE_OWN"]}));
vi.mock("@/components/auth/AuthContext",()=>({useAuth:()=>({user:{apiPermissions:mocks.permissions}})}));
vi.mock("@/components/landing/LandingHeader",()=>({LandingHeader:()=> <header>header</header>}));
vi.mock("./dispatchAdapterFactory",()=>({createDispatchAdapter:()=>new Proxy({},{get:(_target,property)=>mocks.adapter[property as keyof DispatchAdapter]})}));
import {DispatchActionWorkspace} from "./DispatchActionWorkspace";
const detail:DispatchDetail={publicId:"dispatch-1",attemptNo:1,status:"ACTION_IN_PROGRESS",requestMessage:"현장 조치",requestedAt:"2026-07-21T00:00:00Z",acceptedAt:"2026-07-21T00:10:00Z",versionNo:4,incident:{publicId:"incident-1",incidentNo:"INC-1",status:"ACTION_IN_PROGRESS",objectCategory:"낙하물",riskGrade:"HIGH",cctvName:"CAM 01",roadName:"중부고속도로",roadSectionName:"일죽IC~호법JC",latitude:37.5,longitude:127.1},assignedBy:{publicId:"manager",name:"관제자"},rejectionReason:null,departedAt:"2026-07-21T00:20:00Z",enRouteAt:"2026-07-21T00:25:00Z",arrivedAt:"2026-07-21T00:30:00Z",actionStartedAt:"2026-07-21T00:35:00Z",actionCompletedAt:null,cancelledAt:null,previousDispatchPublicId:null};
const report:DispatchActionReport={detail:"낙하물을 제거했습니다.",files:[],savedAt:"2026-07-21T00:40:00Z",completedAt:null};
const adapter=():DispatchAdapter=>({mode:"mock",list:vi.fn(),detail:vi.fn().mockResolvedValue(detail),accept:vi.fn(),reject:vi.fn(),depart:vi.fn(),markEnRoute:vi.fn(),arrive:vi.fn(),startAction:vi.fn(),getActionReport:vi.fn().mockResolvedValue(null),saveActionReport:vi.fn().mockResolvedValue({ok:true,report,detail}),uploadActionFile:vi.fn().mockResolvedValue({filePublicId:"file-1"}),linkActionFile:vi.fn().mockResolvedValue({filePublicId:"file-1",purpose:"ACTION_BEFORE",displayOrder:0,fileName:"photo.jpg"}),completeAction:vi.fn().mockResolvedValue({ok:true,report:{...report,completedAt:"2026-07-21T01:00:00Z"},detail:{...detail,status:"ACTION_COMPLETED",actionCompletedAt:"2026-07-21T01:00:00Z"}})});
afterEach(cleanup);beforeEach(()=>{mocks.permissions=["DISPATCH.UPDATE_OWN"];mocks.adapter=adapter();Object.defineProperty(URL,"createObjectURL",{configurable:true,value:vi.fn(()=>"blob:preview")});Object.defineProperty(URL,"revokeObjectURL",{configurable:true,value:vi.fn()})});
describe("DispatchActionWorkspace",()=>{
 it("saves the report, reviews it, and completes after explicit confirmation",async()=>{const view=render(<DispatchActionWorkspace publicId="dispatch-1"/>);await screen.findByRole("heading",{name:"조치 상세 내용"});const textarea=view.container.querySelector("#action-detail")!;fireEvent.change(textarea,{target:{value:"  낙하물을 제거했습니다.  "}});fireEvent.click(screen.getByRole("button",{name:"조치 내용 저장"}));await screen.findByRole("heading",{name:"현장 사진"});expect(mocks.adapter.saveActionReport).toHaveBeenCalledWith("dispatch-1","낙하물을 제거했습니다.",4,expect.any(String),detail);fireEvent.click(screen.getByRole("button",{name:"최종 확인"}));fireEvent.click(screen.getByRole("button",{name:"현장 조치 완료"}));const dialog=screen.getByRole("dialog",{name:"현장 조치를 완료할까요?"});fireEvent.click(within(dialog).getByRole("button",{name:"현장 조치 완료"}));expect(await screen.findByText("관제센터에서 조치 결과를 확인하고 있습니다.")).toBeTruthy()});
 it("uploads once and links with the returned file public id",async()=>{mocks.adapter=adapter();vi.mocked(mocks.adapter.getActionReport).mockResolvedValue(report);render(<DispatchActionWorkspace publicId="dispatch-1"/>);await screen.findByDisplayValue(report.detail);fireEvent.click(screen.getByRole("button",{name:"조치 내용 저장"}));await screen.findByRole("heading",{name:"현장 사진"});const input=screen.getAllByLabelText("갤러리에서 선택")[0];const file=new File(["image"],"before.jpg",{type:"image/jpeg"});fireEvent.change(input,{target:{files:[file]}});await waitFor(()=>expect(mocks.adapter.uploadActionFile).toHaveBeenCalledTimes(1));await waitFor(()=>expect(mocks.adapter.linkActionFile).toHaveBeenCalledWith("dispatch-1","file-1","ACTION_BEFORE",0,expect.any(String)))});
 it("blocks editing without permission and handles a mismatched state",async()=>{mocks.permissions=[];const view=render(<DispatchActionWorkspace publicId="dispatch-1"/>);expect(await screen.findByText("현재 계정에는 현장 조치 정보를 등록할 권한이 없습니다.")).toBeTruthy();expect((view.container.querySelector("#action-detail") as HTMLTextAreaElement).disabled).toBe(true);cleanup();mocks.adapter=adapter();vi.mocked(mocks.adapter.detail).mockResolvedValue({...detail,status:"ARRIVED"});render(<DispatchActionWorkspace publicId="dispatch-1"/>);expect(await screen.findByText("출동 상세에서 조치 시작을 먼저 등록해 주세요.")).toBeTruthy()});
});
