// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen} from "@testing-library/react";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import type {DispatchAdapter,DispatchDetail} from "./dispatchTypes";
const mocks=vi.hoisted(()=>({adapter:{} as DispatchAdapter,permissions:["DISPATCH.UPDATE_OWN"]}));
vi.mock("@/components/auth/AuthContext",()=>({useAuth:()=>({user:{apiPermissions:mocks.permissions}})}));
vi.mock("@/components/landing/LandingHeader",()=>({LandingHeader:()=> <header>header</header>}));
vi.mock("./dispatchAdapterFactory",()=>({createDispatchAdapter:()=>new Proxy({},{get:(_target,property)=>mocks.adapter[property as keyof DispatchAdapter]})}));
import {DispatchHub} from "./DispatchHub";
const detail=(status:DispatchDetail["status"],id=status):DispatchDetail=>({publicId:`dispatch-${id}`,attemptNo:1,status,requestMessage:"현장 확인 후 안전 조치를 진행해 주세요.",requestedAt:"2026-07-21T00:00:00Z",acceptedAt:status==="REQUESTED"?null:"2026-07-21T00:10:00Z",versionNo:1,incident:{publicId:`incident-${id}`,incidentNo:`INC-${id}`,status:"DISPATCHED",objectCategory:"낙하물",riskGrade:"HIGH",cctvName:"CAM 03",roadName:"영동고속도로",roadSectionName:"여주JC → 이천IC",latitude:37.5,longitude:127.1},assignedBy:{publicId:"manager",name:"관제 담당자"},rejectionReason:null,departedAt:status==="EN_ROUTE"?"2026-07-21T00:20:00Z":null,enRouteAt:status==="EN_ROUTE"?"2026-07-21T00:25:00Z":null,arrivedAt:null,actionStartedAt:null,actionCompletedAt:status==="ACTION_COMPLETED"?"2026-07-21T01:00:00Z":null,cancelledAt:status==="CANCELLED"?"2026-07-21T01:00:00Z":null,previousDispatchPublicId:null});
const adapterFor=(items:DispatchDetail[]):DispatchAdapter=>({mode:"mock",list:vi.fn().mockResolvedValue({items,pagination:{page:1,size:50,totalElements:items.length,totalPages:1}}),detail:vi.fn(async id=>items.find(item=>item.publicId===id)??null),accept:vi.fn(),reject:vi.fn(),depart:vi.fn(),markEnRoute:vi.fn(),arrive:vi.fn(),startAction:vi.fn(),getActionReport:vi.fn(),saveActionReport:vi.fn(),uploadActionFile:vi.fn(),linkActionFile:vi.fn(),completeAction:vi.fn()});
afterEach(cleanup);beforeEach(()=>{mocks.permissions=["DISPATCH.UPDATE_OWN"];mocks.adapter=adapterFor([detail("EN_ROUTE"),detail("REQUESTED"),detail("ACTION_COMPLETED")])});
describe("DispatchHub",()=>{
  it.each([["ACCEPTED","출발 등록"],["DEPARTED","이동 중 등록"],["EN_ROUTE","현장 도착 등록"],["ARRIVED","조치 시작"],["ACTION_IN_PROGRESS","현장 조치 등록"]] as const)("derives the next work for %s",async(status,label)=>{mocks.adapter=adapterFor([detail(status)]);render(<DispatchHub/>);expect((await screen.findAllByText(label)).length).toBeGreaterThan(0)});
  it("prioritizes the active dispatch and links by public id",async()=>{const{container}=render(<DispatchHub/>);expect(await screen.findByRole("heading",{name:"현재 현장 대응"})).toBeTruthy();expect(screen.getByRole("heading",{name:"여주JC — 이천IC"})).toBeTruthy();expect(screen.getAllByText("현장 도착 등록").length).toBeGreaterThan(0);expect(screen.getByRole("link",{name:"업무 계속하기"}).getAttribute("href")).toBe("/dispatch/dispatch-EN_ROUTE");expect(container.textContent).not.toMatch(/[→>›‹]/)});
  it("shows a request action only with update permission",async()=>{render(<DispatchHub/>);expect((await screen.findByRole("link",{name:"요청 검토"})).getAttribute("href")).toBe("/dispatch/dispatch-REQUESTED");cleanup();mocks.permissions=[];render(<DispatchHub/>);await screen.findByText("INC-REQUESTED");expect(screen.queryByRole("link",{name:"요청 검토"})).toBeNull()});
  it("uses a full-width request area when no active dispatch exists",async()=>{mocks.adapter=adapterFor([detail("REQUESTED")]);const{container}=render(<DispatchHub/>);expect(await screen.findByText("현재 진행 중인 현장 대응이 없습니다.")).toBeTruthy();expect(container.querySelector(".dispatch-hub-grid.no-active")).toBeTruthy()});
  it("keeps terminal work only in the URL-selected history view",async()=>{render(<DispatchHub initialView="history"/>);expect(await screen.findByRole("heading",{name:"완료 이력"})).toBeTruthy();expect(screen.getByText("조치 완료")).toBeTruthy();expect(screen.queryByRole("heading",{name:"현재 현장 대응"})).toBeNull()});
  it("shows completed, rejected, and cancelled work in history",async()=>{mocks.adapter=adapterFor([detail("ACTION_COMPLETED"),detail("REJECTED"),detail("CANCELLED")]);render(<DispatchHub initialView="history"/>);expect(await screen.findByText("조치 완료")).toBeTruthy();expect(screen.getByText("출동 거절")).toBeTruthy();expect(screen.getByText("출동 취소")).toBeTruthy()});
  it("normalizes an unsupported view to the dispatch home",async()=>{render(<DispatchHub initialView="unknown"/>);expect(await screen.findByRole("heading",{name:"내 출동"})).toBeTruthy()});
  it("renders semantic progress states without step numbers",async()=>{const{container}=render(<DispatchHub/>);await screen.findByLabelText("이동 중, 현재 단계");expect(screen.getByLabelText("출발, 완료")).toBeTruthy();expect(screen.getByLabelText("도착, 예정")).toBeTruthy();expect([...container.querySelectorAll(".dispatch-hub-progress i")].map(node=>node.textContent).join("")).not.toMatch(/[1-7]/)});
  it("renders the no-data and API error states",async()=>{mocks.adapter=adapterFor([]);render(<DispatchHub/>);expect(await screen.findByText("아직 배정된 출동 기록이 없습니다.")).toBeTruthy();cleanup();mocks.adapter={...adapterFor([]),list:vi.fn().mockRejectedValue(new Error("offline"))};render(<DispatchHub/>);expect(await screen.findByText("출동 정보를 불러오지 못했습니다.")).toBeTruthy();expect(screen.getByRole("button",{name:"다시 확인"})).toBeTruthy()});
  it("keeps existing work visible while a refresh fails",async()=>{const current=adapterFor([detail("EN_ROUTE")]);vi.mocked(current.list).mockResolvedValueOnce({items:[detail("EN_ROUTE")],pagination:{page:1,size:50,totalElements:1,totalPages:1}}).mockRejectedValueOnce(new Error("offline"));mocks.adapter=current;render(<DispatchHub/>);await screen.findByRole("heading",{name:"현재 현장 대응"});fireEvent.click(screen.getByRole("button",{name:"새로고침"}));expect(screen.getByRole("heading",{name:"현재 현장 대응"})).toBeTruthy();expect((await screen.findByRole("alert")).textContent).toContain("기존 출동 정보를 계속 표시합니다.")});
});
