// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen} from "@testing-library/react";
import {afterEach,describe,expect,it,vi} from "vitest";
import type {IncidentDetailRecord} from "./incidentDetailTypes";
import {FieldActionReview,fieldActionClosureBlockReason} from "./FieldActionReview";

const record=(status:"ACTION_COMPLETED"|"CLOSED"="ACTION_COMPLETED"):IncidentDetailRecord=>({incident:{public_id:"incident-1",incident_no:"INC-1",cctv_public_id:"cctv-1",status,object_category:"DEBRIS",class_code:"TIRE",class_name:"타이어",current_risk_score:80,current_risk_grade:"HIGH",representative_confidence:.9,duration_ms:1000,detection_count:2,representative_image_url:null,representative_image_kind:null,detection_bbox:null,assigned_controller:null,claimed_at:null,version_no:1,created_at:"2026-07-19T00:00:00Z",updated_at:"2026-07-19T01:00:00Z"},cctv:{public_id:"cctv-1",cctv_code:"CAM",cctv_name:"CAM",source_type:"DEMO",stream_type:"DEMO",direction_code:"ASC",operational_status:"NORMAL",has_stream:true,fallback_used:false,video_state:"PLAYING",road:{road_name:"도로"},road_section:{section_name:"구간"}},evidences:[],dispatch:{public_id:"dispatch-1",incident_public_id:"incident-1",status:"ACTION_COMPLETED",responder_label:"이출동",requested_at:"2026-07-19T00:00:00Z",updated_at:"2026-07-19T01:00:00Z"},histories:status==="CLOSED"?[{public_id:"history-close",event_type:"INCIDENT_UPDATED",label:"사건 최종 종료",actor_name:"관제자",occurred_at:"2026-07-19T01:10:00Z",detail:null}]:[],field_action:{action_type:"현장 조치",detail:"낙하물을 제거했습니다.",before_image_url:"/before.png",after_image_url:"/after.png",completed_at:"2026-07-19T01:00:00Z"},decision:null,controller_note:null,memos:[],request_message:null});
afterEach(cleanup);
describe("FieldActionReview",()=>{
  it("shows action details and enables explicit closure only when complete",()=>{const onClose=vi.fn();render(<FieldActionReview record={record()} onClose={onClose}/>);expect(screen.getByText("이출동")).toBeTruthy();expect(screen.getByText("낙하물을 제거했습니다.")).toBeTruthy();expect(screen.getByRole("button",{name:"사건 최종 종료"}).hasAttribute("disabled")).toBe(false);fireEvent.click(screen.getByRole("button",{name:"사건 최종 종료"}));expect(onClose).toHaveBeenCalled()});
  it("blocks closure with a clear reason when photo linkage is incomplete",()=>{const base=record(),incomplete={...base,field_action:{...base.field_action!,after_image_url:null}};render(<FieldActionReview record={incomplete}/>);expect(fieldActionClosureBlockReason(incomplete)).toContain("전·후 사진");expect(screen.getByRole("alert").textContent).toContain("사진 연결");expect(screen.getByRole("button",{name:"사건 최종 종료"}).hasAttribute("disabled")).toBe(true)});
  it("opens a photo dialog, closes with Escape, and restores focus",async()=>{render(<FieldActionReview record={record()}/>);const trigger=screen.getByRole("button",{name:"조치 전 사진 확대 보기"});fireEvent.click(trigger);expect(screen.getByRole("dialog",{name:"조치 전 사진 확대 보기"})).toBeTruthy();fireEvent.keyDown(document,{key:"Escape"});await new Promise(resolve=>requestAnimationFrame(resolve));expect(screen.queryByRole("dialog")).toBeNull();expect(document.activeElement).toBe(trigger)});
  it("renders closed incidents as read-only with closure information",()=>{render(<FieldActionReview record={record("CLOSED")}/>);expect(screen.getByText("종료 완료")).toBeTruthy();expect(screen.getByText("사건 종료 시각")).toBeTruthy();expect(screen.queryByRole("button",{name:"사건 최종 종료"})).toBeNull()});
});
