import { describe, expect, it } from "vitest";
import type { DashboardIncident } from "@/features/control-dashboard/dashboardTypes";
import { canCompareEvidence, dedupeEvidences, isIncidentActionSupported, reasonLabel, resolveIncidentWorkspaceMode, resolvePrimaryIncidentAction, sortIncidentHistories } from "./incidentDetailDomain";

const incident={public_id:"i",incident_no:"INC",cctv_public_id:"c",status:"CLAIMED",object_category:"DEBRIS",class_code:"TIRE",class_name:"타이어",current_risk_score:80,current_risk_grade:"HIGH",representative_confidence:.9,duration_ms:1000,detection_count:2,assigned_controller:{public_id:"me",display_name:"나"},version_no:2,created_at:"2026-01-01T00:00:00Z",updated_at:"2026-01-01T00:00:00Z"} as DashboardIncident;

describe("incident detail domain",()=>{
 it("resolves adaptive workspace modes",()=>{expect(resolveIncidentWorkspaceMode("NEW")).toBe("EVIDENCE_REVIEW");expect(resolveIncidentWorkspaceMode("DISPATCHED")).toBe("FIELD_RESPONSE");expect(resolveIncidentWorkspaceMode("ACTION_COMPLETED")).toBe("CLOSURE_REVIEW");expect(resolveIncidentWorkspaceMode("CLOSED")).toBe("READ_ONLY")});
 it("checks permission, non-negative version and assignee",()=>{expect(resolvePrimaryIncidentAction(incident,{public_id:"me",permissions:["INCIDENT.DECIDE"]})?.key).toBe("review");expect(resolvePrimaryIncidentAction(incident,{public_id:"other",permissions:["INCIDENT.DECIDE"]})).toBeNull();expect(resolvePrimaryIncidentAction({...incident,status:"NEW",assigned_controller:null,version_no:0},{public_id:"me",permissions:["INCIDENT.CLAIM"]})).toMatchObject({key:"acknowledge",label:"사건 확인"})});
 it("shows API decisions only to the assigned controller with permission and keeps close unsupported",()=>{const reviewing={...incident,status:"UNDER_REVIEW"} as DashboardIncident;const decision=resolvePrimaryIncidentAction(reviewing,{public_id:"me",permissions:["INCIDENT.DECIDE"]});expect(decision?.key).toBe("decide");expect(decision&&isIncidentActionSupported("api",decision.key)).toBe(true);expect(resolvePrimaryIncidentAction(reviewing,{public_id:"me",permissions:[]})).toBeNull();expect(resolvePrimaryIncidentAction(reviewing,{public_id:"other",permissions:["INCIDENT.DECIDE"]})).toBeNull();expect(isIncidentActionSupported("api","close")).toBe(false)});
 it("compares only when the same original frame and bbox are available",()=>{expect(canCompareEvidence({original_image_url:"/frame.jpg",bbox:{x:.1,y:.1,width:.2,height:.2}})).toBe(true);expect(canCompareEvidence({original_image_url:null,bbox:{x:.1,y:.1,width:.2,height:.2}})).toBe(false);expect(canCompareEvidence({original_image_url:"/frame.jpg",bbox:null})).toBe(false)});
 it("keeps readable AI reason labels",()=>{expect(reasonLabel.REPEAT_DETECTION).toBe("반복 탐지 기준 통과")});
 it("deduplicates evidence public ids",()=>{expect(dedupeEvidences([{detection_public_id:"a"},{detection_public_id:"a"},{detection_public_id:"b"}])).toHaveLength(2)});
 it("sorts histories without mutating the source",()=>{const source=[{public_id:"b",event_type:"B",label:"두 번째",actor_name:null,occurred_at:"2026-01-02T00:00:00Z",detail:null},{public_id:"c",event_type:"C",label:"세 번째",actor_name:null,occurred_at:"2026-01-01T00:00:00Z",detail:null},{public_id:"a",event_type:"A",label:"첫 번째",actor_name:null,occurred_at:"2026-01-02T00:00:00Z",detail:null}];const before=[...source];expect(sortIncidentHistories(source).map(item=>item.public_id)).toEqual(["c","a","b"]);expect(source).toEqual(before)});
});
