import { describe,expect,it } from "vitest";
import { canUsePrimaryAction,countKpi,dispatchStatusLabel,filterDashboardRail,formatCompactKst,formatKst,formatRiskGrade,highRiskAlertKey,incidentStatusForDispatch,prioritizeIncidents,resolveDispatchPresentation,resolveIncidentSteps,resolvePrimaryActionAvailability,resolveUrgentIncidentSelection,riskLabel,selectHighRiskAlert,selectIncidentForCctv } from "./dashboardDomain";
import type { DashboardCctv, DashboardDispatch, DashboardIncident } from "./dashboardTypes";
const incident=(status:DashboardIncident["status"],grade:DashboardIncident["current_risk_grade"]="HIGH"):DashboardIncident=>({public_id:`i-${status}`,incident_no:"INC-1",cctv_public_id:"c-1",status,object_category:"DEBRIS",class_code:"TIRE",class_name:"타이어",current_risk_score:80,current_risk_grade:grade,representative_confidence:.9,duration_ms:1000,detection_count:2,representative_image_kind:null,assigned_controller:null,claimed_at:null,version_no:1,created_at:"2026-07-19T00:00:00.000Z",updated_at:"2026-07-19T00:00:00.000Z"});
describe("control dashboard domain",()=>{
  it("maps risk grade codes to the unified Korean labels",()=>{expect(riskLabel).toEqual({CRITICAL:"긴급",HIGH:"주의",MEDIUM:"보통",LOW:"낮음"});expect(formatRiskGrade("HIGH")).toBe("주의");expect(formatRiskGrade("UNKNOWN")).toBe("UNKNOWN")});
  it("calculates the four operational KPI groups",()=>{const items=[incident("NEW"),incident("ACKNOWLEDGED"),incident("CLAIMED"),incident("DISPATCHED"),incident("ACTION_COMPLETED")];expect(countKpi(items,"unconfirmed")).toBe(1);expect(countKpi(items,"review")).toBe(2);expect(countKpi(items,"dispatch")).toBe(1);expect(countKpi(items,"closing")).toBe(1)});
  it("puts an unconfirmed critical incident first",()=>{expect(prioritizeIncidents([incident("DISPATCHED","CRITICAL"),incident("NEW","HIGH"),incident("NEW","CRITICAL")])[0].current_risk_grade).toBe("CRITICAL")});
  it("uses a stable operational order after urgent incidents",()=>{
    const items=[
      {...incident("ACTION_COMPLETED"),public_id:"closing"},
      {...incident("DISPATCHED"),public_id:"dispatch",assigned_controller:{public_id:"controller",display_name:"관제자"}},
      {...incident("UNDER_REVIEW"),public_id:"review",assigned_controller:{public_id:"controller",display_name:"관제자"}},
      {...incident("ACKNOWLEDGED"),public_id:"reassign"},
    ];
    expect(prioritizeIncidents(items).map(item=>item.public_id)).toEqual(["reassign","review","dispatch","closing"]);
  });
  it("maps rejected dispatch back to dispatch requested",()=>{expect(incidentStatusForDispatch("REJECTED")).toBe("DISPATCH_REQUESTED");expect(incidentStatusForDispatch("ARRIVED")).toBe("ON_SCENE")});
  it("requires permissions, a non-negative version and matching assignee",()=>{const item={...incident("CLAIMED"),assigned_controller:{public_id:"other",display_name:"다른 관제자"}};expect(canUsePrimaryAction(item,{publicId:"me",apiPermissions:["INCIDENT.DECIDE"]})).toBe(false);expect(canUsePrimaryAction({...item,assigned_controller:{public_id:"me",display_name:"나"},version_no:0},{publicId:"me",apiPermissions:["INCIDENT.DECIDE"]})).toBe(true);expect(canUsePrimaryAction({...item,assigned_controller:{public_id:"me",display_name:"나"},version_no:-1},{publicId:"me",apiPermissions:["INCIDENT.DECIDE"]})).toBe(false)});
  it("requires INCIDENT.CLAIM to acknowledge a new incident",()=>{const item={...incident("NEW"),version_no:0};expect(canUsePrimaryAction(item,{publicId:"me",apiPermissions:["INCIDENT.READ_ALL"]})).toBe(false);expect(canUsePrimaryAction(item,{publicId:"me",apiPermissions:["INCIDENT.CLAIM"]})).toBe(true)});
  it("selects the highest-priority incident linked to a CCTV without borrowing another CCTV incident",()=>{
    const critical={...incident("NEW","CRITICAL"),public_id:"critical",cctv_public_id:"c-2"};
    const high={...incident("NEW","HIGH"),public_id:"high",cctv_public_id:"c-2"};
    expect(selectIncidentForCctv([high,critical],"c-2")?.public_id).toBe("critical");
    expect(selectIncidentForCctv([high,critical],"c-3")).toBeNull();
  });
  it("renders backend UTC timestamps in KST",()=>{expect(formatKst("2026-07-20T00:00:00.000Z")).toContain("09:00")});
  it("renders a compact comparable KST timestamp",()=>{expect(formatCompactKst("2026-07-19T05:24:00.000Z")).toBe("07.19 14:24")});
  it("reports the exact reason a review action is blocked",()=>{
    const assigned={...incident("UNDER_REVIEW"),assigned_controller:{public_id:"other",display_name:"다른 관제자"}};
    expect(resolvePrimaryActionAvailability(assigned,{publicId:"me",apiPermissions:[]})).toMatchObject({allowed:false,reason:"현재 계정에는 사건 판정 권한이 없습니다."});
    expect(resolvePrimaryActionAvailability(assigned,{publicId:"me",apiPermissions:["INCIDENT.DECIDE"]})).toMatchObject({allowed:false,reason:"담당 관제자만 판정을 진행할 수 있습니다."});
  });
  it("marks dispatch and field steps as not applicable for false positives",()=>{const steps=resolveIncidentSteps("FALSE_POSITIVE");expect(steps[4]).toMatchObject({state:"skipped",stateLabel:"해당 없음"});expect(steps[5]).toMatchObject({state:"skipped",stateLabel:"해당 없음"});expect(steps[6]).toMatchObject({state:"done",stateLabel:"처리 완료"})});
  it("filters the priority rail by assignment and incident or CCTV search",()=>{const cctv={public_id:"c-1",cctv_code:"C",cctv_name:"CAM 01",source_type:"ITS",stream_type:"LIVE",direction_code:"ASC",operational_status:"NORMAL",has_stream:true,fallback_used:false,video_state:"PLAYING",road:{road_name:"도로"},road_section:{section_name:"구간"}}as DashboardCctv;const unassigned=incident("NEW"),mine={...incident("UNDER_REVIEW"),public_id:"mine",assigned_controller:{public_id:"me",display_name:"나"}};expect(filterDashboardRail([unassigned,mine],[cctv],"unassigned","", "me")).toEqual([unassigned]);expect(filterDashboardRail([unassigned,mine],[cctv],"mine","INC-1","me")).toEqual([mine]);expect(filterDashboardRail([unassigned],[cctv],"high","CAM 01")).toEqual([unassigned])});
  it("dismisses only the current version of a high-risk alert",()=>{const first={...incident("NEW","CRITICAL"),public_id:"first"},second={...incident("NEW","HIGH"),public_id:"second"};expect(selectHighRiskAlert([second,first],new Set())?.public_id).toBe("first");expect(selectHighRiskAlert([second,first],new Set([highRiskAlertKey(first)]))?.public_id).toBe("second");expect(selectHighRiskAlert([{...first,version_no:2}],new Set([highRiskAlertKey(first)]))?.version_no).toBe(2)});
  it("resolves an urgent selection only by exact incident and linked CCTV public IDs",()=>{const item={...incident("NEW"),public_id:"incident-uuid",incident_no:"INC-20260719-0013"};const cctv={public_id:"c-1"}as DashboardCctv;expect(resolveUrgentIncidentSelection([item],[cctv],"incident-uuid")).toEqual({incident:item,cctv});expect(resolveUrgentIncidentSelection([item],[cctv],"INC-20260719-0013")).toBeNull();expect(resolveUrgentIncidentSelection([item],[],"incident-uuid")).toBeNull()});
  it("separates controller, responder and dispatch status presentation",()=>{const assigned={...incident("DISPATCH_REQUESTED"),assigned_controller:{public_id:"controller",display_name:"조정민"}};const requested={public_id:"dispatch",incident_public_id:assigned.public_id,status:"REQUESTED",responder_label:"이출동",requested_at:assigned.created_at,updated_at:assigned.updated_at}as DashboardDispatch;expect(resolveDispatchPresentation(assigned,null)).toMatchObject({controller:"조정민",responder:"미배정",status:"출동 배정 필요",active:false,hasDispatch:false,compact:"관제 조정민 · 출동 배정 필요"});expect(resolveDispatchPresentation(assigned,requested)).toMatchObject({responder:"이출동",status:"수락 대기",active:true,hasDispatch:true,compact:"관제 조정민 · 출동 이출동 · 수락 대기"});expect(resolveDispatchPresentation({...assigned,assigned_controller:null},null).controller).toBe("미배정")});
  it("maps every dispatch enum without reusing the incident-stage label",()=>{expect(dispatchStatusLabel).toEqual({REQUESTED:"수락 대기",ACCEPTED:"수락 완료",DEPARTED:"출발",EN_ROUTE:"이동 중",ARRIVED:"현장 도착",ACTION_IN_PROGRESS:"조치 중",ACTION_COMPLETED:"조치 완료",REJECTED:"출동 거절",CANCELLED:"출동 취소"})});
  it("ignores a dispatch that contradicts a pre-dispatch incident stage",()=>{const item=incident("NEW"),stale={public_id:"dispatch",incident_public_id:item.public_id,status:"REQUESTED",responder_label:"이출동",requested_at:item.created_at,updated_at:item.updated_at}as DashboardDispatch;expect(resolveDispatchPresentation(item,stale)).toMatchObject({responder:"미배정",status:"출동 전",active:false,hasDispatch:false})});
});
