import{describe,expect,it}from"vitest";
import{countKpi,activeStatuses}from"./dashboardDomain";
import{createMockDashboardSnapshot,MockDashboardAdapter}from"./mockDashboardAdapter";

describe("mock dashboard data path",()=>{
 it("creates six CCTV cards through the mock snapshot mapper",()=>{expect(createMockDashboardSnapshot().cctvs).toHaveLength(6)});
 it("returns six CCTV cards from MockDashboardAdapter.load",async()=>{expect((await new MockDashboardAdapter().load()).cctvs).toHaveLength(6)});
 it("uses unique resource identifiers without CCTV/incident collisions",()=>{const snapshot=createMockDashboardSnapshot();const cctvIds=snapshot.cctvs.map(item=>item.public_id),incidentIds=snapshot.incidents.map(item=>item.public_id);expect(new Set(cctvIds).size).toBe(cctvIds.length);expect(new Set(incidentIds).size).toBe(incidentIds.length);expect(cctvIds.some(id=>incidentIds.includes(id))).toBe(false)});
 it("links every incident to an existing mock CCTV",()=>{const snapshot=createMockDashboardSnapshot(),cctvIds=new Set(snapshot.cctvs.map(item=>item.public_id));expect(snapshot.incidents.every(item=>cctvIds.has(item.cctv_public_id))).toBe(true)});
 it("preserves CCTV contracts, incidents, and non-zero operational KPIs",()=>{const snapshot=createMockDashboardSnapshot(),active=snapshot.incidents.filter(item=>activeStatuses.includes(item.status));expect(snapshot.incidents.length).toBeGreaterThan(0);expect(snapshot.summary.total_count).toBe(snapshot.incidents.length);expect(["NORMAL","DELAYED","FAULT","INACTIVE","UNKNOWN"]).toContain(snapshot.cctvs[0].operational_status);expect(snapshot.cctvs.every(item=>item.source_type&&item.stream_type&&item.direction_code)).toBe(true);expect(["unconfirmed","review","dispatch","closing"].map(key=>countKpi(active,key as "unconfirmed"|"review"|"dispatch"|"closing")).some(count=>count>0)).toBe(true)});
 it("uses the dedicated original frame and bbox only for the CAM04 box incident",()=>{const snapshot=createMockDashboardSnapshot();const cam04Box=snapshot.incidents.find(item=>item.incident_no==="INC-20260719-0007")!;expect(cam04Box).toMatchObject({class_code:"BOX",representative_image_url:"/images/incidents/cam04-box-highway-v2.png",representative_image_kind:"ORIGINAL",detection_bbox:{x:.505,y:.655,width:.06,height:.085}});const otherBox=snapshot.incidents.find(item=>item.class_code==="BOX"&&item.incident_no!==cam04Box.incident_no)!;expect(otherBox.representative_image_url).toBe("/images/incidents/response-ai-detection-v2.png");expect(otherBox.detection_bbox).toEqual({x:.52,y:.55,width:.08,height:.1});expect(snapshot.incidents.filter(item=>item.incident_no!==cam04Box.incident_no).some(item=>item.representative_image_url==="/images/incidents/cam04-box-highway-v2.png")).toBe(false)});
});
