"use client";
import Link from "next/link";
import { useEffect,useMemo,useRef,useState } from "react";
import { useSearchParams } from "next/navigation";
import { useAuth } from "@/components/auth/AuthContext";
import type { UserRole } from "@/types/auth";
import { createUserManagementAdapter } from "./mockUserManagementAdapter";
import { mockOrganizations } from "./mockUserFixtures";
import type { ManagedUser } from "./userManagementTypes";
import {RoleBadge,RoleBadgeGroup,RoleDescription} from "./RolePresentation";
import {ROLE_ORDER,ROLE_PRESENTATIONS,sortRoles} from "./rolePresentationConfig";
type Styles=Record<string,string>;type Panel="edit"|"roles"|"deactivate"|null;const allRoles:UserRole[]=ROLE_ORDER;
const fmt=(v:string|null)=>v?new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(v)):"로그인 기록 없음";
export function AdminUserDetail({publicId,styles}:{publicId:string;styles:Styles}){
 const repo=useMemo(()=>createUserManagementAdapter(),[]),{user:me}=useAuth(),search=useSearchParams();const[data,setData]=useState<ManagedUser|null|undefined>(undefined);const[panel,setPanel]=useState<Panel>(null);const[toast,setToast]=useState(search.get("created")==="1"?"운영 사용자가 등록되었습니다.":"");const trigger=useRef<HTMLButtonElement|null>(null);
 const load=()=>{const c=new AbortController();void repo.getUserDetail(publicId,c.signal).then(setData).catch(error=>{if(!(error instanceof DOMException&&error.name==="AbortError"))setData(null)});return()=>c.abort()};useEffect(load,[publicId,repo]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2500);return()=>clearTimeout(t)},[toast]);
 const open=(next:Panel,e:React.MouseEvent<HTMLButtonElement>)=>{trigger.current=e.currentTarget;setPanel(next)},close=()=>{setPanel(null);requestAnimationFrame(()=>trigger.current?.focus())};const canWrite=me?.apiPermissions.includes("USER.WRITE"),canRoles=me?.apiPermissions.includes("ROLE.MANAGE");
 if(data===undefined)return <main className={styles.page}><div className={styles.form}>사용자 정보를 불러오고 있습니다.</div></main>;
 if(data===null)return <main className={styles.page}><div className={styles.form}><h1>사용자를 찾을 수 없습니다.</h1><p>삭제되었거나 접근할 수 없는 사용자입니다.</p><Link className={styles.back} href="/admin/users">사용자 목록으로</Link></div></main>;
 const org=data.organization?.name??"소속 없음";
 return <main className={styles.page}><Link className={styles.back} href="/admin/users">← 사용자 목록</Link><header className={styles.detailHeader}><div><span className={styles.status} data-inactive={data.accountStatus==="INACTIVE"}>{data.accountStatus==="ACTIVE"?"활성":"비활성"}</span><h1>{data.userName}</h1><RoleBadgeGroup roles={data.roles}/><p>{org}</p></div><div className={styles.detailActions}>{canWrite&&data.accountStatus==="ACTIVE"&&<button type="button" onClick={e=>open("edit",e)}>정보 수정</button>}{canRoles&&data.accountStatus==="ACTIVE"&&<button type="button" onClick={e=>open("roles",e)}>역할 관리</button>}{canWrite&&data.accountStatus==="ACTIVE"&&<button type="button" onClick={e=>open("deactivate",e)}>계정 비활성화</button>}</div></header><div className={styles.detailGrid}><section className={styles.detailSection}><h2>기본 정보</h2><dl>{[["이름",data.userName],["이메일",data.email],["전화번호",data.phone??"등록되지 않음"],["소속 기관",org],["계정 상태",data.accountStatus],["마지막 로그인",fmt(data.lastLoginAt)],["등록일",fmt(data.createdAt)],["최근 수정일",fmt(data.updatedAt)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section><section className={styles.detailSection}><h2>역할 및 접근 범위</h2><RoleDescription roles={data.roles} showCodes/></section><section className={styles.detailSection}><h2>최근 계정 활동</h2>{data.changes.length?<ol className={styles.activity}>{data.changes.map(c=><li key={c.id}><strong>{c.action}</strong><span>{c.summary}</span><small>{fmt(c.occurredAt)} · {c.actor}</small></li>)}</ol>:<p>기록된 계정 활동이 없습니다.</p>}</section>{data.responderProfile&&<section className={styles.detailSection}><h2>출동 업무 설정</h2><p>{data.responderProfile.responderCode} · {data.responderProfile.dutyStatus} · {data.responderProfile.linked?"연결됨":"연결 해제 예정"}</p></section>}</div>{panel==="edit"&&<EditSheet user={data} styles={styles} repo={repo} close={close} saved={next=>{setData(next);setToast("사용자 정보가 수정되었습니다.");close()}}/>}{panel==="roles"&&<RoleSheet user={data} styles={styles} repo={repo} close={close} saved={next=>{setData(next);setToast("사용자 역할이 변경되었습니다.");close()}}/>}{panel==="deactivate"&&<DeactivateDialog user={data} styles={styles} repo={repo} close={close} saved={next=>{setData(next);setToast("사용자 계정이 비활성화되었습니다.");close()}}/>}{toast&&<div className={styles.toast} role="status">{toast}</div>}</main>
}
function EditSheet({user,styles,repo,close,saved}:{user:ManagedUser;styles:Styles;repo:ReturnType<typeof createUserManagementAdapter>;close:()=>void;saved:(u:ManagedUser)=>void}){const[name,setName]=useState(user.userName),[phone,setPhone]=useState(user.phone??""),[org,setOrg]=useState(user.organization?.publicId??""),[busy,setBusy]=useState(false);const changed=name.trim()!==user.userName||phone!==user.phone||org!==user.organization?.publicId;return <div className={styles.overlay} onMouseDown={e=>e.target===e.currentTarget&&close()}><section className={styles.sheet} role="dialog" aria-modal="true"><header><div><h2>기본정보 수정</h2><p>사용자의 연락처와 소속 정보를 변경합니다.</p></div><button onClick={close} aria-label="기본정보 수정 닫기">×</button></header><div className={styles.fields}><label className={`${styles.field} ${styles.full}`}><span>이메일</span><input value={user.email} readOnly/><small>로그인 식별자로 사용되는 이메일은 이 화면에서 변경할 수 없습니다.</small></label><label className={`${styles.field} ${styles.full}`}><span>이름</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label className={`${styles.field} ${styles.full}`}><span>전화번호</span><input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className={`${styles.field} ${styles.full}`}><span>소속</span><select value={org} onChange={e=>setOrg(e.target.value)}>{mockOrganizations.map(o=><option value={o.publicId} key={o.publicId}>{o.name}</option>)}</select></label></div><footer className={styles.actions}><button onClick={close}>취소</button><button className={styles.primary} disabled={!changed||busy||name.trim().length<2} onClick={async()=>{setBusy(true);saved(await repo.updateUser(user.publicId,{userName:name,phone:phone||null,organizationPublicId:org}))}}>변경 저장</button></footer></section></div>}
function RoleSheet({user,styles,repo,close,saved}:{user:ManagedUser;styles:Styles;repo:ReturnType<typeof createUserManagementAdapter>;close:()=>void;saved:(u:ManagedUser)=>void}){const[roles,setRoles]=useState(user.roles),[reason,setReason]=useState("");const added=sortRoles(roles.filter(role=>!user.roles.includes(role))),removed=sortRoles(user.roles.filter(role=>!roles.includes(role)));return <div className={styles.overlay}><section className={styles.sheet} role="dialog" aria-modal="true"><header><h2>역할 관리</h2><button onClick={close} aria-label="역할 관리 닫기">×</button></header><section className={styles.review}><h3>현재 역할</h3><RoleBadgeGroup roles={user.roles}/><h3>변경 후 역할</h3><RoleBadgeGroup roles={roles}/></section><div className={styles.roleGrid}>{allRoles.map(r=><button type="button" className={styles.roleCard} aria-pressed={roles.includes(r)} key={r} onClick={()=>setRoles(current=>current.includes(r)?current.filter(x=>x!==r):[...current,r])}><RoleBadge role={r}/><span>{ROLE_PRESENTATIONS[r].shortDescription}</span><b aria-hidden="true">{roles.includes(r)?"✓":""}</b></button>)}</div>{(added.length>0||removed.length>0)&&<section className={styles.review}><h3>변경 내용</h3>{added.map(role=><p key={`add-${role}`}>추가 + <RoleBadge role={role}/></p>)}{removed.map(role=><p key={`remove-${role}`}>해제 − <RoleBadge role={role}/></p>)}</section>}<label className={`${styles.field} ${styles.full}`}><span>변경 사유 *</span><textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><p className={styles.notice}>역할 변경 후 메뉴와 접근 권한이 변경됩니다. 실제 API 연결 시 기존 로그인 세션이 종료될 수 있습니다.</p><footer className={styles.actions}><button onClick={close}>취소</button><button className={styles.primary} disabled={!roles.length||!reason.trim()||(!added.length&&!removed.length)} onClick={async()=>saved(await repo.updateUserRoles(user.publicId,{roles,reason:reason.trim()}))}>역할 변경</button></footer></section></div>}
function DeactivateDialog({user,styles,repo,close,saved}:{user:ManagedUser;styles:Styles;repo:ReturnType<typeof createUserManagementAdapter>;close:()=>void;saved:(u:ManagedUser)=>void}){const[reason,setReason]=useState(""),[error,setError]=useState("");return <div className={styles.dialogWrap}><section className={styles.dialog} role="alertdialog" aria-modal="true"><h2>{user.userName} 사용자를 비활성화하시겠습니까?</h2><ul><li>신규 로그인이 차단됩니다.</li><li>실제 API 연결 시 활성 세션이 종료됩니다.</li><li>기존 사건·출동·감사 이력은 유지됩니다.</li></ul>{(user.activeAssignments??0)>0?<p className={styles.error}>현재 담당 중인 업무 {user.activeAssignments}건이 있습니다. 담당 업무를 먼저 재배정해 주세요.</p>:<label className={styles.field}><span>비활성화 사유 *</span><textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>}{error&&<p className={styles.error}>{error}</p>}<footer className={styles.actions}><button onClick={close}>취소</button><button className={styles.danger} disabled={!reason.trim()||(user.activeAssignments??0)>0} onClick={async()=>{try{saved(await repo.deactivateUser(user.publicId,{reason:reason.trim()}))}catch(e){setError(e instanceof Error?e.message:"처리하지 못했습니다.")}}}>계정 비활성화</button></footer></section></div>}
