"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {getRoleLabel} from "@/lib/auth/roleLabels";
import type {UserRole} from "@/types/auth";
import {createUserManagementAdapter} from "./mockUserManagementAdapter";
import {OrganizationExplorer} from "./OrganizationExplorer";
import type {OrganizationOption,ResponderDutyStatus,UserManagementError} from "./userManagementTypes";
import {RoleBadgeGroup} from "./RolePresentation";
import {ROLE_PRESENTATIONS} from "./rolePresentationConfig";
import {RoleIcon} from "./RoleIcon";

type Styles=Record<string,string>;type Availability="idle"|"checking"|"available"|"duplicate";
type Form={userName:string;email:string;phone:string;password:string;confirm:string;organizationId:string;primaryRole:UserRole|null;additional:UserRole[];responderCode:string;dutyStatus:ResponderDutyStatus;coverageArea:string;dispatchEnabled:boolean};
const roleOptions:UserRole[]=["SYSTEM_ADMIN","CONTROL_MANAGER","CONTROLLER","RESPONDER"];
const initial:Form={userName:"",email:"",phone:"",password:"",confirm:"",organizationId:"",primaryRole:null,additional:[],responderCode:"",dutyStatus:"AVAILABLE",coverageArea:"",dispatchEnabled:true};
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export const normalizeAdminPhone=(value:string)=>value.replace(/\D/g,"").replace(/^82(?=10)/,"0");
export const formatAdminPhone=(value:string)=>{const digits=normalizeAdminPhone(value).slice(0,11);return digits.length>7?digits.replace(/(\d{3})(\d{4})(\d{0,4})/,"$1-$2-$3"):digits.length>3?digits.replace(/(\d{3})(\d{0,4})/,"$1-$2"):digits};

export function CreateUserWizard({styles}:{styles:Styles}){
 const router=useRouter(),repo=useMemo(()=>createUserManagementAdapter(),[]);
 const[form,setForm]=useState<Form>(initial),[organizations,setOrganizations]=useState<OrganizationOption[]>([]),[orgLoading,setOrgLoading]=useState(true),[orgError,setOrgError]=useState("");
 const[emailState,setEmailState]=useState<Availability>("idle"),[codeState,setCodeState]=useState<Availability>("idle"),[showPassword,setShowPassword]=useState(false),[showConfirm,setShowConfirm]=useState(false),[additionalOpen,setAdditionalOpen]=useState(false);
 const[step,setStep]=useState<1|2|3>(1),[exitOpen,setExitOpen]=useState(false),[busy,setBusy]=useState(false),[submitError,setSubmitError]=useState(""),[submitted,setSubmitted]=useState(false),[touched,setTouched]=useState<Set<string>>(new Set());
 const roles=useMemo(()=>form.primaryRole?[...new Set([form.primaryRole,...form.additional.filter(role=>role!==form.primaryRole)])]:[],[form.primaryRole,form.additional]);
 const responder=roles.includes("RESPONDER"),organization=organizations.find(item=>item.publicId===form.organizationId);
 const validity={role:Boolean(form.primaryRole),name:form.userName.trim().length>=2&&form.userName.trim().length<=100,email:emailPattern.test(form.email)&&form.email.length<=254&&emailState==="available",phone:!form.phone||normalizeAdminPhone(form.phone).length===11,password:form.password.length>=8&&form.password.length<=64&&/[A-Za-z]/.test(form.password)&&/\d/.test(form.password),confirm:Boolean(form.confirm)&&form.password===form.confirm,organization:Boolean(form.organizationId),responder:!responder||(/^[A-Z0-9-]{3,20}$/.test(form.responderCode)&&codeState==="available"&&Boolean(form.coverageArea.trim()))};
 const ready=Object.values(validity).every(Boolean)&&!orgLoading;
 const dirty=Object.entries(form).some(([key,value])=>key==="dispatchEnabled"?value!==true:key==="dutyStatus"?value!=="AVAILABLE":Array.isArray(value)?value.length>0:Boolean(value));
 const loadOrganizations=useCallback(()=>{const controller=new AbortController();setOrgLoading(true);setOrgError("");repo.listOrganizations(controller.signal).then(setOrganizations).catch(error=>{if(!(error instanceof DOMException&&error.name==="AbortError"))setOrgError("소속 기관을 불러오지 못했습니다.")}).finally(()=>setOrgLoading(false));return controller},[repo]);
 useEffect(()=>{const controller=loadOrganizations();return()=>controller.abort()},[loadOrganizations]);
 useEffect(()=>{if(!emailPattern.test(form.email)||form.email.length>254){setEmailState("idle");return}setEmailState("checking");const timer=setTimeout(()=>void repo.checkEmailAvailability(form.email).then(result=>setEmailState(result.available?"available":"duplicate")),350);return()=>clearTimeout(timer)},[form.email,repo]);
 useEffect(()=>{if(!responder||!/^[A-Z0-9-]{3,20}$/.test(form.responderCode)){setCodeState("idle");return}setCodeState("checking");const timer=setTimeout(()=>void repo.checkResponderCodeAvailability(form.responderCode).then(result=>setCodeState(result.available?"available":"duplicate")),350);return()=>clearTimeout(timer)},[form.responderCode,responder,repo]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};addEventListener("beforeunload",warn);return()=>removeEventListener("beforeunload",warn)},[dirty]);
 const set=<K extends keyof Form>(key:K,value:Form[K])=>setForm(current=>({...current,[key]:value}));
 const touch=(key:string)=>setTouched(current=>new Set(current).add(key));
 const showError=(key:string)=>submitted||touched.has(key);
 const focusFirstError=()=>{const order:[keyof typeof validity,string][]=[["role","account-type-system-admin"],["organization","new-user-org"],["name","new-user-name"],["email","new-user-email"],["phone","new-user-phone"],["password","new-user-password"],["confirm","new-user-confirm"],["responder","new-responder-code"]];const target=order.find(([key])=>!validity[key]);if(target){document.getElementById(target[1])?.focus();document.getElementById(target[1])?.scrollIntoView({behavior:"smooth",block:"center"})}};
 const goTop=()=>requestAnimationFrame(()=>document.querySelector<HTMLElement>(`.${styles.stepProgress}`)?.scrollIntoView({behavior:"smooth",block:"start"}));
 const basicReady=validity.role&&validity.organization&&validity.name&&validity.email&&validity.phone;
 const nextBasic=()=>{if(!basicReady){setTouched(current=>new Set([...current,"role","organization","name","email","phone"]));focusFirstError();return}setStep(2);setSubmitted(false);goTop()};
 const inspect=()=>{setSubmitted(true);if(!ready){focusFirstError();return}setStep(3);goTop()};
 const goStep=(value:1|2|3)=>{setStep(value);if(value<3)setSubmitted(false);goTop()};
 const requestLeave=()=>dirty?setExitOpen(true):router.push("/admin/users");
 const submit=async()=>{if(!ready||busy)return;setBusy(true);setSubmitError("");try{const created=await repo.createUser({email:form.email.trim().toLowerCase(),password:form.password,userName:form.userName.trim(),phone:normalizeAdminPhone(form.phone)||undefined,organizationPublicId:form.organizationId,roles,responderProfile:responder?{responderCode:form.responderCode.trim().toUpperCase(),dutyStatus:form.dutyStatus,coverageArea:form.coverageArea.trim()||null,isDispatchEnabled:form.dispatchEnabled}:undefined});router.push(`/admin/users/${created.publicId}?created=1`)}catch(error){const managed=error as UserManagementError,id=managed.code==="USER_EMAIL_DUPLICATE"?"new-user-email":managed.code==="RESPONDER_CODE_DUPLICATE"?"new-responder-code":null;setSubmitError(error instanceof Error?error.message:"사용자를 등록하지 못했습니다.");if(id){goStep(id==="new-user-email"?1:2);setTimeout(()=>{document.getElementById(id)?.focus();document.getElementById(id)?.scrollIntoView({block:"center"})},0)}}finally{setBusy(false)}};
 const requiredComplete=[validity.role,validity.organization,validity.name,validity.email,validity.password,validity.confirm].filter(Boolean).length;
 return <main className={styles.page}>
  <header className={styles.header}><div><nav aria-label="현재 위치"><Link href="/admin/users">사용자 관리</Link><span>/</span><b>운영 사용자 등록</b></nav><h1>운영 사용자 등록</h1><p>업무에 필요한 계정과 역할, 소속 정보를 설정합니다.</p></div><button className={styles.back} type="button" onClick={requestLeave}>사용자 목록</button></header>
  <div className={styles.singleForm}>
   <nav className={styles.stepProgress} aria-label="운영 계정 등록 단계">{(["기본 정보","계정 및 업무 설정","등록 정보 검토"] as const).map((label,index)=>{const number=(index+1) as 1|2|3;return <button type="button" key={label} aria-current={step===number?"step":undefined} data-complete={step>number} disabled={number>step} onClick={()=>number<step&&goStep(number)}><span>{number}</span><b>{label}</b></button>})}</nav>
   {step===1&&<>
   <section className={styles.workSection} aria-labelledby="account-type-title"><header><h2 id="account-type-title">업무 설정</h2><p>담당 업무와 접근 범위를 기준으로 역할과 소속을 설정해 주세요.</p></header>
    <div className={styles.roleGrid} role="radiogroup" aria-label="기준 역할">{roleOptions.map(role=>{const meta=ROLE_PRESENTATIONS[role];return <button id={`account-type-${role.toLowerCase().replace("_","-")}`} type="button" role="radio" aria-checked={form.primaryRole===role} key={role} onBlur={()=>touch("role")} onClick={()=>{set("primaryRole",role);set("additional",form.additional.filter(item=>item!==role))}} style={{"--role-accent":meta.color.accent,"--role-surface":meta.color.background,"--role-border":meta.color.border} as React.CSSProperties}><i><RoleIcon kind={role}/></i><span><strong>{meta.label}</strong><small>{meta.shortDescription}</small><code>{role}</code></span><b aria-hidden="true">{form.primaryRole===role?"✓":""}</b></button>})}</div>
    {showError("role")&&!validity.role&&<p className={styles.inlineError}>기준 역할을 선택해 주세요.</p>}
    {form.primaryRole&&<p className={styles.roleGuidance}><RoleIcon kind={form.primaryRole}/>{ROLE_PRESENTATIONS[form.primaryRole].shortDescription}</p>}
    <div className={styles.workControls}><Field styles={styles} id="new-user-org" label="소속 기관" required error={orgError||showError("organization")&&!validity.organization?"소속 기관을 선택해 주세요.":""}><div onBlur={()=>touch("organization")}><OrganizationExplorer triggerId="new-user-org" organizations={organizations} value={form.organizationId?{type:"ORGANIZATION",publicId:form.organizationId}:{type:"ALL"}} onChange={value=>set("organizationId",value.type==="ORGANIZATION"?value.publicId:"")} label="소속 기관" placeholder="소속 기관을 선택해 주세요" loading={orgLoading} error={orgError} onRetry={()=>loadOrganizations()}/></div></Field>
     <div className={styles.additionalRoles}><button type="button" aria-expanded={additionalOpen} onClick={()=>setAdditionalOpen(value=>!value)}>+ 다른 역할 함께 부여</button>{additionalOpen&&<div className={styles.additionalOptions} role="group" aria-label="추가 역할">{roleOptions.filter(role=>role!==form.primaryRole).map(role=><label key={role}><input type="checkbox" checked={form.additional.includes(role)} onChange={e=>set("additional",e.target.checked?[...new Set([...form.additional,role])]:form.additional.filter(item=>item!==role))}/><RoleIcon kind={role}/>{getRoleLabel(role)}</label>)}</div>}{form.additional.length>0&&<div className={styles.chips}>{form.additional.map(role=><button type="button" key={role} style={{"--role-accent":ROLE_PRESENTATIONS[role].color.accent,"--role-surface":ROLE_PRESENTATIONS[role].color.background,"--role-border":ROLE_PRESENTATIONS[role].color.border} as React.CSSProperties} aria-label={`${getRoleLabel(role)} 추가 역할 제거`} onClick={()=>set("additional",form.additional.filter(item=>item!==role))}><RoleIcon kind={role}/>{getRoleLabel(role)} <span aria-hidden="true">×</span></button>)}</div>}</div>
    </div>
   </section>
   <section><header><h2>계정 정보</h2><p>로그인과 관리자 식별에 사용할 기본 정보를 입력해 주세요.</p></header><div className={styles.fields}>
    <Field styles={styles} id="new-user-name" label="이름" required error={showError("name")&&!validity.name?"이름은 2자 이상 100자 이하로 입력해 주세요.":""}><input id="new-user-name" placeholder="이름을 입력해 주세요" value={form.userName} maxLength={100} autoComplete="name" onBlur={()=>touch("name")} onChange={e=>set("userName",e.target.value)}/></Field>
    <Field styles={styles} id="new-user-email" label="이메일" required error={emailState==="duplicate"?"이미 사용 중인 이메일입니다.":showError("email")&&!validity.email&&emailState!=="checking"?"올바른 이메일 형식으로 입력해 주세요.":""} message={emailState==="checking"?"중복 확인 중…":emailState==="available"?"사용할 수 있는 이메일입니다.":""}><input id="new-user-email" type="email" placeholder="이메일을 입력해 주세요" value={form.email} maxLength={254} autoComplete="email" onBlur={()=>touch("email")} onChange={e=>set("email",e.target.value.toLowerCase())}/></Field>
    <Field styles={styles} id="new-user-phone" label="전화번호" error={showError("phone")&&!validity.phone?"전화번호 11자리를 입력해 주세요.":""}><input id="new-user-phone" inputMode="tel" value={formatAdminPhone(form.phone)} maxLength={18} autoComplete="tel" placeholder="010-0000-0000" onBlur={()=>touch("phone")} onChange={e=>set("phone",e.target.value)}/></Field>
   </div></section></>}
   {step===2&&<><section><header><h2>계정 보안</h2><p>초기 로그인에 사용할 비밀번호를 설정합니다.</p></header><div className={styles.fields}>
    <Field styles={styles} id="new-user-password" label="초기 비밀번호" required error={showError("password")&&!validity.password?"영문과 숫자를 포함해 8~64자로 입력해 주세요.":""}><div className={styles.passwordInput}><input id="new-user-password" type={showPassword?"text":"password"} value={form.password} maxLength={64} autoComplete="new-password" onBlur={()=>touch("password")} onChange={e=>set("password",e.target.value)}/><button type="button" aria-label={showPassword?"비밀번호 숨기기":"비밀번호 보기"} onClick={()=>setShowPassword(value=>!value)}><EyeIcon hidden={!showPassword}/></button></div><PasswordStatus value={form.password} styles={styles}/></Field>
    <Field styles={styles} id="new-user-confirm" label="비밀번호 확인" required error={form.confirm&&form.password!==form.confirm?"비밀번호가 일치하지 않습니다.":showError("confirm")&&!form.confirm?"비밀번호 확인을 입력해 주세요.":""} message={form.confirm&&form.password===form.confirm?"✓ 비밀번호가 일치합니다.":""}><div className={styles.passwordInput}><input id="new-user-confirm" type={showConfirm?"text":"password"} value={form.confirm} maxLength={64} autoComplete="new-password" onBlur={()=>touch("confirm")} onChange={e=>set("confirm",e.target.value)}/><button type="button" aria-label={showConfirm?"비밀번호 확인 숨기기":"비밀번호 확인 보기"} onClick={()=>setShowConfirm(value=>!value)}><EyeIcon hidden={!showConfirm}/></button></div></Field>
   </div><p className={styles.policyNote}><i aria-hidden="true">i</i><span>등록이 완료되면 즉시 로그인할 수 있는 활성 계정으로 생성됩니다.</span></p></section>
   {responder&&<section className={styles.responderSection}><header><h2>출동 담당 정보</h2><p>출동 담당자의 업무 코드와 초기 근무 정보를 설정합니다.</p></header><div className={styles.responderFields}><Field styles={styles} id="new-responder-code" label="담당자 코드" required error={codeState==="duplicate"?"이미 사용 중인 코드입니다.":showError("responder")&&!validity.responder&&codeState!=="checking"?"담당자 코드를 확인해 주세요.":""} message={codeState==="checking"?"중복 확인 중…":codeState==="available"?"사용할 수 있는 코드입니다.":""}><input id="new-responder-code" value={form.responderCode} maxLength={20} placeholder="RSP-001" onBlur={()=>touch("responder")} onChange={e=>set("responderCode",e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g,""))}/></Field><Field styles={styles} id="new-coverage" label="담당 구역" required error={showError("responder")&&!form.coverageArea.trim()?"담당 구역을 입력해 주세요.":""}><input id="new-coverage" value={form.coverageArea} maxLength={100} placeholder="담당 구역을 입력해 주세요" onBlur={()=>touch("responder")} onChange={e=>set("coverageArea",e.target.value)}/></Field><Field styles={styles} id="new-duty" label="초기 근무 상태" required><div id="new-duty" className={styles.dutySegments} role="radiogroup" aria-label="초기 근무 상태">{([["AVAILABLE","출동 가능"],["OFF_DUTY","근무 외"]] as const).map(([value,label])=><button type="button" role="radio" aria-checked={form.dutyStatus===value} key={value} onClick={()=>set("dutyStatus",value)}>{form.dutyStatus===value&&<span aria-hidden="true">✓</span>}{label}</button>)}</div></Field></div></section>}</>}
   {step===3&&<section className={styles.reviewStep} aria-labelledby="review-title"><header><h2 id="review-title">등록 정보 검토</h2><p>입력한 계정과 업무 설정을 확인한 뒤 운영 계정을 등록합니다.</p></header><div className={styles.reviewGrid}><section><header><h3>기본 정보</h3><button type="button" onClick={()=>goStep(1)}>수정</button></header><Review rows={[["사용자명",form.userName],["이메일",form.email],["전화번호",formatAdminPhone(form.phone)||"입력 안 함"],["소속",organization?.name??""]]}/><RoleBadgeGroup roles={roles}/></section><section><header><h3>계정 설정</h3><button type="button" onClick={()=>goStep(2)}>수정</button></header><Review rows={[["계정 상태","활성"],["초기 비밀번호","설정 완료"]]}/></section>{responder&&<section><header><h3>출동 담당 정보</h3><button type="button" onClick={()=>goStep(2)}>수정</button></header><Review rows={[["담당자 코드",form.responderCode],["담당 구역",form.coverageArea],["초기 근무 상태",form.dutyStatus==="AVAILABLE"?"출동 가능":"근무 외"]]}/></section>}</div></section>}
   {submitError&&<p className={styles.submitError} role="alert">{submitError} 입력값은 유지되었습니다. 다시 확인해 주세요.</p>}
   <footer className={styles.stickyActions}><p>{step===3?"등록 전 정보를 확인해 주세요.":requiredComplete===6?"필수 항목 입력 완료":`필수 항목 ${6-requiredComplete}개 남음`}</p><div>{step===1?<><button type="button" className={styles.cancelStep} onClick={requestLeave}>취소</button><button type="button" className={`${styles.primary} ${styles.nextStep}`} onClick={nextBasic}>다음 단계</button></>:step===2?<><button type="button" onClick={()=>goStep(1)}>이전 단계</button><button type="button" className={styles.primary} onClick={inspect}>등록 정보 검토</button></>:<><button type="button" disabled={busy} onClick={()=>goStep(2)}>이전 단계</button><button type="button" className={styles.primary} disabled={busy} onClick={()=>void submit()}>{busy?"등록 중…":"운영 계정 등록"}</button></>}</div></footer>
  </div>
  {exitOpen&&<div className={styles.dialogWrap}><section className={styles.dialog} role="alertdialog" aria-modal="true" aria-labelledby="exit-title"><h2 id="exit-title">작성 중인 내용을 나갈까요?</h2><p>입력한 등록 정보는 저장되지 않습니다.</p><footer className={styles.actions}><button onClick={()=>setExitOpen(false)}>계속 작성</button><button className={styles.danger} onClick={()=>router.push("/admin/users")}>나가기</button></footer></section></div>}
 </main>
}
function Field({styles,id,label,required,error,message,children}:{styles:Styles;id:string;label:string;required?:boolean;error?:string|false;message?:string;children:React.ReactNode}){return <div className={styles.field}><label htmlFor={id}>{label}{required&&<b aria-label="필수"> *</b>}</label>{children}<small id={`${id}-help`} className={error?styles.error:message?styles.success:undefined} aria-live="polite">{error||message||" "}</small></div>}
function Review({rows}:{rows:string[][]}){return <dl className="review-list">{rows.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>}
function EyeIcon({hidden}:{hidden:boolean}){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/>{hidden&&<path d="m4 4 16 16"/>}</svg>}
function PasswordStatus({value,styles}:{value:string;styles:Styles}){const length=value.length>=8&&value.length<=64,letter=/[A-Za-z]/.test(value),number=/\d/.test(value);return <p className={styles.passwordChecks}><span data-ok={length}>{length?"✓":"○"} 8~64자</span><span data-ok={letter}>{letter?"✓":"○"} 영문 포함</span><span data-ok={number}>{number?"✓":"○"} 숫자 포함</span></p>}
