"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {getRoleLabel} from "@/lib/auth/roleLabels";
import type {UserRole} from "@/types/auth";
import {createUserManagementAdapter} from "./mockUserManagementAdapter";
import {OrganizationExplorer} from "./OrganizationExplorer";
import type {OrganizationOption,ResponderDutyStatus,UserManagementError} from "./userManagementTypes";
import {RoleBadgeGroup,RoleReview} from "./RolePresentation";
import {ROLE_PRESENTATIONS} from "./rolePresentationConfig";

type Styles=Record<string,string>;type Availability="idle"|"checking"|"available"|"duplicate";
type Form={userName:string;email:string;phone:string;password:string;confirm:string;organizationId:string;primaryRole:UserRole|null;additional:UserRole[];responderCode:string;dutyStatus:ResponderDutyStatus;coverageArea:string;dispatchEnabled:boolean};
const roleOptions:UserRole[]=["SYSTEM_ADMIN","CONTROL_MANAGER","CONTROLLER","RESPONDER"];
const initial:Form={userName:"",email:"",phone:"",password:"",confirm:"",organizationId:"",primaryRole:null,additional:[],responderCode:"",dutyStatus:"AVAILABLE",coverageArea:"",dispatchEnabled:true};
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export const normalizeAdminPhone=(value:string)=>value.replace(/\D/g,"").replace(/^82(?=10)/,"0");
export const formatAdminPhone=(value:string)=>{const digits=normalizeAdminPhone(value).slice(0,11);return digits.length>7?digits.replace(/(\d{3})(\d{4})(\d{0,4})/,"$1-$2-$3"):digits.length>3?digits.replace(/(\d{3})(\d{0,4})/,"$1-$2"):digits};

export function CreateUserWizard({styles}:{styles:Styles}){
 const router=useRouter(),repo=useMemo(()=>createUserManagementAdapter(),[]);
 const[form,setForm]=useState<Form>(initial),[organizations,setOrganizations]=useState<OrganizationOption[]>([]),[orgLoading,setOrgLoading]=useState(true),[orgError,setOrgError]=useState("");
 const[emailState,setEmailState]=useState<Availability>("idle"),[codeState,setCodeState]=useState<Availability>("idle"),[showPassword,setShowPassword]=useState(false),[showConfirm,setShowConfirm]=useState(false),[additionalOpen,setAdditionalOpen]=useState(false);
 const[reviewOpen,setReviewOpen]=useState(false),[exitOpen,setExitOpen]=useState(false),[busy,setBusy]=useState(false),[submitError,setSubmitError]=useState(""),[submitted,setSubmitted]=useState(false);
 const reviewTrigger=useRef<HTMLButtonElement>(null),dialogRef=useRef<HTMLElement>(null);
 const roles=useMemo(()=>form.primaryRole?[...new Set([form.primaryRole,...form.additional.filter(role=>role!==form.primaryRole)])]:[],[form.primaryRole,form.additional]);
 const responder=roles.includes("RESPONDER"),organization=organizations.find(item=>item.publicId===form.organizationId);
 const validity={role:Boolean(form.primaryRole),name:form.userName.trim().length>=2&&form.userName.trim().length<=100,email:emailPattern.test(form.email)&&form.email.length<=254&&emailState==="available",phone:!form.phone||normalizeAdminPhone(form.phone).length===11,password:form.password.length>=8&&form.password.length<=64&&/[A-Za-z]/.test(form.password)&&/\d/.test(form.password),confirm:Boolean(form.confirm)&&form.password===form.confirm,organization:Boolean(form.organizationId),responder:!responder||(/^[A-Z0-9-]{3,20}$/.test(form.responderCode)&&codeState==="available")};
 const ready=Object.values(validity).every(Boolean)&&!orgLoading;
 const dirty=Object.entries(form).some(([key,value])=>key==="dispatchEnabled"?value!==true:key==="dutyStatus"?value!=="AVAILABLE":Array.isArray(value)?value.length>0:Boolean(value));
 const loadOrganizations=useCallback(()=>{const controller=new AbortController();setOrgLoading(true);setOrgError("");repo.listOrganizations(controller.signal).then(setOrganizations).catch(error=>{if(!(error instanceof DOMException&&error.name==="AbortError"))setOrgError("소속 기관을 불러오지 못했습니다.")}).finally(()=>setOrgLoading(false));return controller},[repo]);
 useEffect(()=>{const controller=loadOrganizations();return()=>controller.abort()},[loadOrganizations]);
 useEffect(()=>{if(!emailPattern.test(form.email)||form.email.length>254){setEmailState("idle");return}setEmailState("checking");const timer=setTimeout(()=>void repo.checkEmailAvailability(form.email).then(result=>setEmailState(result.available?"available":"duplicate")),350);return()=>clearTimeout(timer)},[form.email,repo]);
 useEffect(()=>{if(!responder||!/^[A-Z0-9-]{3,20}$/.test(form.responderCode)){setCodeState("idle");return}setCodeState("checking");const timer=setTimeout(()=>void repo.checkResponderCodeAvailability(form.responderCode).then(result=>setCodeState(result.available?"available":"duplicate")),350);return()=>clearTimeout(timer)},[form.responderCode,responder,repo]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};addEventListener("beforeunload",warn);return()=>removeEventListener("beforeunload",warn)},[dirty]);
 useEffect(()=>{if(!reviewOpen){reviewTrigger.current?.focus();return}const dialog=dialogRef.current,focusable=()=>[...(dialog?.querySelectorAll<HTMLElement>("button,a[href]")??[])].filter(item=>!item.hasAttribute("disabled"));focusable()[0]?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!busy){setReviewOpen(false);return}if(event.key!=="Tab")return;const items=focusable(),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[reviewOpen,busy]);
 const set=<K extends keyof Form>(key:K,value:Form[K])=>setForm(current=>({...current,[key]:value}));
 const focusFirstError=()=>{const order:[keyof typeof validity,string][]=[["role","account-type-system-admin"],["name","new-user-name"],["email","new-user-email"],["phone","new-user-phone"],["password","new-user-password"],["confirm","new-user-confirm"],["organization","new-user-org"],["responder","new-responder-code"]];const target=order.find(([key])=>!validity[key]);if(target){document.getElementById(target[1])?.focus();document.getElementById(target[1])?.scrollIntoView({behavior:"smooth",block:"center"})}};
 const inspect=()=>{setSubmitted(true);if(!ready){focusFirstError();return}setReviewOpen(true)};
 const requestLeave=()=>dirty?setExitOpen(true):router.push("/admin/users");
 const submit=async()=>{if(!ready||busy)return;setBusy(true);setSubmitError("");try{const created=await repo.createUser({email:form.email.trim().toLowerCase(),password:form.password,userName:form.userName.trim(),phone:normalizeAdminPhone(form.phone)||undefined,organizationPublicId:form.organizationId,roles,responderProfile:responder?{responderCode:form.responderCode.trim().toUpperCase(),dutyStatus:form.dutyStatus,coverageArea:form.coverageArea.trim()||null,isDispatchEnabled:form.dispatchEnabled}:undefined});router.push(`/admin/users/${created.publicId}?created=1`)}catch(error){const managed=error as UserManagementError;setReviewOpen(false);setSubmitError(error instanceof Error?error.message:"사용자를 등록하지 못했습니다.");setTimeout(()=>{const id=managed.code==="USER_EMAIL_DUPLICATE"?"new-user-email":managed.code==="RESPONDER_CODE_DUPLICATE"?"new-responder-code":null;if(id){document.getElementById(id)?.focus();document.getElementById(id)?.scrollIntoView({block:"center"})}},0)}finally{setBusy(false)}};
 const checks=[["name",validity.name,"이름 입력","이름을 2자 이상 입력해 주세요."],["email",validity.email,"이메일 확인","올바른 이메일과 중복 확인이 필요합니다."],["password",validity.password,"비밀번호 조건","8~64자, 영문과 숫자가 필요합니다."],["confirm",validity.confirm,"비밀번호 일치","비밀번호 확인을 완료해 주세요."],["organization",validity.organization,"소속 기관","소속 기관을 선택해 주세요."],["role",validity.role,"계정 유형","계정 유형을 선택해 주세요."],...(responder?[["responder",validity.responder,"출동 담당자 설정","담당자 코드 확인이 필요합니다."]]:[])] as [string,boolean,string,string][];
 return <main className={styles.page}>
  <header className={styles.header}><div><nav aria-label="현재 위치"><Link href="/admin/users">사용자 관리</Link><span>/</span><b>운영 사용자 등록</b></nav><h1>운영 사용자 등록</h1><p>업무에 필요한 계정과 역할, 소속 정보를 설정합니다.</p></div><button className={styles.back} type="button" onClick={requestLeave}>사용자 목록</button></header>
  <section className={styles.roleChooser} aria-labelledby="account-type-title"><header><h2 id="account-type-title">업무 역할</h2><p>담당 업무와 접근 범위를 비교한 뒤 기본 역할을 선택해 주세요.</p></header><div role="radiogroup" aria-label="업무 역할">{roleOptions.map(role=><button id={`account-type-${role.toLowerCase().replace("_","-")}`} type="button" role="radio" aria-checked={form.primaryRole===role} key={role} onClick={()=>set("primaryRole",role)}><i className={styles.roleRadio} aria-hidden="true"/><span className={styles.roleCardTitle}>{ROLE_PRESENTATIONS[role].label}</span><code>{role}</code><small>{ROLE_PRESENTATIONS[role].shortDescription}</small></button>)}</div><p><strong>{form.primaryRole?getRoleLabel(form.primaryRole):"업무 역할을 선택해 주세요."}</strong>{form.primaryRole&&<span>{ROLE_PRESENTATIONS[form.primaryRole].fullDescription}</span>}</p></section>
  <div className={styles.compactLayout}><div className={styles.accountForm}>
   <section><header><h2>계정 정보</h2><p>로그인과 관리자 식별에 사용할 기본 정보입니다.</p></header><div className={styles.fields}>
    <Field styles={styles} id="new-user-name" label="이름" required error={submitted&&!validity.name?"이름은 2자 이상 100자 이하로 입력해 주세요.":""}><input id="new-user-name" value={form.userName} maxLength={100} autoComplete="name" onChange={e=>set("userName",e.target.value)}/></Field>
    <Field styles={styles} id="new-user-email" label="이메일" required error={emailState==="duplicate"?"이미 등록된 이메일입니다.":submitted&&!validity.email&&emailState!=="checking"?"올바른 이메일을 입력하고 중복 확인을 완료해 주세요.":""} message={emailState==="checking"?"중복 확인 중…":emailState==="available"?"사용할 수 있는 이메일입니다.":""}><input id="new-user-email" type="email" value={form.email} maxLength={254} autoComplete="email" onChange={e=>set("email",e.target.value.toLowerCase())}/></Field>
    <Field styles={styles} id="new-user-phone" label="전화번호" error={submitted&&!validity.phone?"전화번호 11자리를 입력해 주세요.":""}><input id="new-user-phone" inputMode="numeric" value={formatAdminPhone(form.phone)} maxLength={13} autoComplete="tel" placeholder="010-0000-0000" onChange={e=>set("phone",e.target.value)}/></Field>
   </div></section>
   <section><header><h2>로그인 및 소속</h2><p>초기 로그인 정보와 운영 소속을 설정합니다.</p></header><div className={styles.fields}>
    <Field styles={styles} id="new-user-password" label="초기 비밀번호" required><div className={styles.passwordInput}><input id="new-user-password" type={showPassword?"text":"password"} value={form.password} maxLength={64} autoComplete="new-password" onChange={e=>set("password",e.target.value)}/><button type="button" aria-pressed={showPassword} onClick={()=>setShowPassword(value=>!value)}>{showPassword?"숨김":"보기"}</button></div><div className={styles.passwordRules}><span data-ok={form.password.length>=8&&form.password.length<=64}>8~64자</span><span data-ok={/[A-Za-z]/.test(form.password)}>영문</span><span data-ok={/\d/.test(form.password)}>숫자</span></div></Field>
    <Field styles={styles} id="new-user-confirm" label="비밀번호 확인" required error={submitted&&!validity.confirm?"비밀번호가 일치하지 않습니다.":""}><div className={styles.passwordInput}><input id="new-user-confirm" type={showConfirm?"text":"password"} value={form.confirm} maxLength={64} autoComplete="new-password" onChange={e=>set("confirm",e.target.value)}/><button type="button" aria-pressed={showConfirm} onClick={()=>setShowConfirm(value=>!value)}>{showConfirm?"숨김":"보기"}</button></div></Field>
    <Field styles={styles} id="new-user-org" label="소속 기관" required error={orgError||submitted&&!validity.organization?"소속 기관을 선택해 주세요.":""}><div id="new-user-org"><OrganizationExplorer organizations={organizations} value={form.organizationId?{type:"ORGANIZATION",publicId:form.organizationId}:{type:"ALL"}} onChange={value=>set("organizationId",value.type==="ORGANIZATION"?value.publicId:"")} label="소속 선택" loading={orgLoading} error={orgError} onRetry={()=>loadOrganizations()}/></div></Field>
   </div><p className={styles.policyNote}><i aria-hidden="true">i</i><span><strong>계정 생성 상태</strong>등록이 완료되면 바로 로그인할 수 있는 활성 계정으로 생성됩니다.</span></p></section>
   <section className={styles.roleExtras}><header><h2>추가 역할</h2><p>필요한 경우 다른 운영 역할을 함께 부여할 수 있습니다.</p></header><button type="button" aria-expanded={additionalOpen} onClick={()=>setAdditionalOpen(value=>!value)}>＋ 추가 역할 선택</button>{form.additional.length>0&&<div className={styles.chips}>{form.additional.map(role=><button type="button" key={role} onClick={()=>set("additional",form.additional.filter(item=>item!==role))}>{getRoleLabel(role)} <span aria-hidden="true">×</span></button>)}</div>}{additionalOpen&&<div className={styles.additionalOptions}>{roleOptions.filter(role=>role!==form.primaryRole).map(role=><label key={role}><input type="checkbox" checked={form.additional.includes(role)} onChange={e=>set("additional",e.target.checked?[...new Set([...form.additional,role])]:form.additional.filter(item=>item!==role))}/>{getRoleLabel(role)}</label>)}</div>}
   {responder&&<div className={styles.responderSection}><header><h3>출동 담당자 추가 설정</h3><p>출동 요청 배정과 현장 업무에 필요한 정보를 설정합니다.</p></header><div className={styles.fields}><Field styles={styles} id="new-responder-code" label="출동 담당자 코드" required error={codeState==="duplicate"?"이미 사용 중인 코드입니다.":submitted&&!validity.responder&&codeState!=="checking"?"담당자 코드를 입력하고 중복 확인을 완료해 주세요.":""} message={codeState==="checking"?"중복 확인 중…":codeState==="available"?"사용할 수 있는 코드입니다.":""}><input id="new-responder-code" value={form.responderCode} maxLength={20} placeholder="RSP-001" onChange={e=>set("responderCode",e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g,""))}/></Field><Field styles={styles} id="new-duty" label="초기 근무 상태" required><select id="new-duty" value={form.dutyStatus} onChange={e=>set("dutyStatus",e.target.value as ResponderDutyStatus)}><option value="AVAILABLE">근무 가능</option><option value="OFF_DUTY">근무 외</option></select></Field><Field styles={styles} id="new-coverage" label="담당 구역"><input id="new-coverage" value={form.coverageArea} maxLength={100} onChange={e=>set("coverageArea",e.target.value)}/></Field><label className={styles.compactSwitch}><span><b>출동 배정 허용</b><small>신규 출동 배정 대상에 포함</small></span><input type="checkbox" checked={form.dispatchEnabled} onChange={e=>set("dispatchEnabled",e.target.checked)}/></label></div></div>}</section>
   {submitError&&<p className={styles.submitError} role="alert">{submitError} 입력값은 유지되었습니다. 다시 확인해 주세요.</p>}
   <footer className={styles.actions}><button type="button" onClick={requestLeave}>취소</button><button ref={reviewTrigger} type="button" className={styles.primary} aria-describedby={!ready?"submit-guidance":undefined} onClick={inspect}>등록 내용 확인</button></footer>
  </div>
  <aside className={styles.preflight} aria-labelledby="preflight-title"><header><h2 id="preflight-title">등록 전 점검</h2><p>입력한 정보와 누락된 필수 항목을 확인합니다.</p></header><div className={styles.preflightUser}><i>{form.userName.trim().slice(0,1)||"–"}</i><div><strong>{form.userName.trim()||"사용자 정보 미입력"}</strong><span>{form.email||"이메일을 입력해 주세요."}</span></div></div>{roles.length?<RoleReview roles={roles}/>:<p>역할을 선택해 주세요.</p>}<dl><div><dt>역할</dt><dd>{roles.length?<RoleBadgeGroup roles={roles} maxVisible={2}/>:"미선택"}</dd></div><div><dt>소속</dt><dd>{organization?.name||"미선택"}</dd></div><div><dt>생성 상태</dt><dd className={styles.activeText}>활성</dd></div>{responder&&<div><dt>출동 설정</dt><dd>{form.responderCode||"담당자 코드 미입력"} · {form.dutyStatus}</dd></div>}</dl><h3>입력 점검</h3><ul id="submit-guidance">{checks.map(([key,ok,label,guide])=><li key={key} data-ok={ok}><b aria-hidden="true">{ok?"✓":"!"}</b><span>{ok?label:guide}</span></li>)}</ul><p className={styles.submitState} data-ready={ready}>{ready?"필수 입력이 완료되었습니다.":"필수 항목을 확인해 주세요."}</p></aside>
  </div>
  {reviewOpen&&<div className={styles.dialogWrap} onMouseDown={e=>e.target===e.currentTarget&&!busy&&setReviewOpen(false)}><section ref={dialogRef} className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="review-title"><header><div><h2 id="review-title">운영 사용자를 등록하시겠습니까?</h2><p>{form.userName} · {form.email}</p></div><button type="button" disabled={busy} aria-label="최종 확인 닫기" onClick={()=>setReviewOpen(false)}>×</button></header><RoleReview roles={roles}/><Review rows={[["소속",organization?.name??""],["전화번호",formatAdminPhone(form.phone)||"입력 안 함"],...(responder?[["담당자 코드",form.responderCode],["근무 상태",form.dutyStatus],["담당 구역",form.coverageArea||"지정 없음"]]:[])]}/><p className={styles.securityNote}>등록이 완료되면 활성 계정으로 생성됩니다. 비밀번호 원문은 표시하거나 Mock 저장소에 보관하지 않습니다.</p><footer className={styles.actions}><button type="button" disabled={busy} onClick={()=>setReviewOpen(false)}>입력 내용 수정</button><button type="button" className={styles.primary} disabled={busy} onClick={()=>void submit()}>{busy?"등록 중…":"운영 사용자 등록"}</button></footer></section></div>}
  {exitOpen&&<div className={styles.dialogWrap}><section className={styles.dialog} role="alertdialog" aria-modal="true" aria-labelledby="exit-title"><h2 id="exit-title">작성 중인 내용을 나갈까요?</h2><p>입력한 등록 정보는 저장되지 않습니다.</p><footer className={styles.actions}><button onClick={()=>setExitOpen(false)}>계속 작성</button><button className={styles.danger} onClick={()=>router.push("/admin/users")}>나가기</button></footer></section></div>}
 </main>
}
function Field({styles,id,label,required,error,message,children}:{styles:Styles;id:string;label:string;required?:boolean;error?:string|false;message?:string;children:React.ReactNode}){return <div className={styles.field}><label htmlFor={id}>{label}{required&&<b aria-label="필수"> *</b>}</label>{children}<small id={`${id}-help`} className={error?styles.error:message?styles.success:undefined} aria-live="polite">{error||message||" "}</small></div>}
function Review({rows}:{rows:string[][]}){return <dl className="review-list">{rows.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>}
