"use client";
import {createPortal} from "react-dom";
import {useEffect,useId,useLayoutEffect,useMemo,useRef,useState} from "react";
import type {CSSProperties} from "react";
import type {OrganizationOption,OrganizationType} from "./userManagementTypes";
import styles from "./OrganizationExplorer.module.css";

export type OrganizationExplorerValue={type:"ALL"}|{type:"UNASSIGNED"}|{type:"ORGANIZATION";publicId:string};
const labels:Record<OrganizationType,string>={CONTROL_CENTER:"관제센터",OPERATIONS_HEADQUARTERS:"운영본부",FIELD_SUPPORT:"출동 지원 조직"};
export function normalizeOrganizationSearch(value:string){return value.trim().replace(/\s+/g," ").toLocaleLowerCase("ko-KR")}
export function filterOrganizations(items:OrganizationOption[],keyword:string){const query=normalizeOrganizationSearch(keyword);return items.filter(item=>item.isActive!==false&&(!query||[item.name,item.code??"",item.type?labels[item.type]:"",item.parentName??""].some(value=>normalizeOrganizationSearch(value).includes(query))))}

export function OrganizationExplorer({organizations,value,onChange,allowAll=false,allowUnassigned=false,label="소속",placeholder="전체",loading=false,error,onRetry,triggerId}:{organizations:OrganizationOption[];value:OrganizationExplorerValue;onChange:(value:OrganizationExplorerValue)=>void;allowAll?:boolean;allowUnassigned?:boolean;label?:string;placeholder?:string;loading?:boolean;error?:string;onRetry?:()=>void;triggerId?:string}){
 const id=useId();const[open,setOpen]=useState(false),[keyword,setKeyword]=useState(""),[active,setActive]=useState(0),[position,setPosition]=useState<CSSProperties>({});const root=useRef<HTMLDivElement>(null),popover=useRef<HTMLElement>(null),search=useRef<HTMLInputElement>(null);
 const selected=value.type==="ORGANIZATION"?organizations.find(item=>item.publicId===value.publicId):null;
 const filtered=useMemo(()=>filterOrganizations(organizations,keyword),[organizations,keyword]);
 const groups=useMemo(()=>Object.entries(labels).map(([type,name])=>({type:type as OrganizationType,name,items:filtered.filter(item=>item.type===type)})).filter(group=>group.items.length),[filtered]);
 const options=useMemo(()=>[...(allowAll?["ALL"]:[]),...(allowUnassigned?["UNASSIGNED"]:[]),...filtered.map(item=>item.publicId)],[allowAll,allowUnassigned,filtered]);
 useEffect(()=>{if(open){setActive(Math.max(0,options.indexOf(value.type==="ORGANIZATION"?value.publicId:value.type)));requestAnimationFrame(()=>search.current?.focus())}},[open,options,value]);
 useEffect(()=>{if(!open)return;window.dispatchEvent(new CustomEvent("roadbogo:admin-filter-open",{detail:id}));const close=(event:Event)=>{if((event as CustomEvent).detail!==id)setOpen(false)};window.addEventListener("roadbogo:admin-filter-open",close);return()=>window.removeEventListener("roadbogo:admin-filter-open",close)},[id,open]);
 useLayoutEffect(()=>{if(!open)return;const place=()=>{const rect=root.current?.getBoundingClientRect();if(!rect)return;const width=Math.min(Math.max(rect.width,360),window.innerWidth-24),left=Math.min(Math.max(12,rect.left),window.innerWidth-width-12),openUp=window.innerHeight-rect.bottom<360;setPosition({position:"fixed",width,left,top:openUp?undefined:rect.bottom+6,bottom:openUp?window.innerHeight-rect.top+6:undefined})};place();window.addEventListener("resize",place);window.addEventListener("scroll",place,true);return()=>{window.removeEventListener("resize",place);window.removeEventListener("scroll",place,true)}},[open]);
 useEffect(()=>{const outside=(event:MouseEvent)=>{const node=event.target as Node;if(!root.current?.contains(node)&&!popover.current?.contains(node))setOpen(false)};document.addEventListener("mousedown",outside);return()=>document.removeEventListener("mousedown",outside)},[]);
 const focusTrigger=()=>requestAnimationFrame(()=>root.current?.querySelector<HTMLButtonElement>(`.${styles.trigger}`)?.focus());
 const choose=(next:OrganizationExplorerValue)=>{onChange(next);setKeyword("");setOpen(false);focusTrigger()};
 const key=(event:React.KeyboardEvent)=>{if(!open&&(event.key==="ArrowDown"||event.key==="Enter"||event.key===" ")){event.preventDefault();setOpen(true);return}if(event.key==="Escape"){event.preventDefault();setOpen(false);focusTrigger();return}if(event.key==="ArrowDown"||event.key==="ArrowUp"){event.preventDefault();setActive(index=>Math.max(0,Math.min(options.length-1,index+(event.key==="ArrowDown"?1:-1))))}if(event.key==="Home"||event.key==="End"){event.preventDefault();setActive(event.key==="Home"?0:options.length-1)}if(event.key==="Enter"&&options[active]){event.preventDefault();const id=options[active];choose(id==="ALL"?{type:"ALL"}:id==="UNASSIGNED"?{type:"UNASSIGNED"}:{type:"ORGANIZATION",publicId:id})}};
 const selectedLabel=value.type==="ALL"?placeholder:value.type==="UNASSIGNED"?"소속 미지정":selected?.name??"선택 복원 중",triggerLabel=`${label}, 현재 ${selectedLabel}`;
 return <div className={styles.root} ref={root}><div className={styles.triggerWrap}><button id={triggerId} type="button" className={styles.trigger} data-applied={value.type!=="ALL"} aria-haspopup="listbox" aria-expanded={open} aria-controls="organization-options" aria-label={triggerLabel} title={selectedLabel} onClick={()=>setOpen(value=>!value)}><span className={styles.triggerIcon} aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 21V6l8-3 8 3v15M8 9h1m-1 4h1m-1 4h1m6-8h1m-1 4h1m-1 4h1M2 21h20"/></svg></span><span className={styles.triggerText}><small>{label}</small><strong>{selectedLabel}</strong></span><i className={styles.selectorIcon} aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m8 9 4-4 4 4M16 15l-4 4-4-4"/></svg></i></button></div>{open&&typeof document!=="undefined"&&createPortal(<><button className={styles.backdrop} tabIndex={-1} aria-label="소속 선택 닫기" onClick={()=>{setOpen(false);focusTrigger()}}/><section ref={popover} className={styles.popover} style={position} onKeyDown={key}><header><strong className={styles.mobileTitle}>소속 선택</strong><label><span className={styles.searchIcon} aria-hidden="true">⌕</span><span className={styles.srOnly}>소속명·조직 코드 검색</span><input ref={search} role="combobox" aria-controls="organization-options" aria-expanded="true" aria-activedescendant={options[active]?`org-${options[active]}`:undefined} value={keyword} onChange={event=>{setKeyword(event.target.value);setActive(0)}} placeholder="소속 기관 검색"/>{keyword&&<button type="button" aria-label="소속 검색어 지우기" onClick={()=>{setKeyword("");setActive(0)}}>×</button>}</label></header><div id="organization-options" role="listbox" aria-label="등록된 조직">{loading?<div className={styles.state}>소속 기관을 불러오는 중입니다.</div>:error?<div className={styles.state} role="alert"><p>{error}</p>{onRetry&&<button onClick={onRetry}>다시 시도</button>}</div>:<>{(allowAll||allowUnassigned)&&<section className={styles.quickOptions} aria-label="빠른 선택">{allowAll&&<Option id="ALL" label="전체 소속" selected={value.type==="ALL"} active={options[active]==="ALL"} onClick={()=>choose({type:"ALL"})}/>} {allowUnassigned&&<Option id="UNASSIGNED" label="소속 미지정" selected={value.type==="UNASSIGNED"} active={options[active]==="UNASSIGNED"} onClick={()=>choose({type:"UNASSIGNED"})}/>}</section>} {groups.map(group=><section className={styles.group} key={group.type} aria-label={group.name}><h3>{group.name}</h3>{group.items.map(item=><Option key={item.publicId} id={item.publicId} label={item.name} meta={[item.code,item.parentName].filter(Boolean).join(" · ")} selected={value.type==="ORGANIZATION"&&value.publicId===item.publicId} active={options[active]===item.publicId} onClick={()=>choose({type:"ORGANIZATION",publicId:item.publicId})}/>)}</section>)}{!filtered.length&&<div className={styles.state}><strong>일치하는 소속 기관이 없습니다.</strong><p>다른 기관명이나 기관 코드를 입력해 주세요.</p></div>}</>}</div></section></>,document.body)}</div>
}
function Option({id,label,meta,selected,active,onClick}:{id:string;label:string;meta?:string;selected:boolean;active:boolean;onClick:()=>void}){return <button id={`org-${id}`} type="button" role="option" aria-selected={selected} data-active={active} className={styles.option} title={label} onClick={onClick}><i aria-hidden="true">{selected?"✓":""}</i><span><strong>{label}</strong>{meta&&<small>{meta}</small>}</span></button>}
