"use client";
import {useEffect,useRef,useState} from "react";
import type {CSSProperties} from "react";
import type {UserRole} from "@/types/auth";
import {ROLE_ORDER,ROLE_PRESENTATIONS,ROLE_SYMBOLS,getUnifiedPermissionCodes,getUnifiedPermissionLabels,sortRoles} from "./rolePresentationConfig";
import styles from "./RolePresentation.module.css";

const vars=(role:UserRole)=>({"--role-bg":ROLE_PRESENTATIONS[role].color.background,"--role-border":ROLE_PRESENTATIONS[role].color.border,"--role-fg":ROLE_PRESENTATIONS[role].color.foreground,"--role-accent":ROLE_PRESENTATIONS[role].color.accent} as CSSProperties);
export function RoleSymbol({role}:{role:UserRole}){return <i className={styles.roleSymbol} style={{color:ROLE_PRESENTATIONS[role].color.accent}} aria-hidden="true">{ROLE_SYMBOLS[role]}</i>}
export function RoleBadge({role,showTooltip=false}:{role:UserRole;showTooltip?:boolean}){const meta=ROLE_PRESENTATIONS[role];return <span className={styles.badge} style={vars(role)} tabIndex={showTooltip?0:undefined}><RoleSymbol role={role}/>{meta.label}{showTooltip&&<span role="tooltip" className={styles.tooltip}><strong>{meta.label}</strong><span>{meta.shortDescription}</span></span>}</span>}
export function RoleBadgeGroup({roles,maxVisible=2,showTooltips=true}:{roles:UserRole[];maxVisible?:number;showTooltips?:boolean}){const sorted=sortRoles(roles),visible=sorted.slice(0,maxVisible),hidden=sorted.slice(maxVisible);return <span className={styles.group}>{visible.map(role=><RoleBadge role={role} showTooltip={showTooltips} key={role}/>)}{hidden.length>0&&<span role={showTooltips?"button":undefined} tabIndex={showTooltips?0:undefined} className={styles.more} aria-label={`추가 역할 ${hidden.length}개 보기`}>+{hidden.length}{showTooltips&&<span role="tooltip" className={styles.tooltip}><strong>추가 역할</strong>{hidden.map(role=><span key={role}>{ROLE_PRESENTATIONS[role].label} · {ROLE_PRESENTATIONS[role].shortDescription}</span>)}</span>}</span>}</span>}
export function RoleDescription({roles,showCodes=false}:{roles:UserRole[];showCodes?:boolean}){const sorted=sortRoles(roles),primary=sorted[0];if(!primary)return <p>지정된 역할이 없습니다.</p>;const meta=ROLE_PRESENTATIONS[primary];return <section className={styles.description}><div className={styles.descriptionHeader}><RoleBadgeGroup roles={sorted}/></div><p><strong>{meta.label}</strong> · {meta.fullDescription}</p>{sorted.length>1&&<details><summary>다른 역할 설명 보기</summary>{sorted.slice(1).map(role=><p key={role}><b>{ROLE_PRESENTATIONS[role].label}</b> · {ROLE_PRESENTATIONS[role].shortDescription}</p>)}</details>}<h4>주요 접근 범위</h4><ul className={styles.access}>{getUnifiedPermissionLabels(sorted).map(label=><li key={label}>{label}</li>)}</ul>{showCodes&&<details><summary>Permission 코드 보기</summary>{getUnifiedPermissionCodes(sorted).map(code=><code key={code}>{code}</code>)}</details>}</section>}
export function RoleLegendPopover(){return <span className={styles.legend}><button type="button" className={styles.legendButton} aria-label="역할 안내 열기">i</button><span className={styles.legendPanel}><h3>역할 안내</h3>{ROLE_ORDER.map(role=>{const meta=ROLE_PRESENTATIONS[role];return <div key={role}><RoleSymbol role={role}/><span><b>{meta.label}</b><p>{meta.shortDescription}</p></span></div>})}</span></span>}
export function RoleFilter({value,onChange}:{value:UserRole|null;onChange:(role:UserRole|null)=>void}){const[open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null);useEffect(()=>{if(!open)return;const close=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[open]);return <div className={styles.filter} ref={root}><button type="button" className={styles.filterTrigger} aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span className={styles.triggerValue}>{value?<RoleBadge role={value}/>:<><i className={styles.neutralMark} aria-hidden="true"/><span>역할 전체</span></>}</span><span className={styles.chevron} aria-hidden="true">⌄</span></button>{open&&<div className={styles.filterMenu} role="listbox" aria-label="역할 필터">{[null,...ROLE_ORDER].map(role=>{const meta=role?ROLE_PRESENTATIONS[role]:null;return <button type="button" role="option" aria-selected={value===role} key={role??"ALL"} onClick={()=>{onChange(role);setOpen(false)}}>{role?<RoleSymbol role={role}/>:<i/>}<span className={styles.optionText}><b>{meta?.label??"역할 전체"}</b><small>{meta?.shortDescription??"모든 역할의 사용자를 표시합니다."}</small></span><span className={styles.check}>{value===role?"✓":""}</span></button>})}</div>}</div>}
export function RoleReview({roles}:{roles:UserRole[]}){const primary=sortRoles(roles)[0];return <div className={styles.reviewRoles}><RoleBadgeGroup roles={roles}/>{primary&&<p>{ROLE_PRESENTATIONS[primary].shortDescription}</p>}<ul className={styles.access}>{getUnifiedPermissionLabels(roles).slice(0,5).map(label=><li key={label}>{label}</li>)}</ul></div>}
