import type {UserRole} from "@/types/auth";

export type RolePresentation={code:UserRole;label:string;shortDescription:string;fullDescription:string;color:{background:string;border:string;foreground:string;accent:string};permissionLabels:string[];permissionCodes:string[]};
export const ROLE_ORDER:UserRole[]=["SYSTEM_ADMIN","CONTROL_MANAGER","CONTROLLER","RESPONDER","GENERAL_USER"];
export const ROLE_SYMBOLS:Record<UserRole,string>={SYSTEM_ADMIN:"◆",CONTROL_MANAGER:"◎",CONTROLLER:"▣",RESPONDER:"◉",GENERAL_USER:"○"};
export const ROLE_PRESENTATIONS:Record<UserRole,RolePresentation>={
 SYSTEM_ADMIN:{code:"SYSTEM_ADMIN",label:"시스템 관리자",shortDescription:"서비스 전체 운영과 사용자·권한 관리",fullDescription:"사용자·권한과 시스템 운영 환경을 관리하는 최고 관리 역할입니다.",color:{background:"#F0EEFF",border:"#D8D3FF",foreground:"#6C63E6",accent:"#6C63E6"},permissionLabels:["사용자 조회 및 등록","사용자 정보 수정","역할 부여 및 해제","계정 비활성화","CCTV 기준정보 조회","감사 로그 조회","시스템 운영 상태 확인"],permissionCodes:["USER.READ_ALL","USER.WRITE","ROLE.MANAGE","CCTV.READ","AUDIT.READ","SYSTEM.READ"]},
 CONTROL_MANAGER:{code:"CONTROL_MANAGER",label:"관제센터 책임자",shortDescription:"관제센터 사건과 담당 인력 감독",fullDescription:"전체 사건과 관제 담당자의 처리 현황을 확인하고 관제 업무 흐름을 감독합니다.",color:{background:"#EAF0FF",border:"#CCD9FF",foreground:"#3C6FE8",accent:"#3C6FE8"},permissionLabels:["전체 CCTV 조회","전체 사건 조회","사건 확인 및 선점","사건 판정","출동 담당자 배정","관제 업무 현황 확인","사건 최종 종료"],permissionCodes:["CCTV.READ","INCIDENT.READ_ALL","INCIDENT.CLAIM","INCIDENT.JUDGE","DISPATCH.ASSIGN","INCIDENT.CLOSE"]},
 CONTROLLER:{code:"CONTROLLER",label:"관제 담당자",shortDescription:"사건 확인·위험 판단과 출동 요청",fullDescription:"AI가 생성한 위험 사건을 확인하고 실제 위험 여부를 판단해 필요한 경우 출동을 요청합니다.",color:{background:"#E7F5F4",border:"#C4E5E2",foreground:"#26999E",accent:"#26999E"},permissionLabels:["CCTV 조회","사건 목록 및 상세 조회","사건 확인 및 선점","실제 위험·오탐 판정","관제 메모","출동 담당자 배정","사건 최종 종료"],permissionCodes:["CCTV.READ","INCIDENT.READ_ALL","INCIDENT.CLAIM","INCIDENT.JUDGE","INCIDENT.MEMO","DISPATCH.ASSIGN","INCIDENT.CLOSE"]},
 RESPONDER:{code:"RESPONDER",label:"출동 담당자",shortDescription:"출동 요청 수행과 현장 조치",fullDescription:"배정된 출동 요청을 확인하고 이동·도착·조치 상태와 현장 처리 결과를 등록합니다.",color:{background:"#FFF4DF",border:"#F1D7A6",foreground:"#B7791F",accent:"#D89A3D"},permissionLabels:["본인 출동 요청 조회","출동 요청 수락 및 거절","출발·이동·도착 상태 등록","현장 조치 시작 및 완료","조치 결과 등록","조치 전후 사진 등록"],permissionCodes:["DISPATCH.READ_OWN","DISPATCH.RESPOND","DISPATCH.STATUS_WRITE","DISPATCH.RESULT_WRITE","DISPATCH.PHOTO_WRITE"]},
 GENERAL_USER:{code:"GENERAL_USER",label:"일반 사용자",shortDescription:"일반 서비스와 본인 계정 이용",fullDescription:"일반 서비스를 이용하고 본인의 계정 정보와 알림을 관리합니다.",color:{background:"#F1F5F9",border:"#D9E1EA",foreground:"#64748B",accent:"#64748B"},permissionLabels:["일반 홈 이용","본인 정보 조회","본인 이름 및 연락처 수정","알림 조회","비밀번호 재설정","허용된 경우 본인 회원탈퇴"],permissionCodes:["PROFILE.READ","PROFILE.WRITE","NOTIFICATION.READ","PASSWORD.RESET","ACCOUNT.WITHDRAW"]},
};
export const sortRoles=(roles:UserRole[])=>[...roles].sort((a,b)=>ROLE_ORDER.indexOf(a)-ROLE_ORDER.indexOf(b));
export const getUnifiedPermissionLabels=(roles:UserRole[])=>[...new Set(sortRoles(roles).flatMap(role=>ROLE_PRESENTATIONS[role].permissionLabels))];
export const getUnifiedPermissionCodes=(roles:UserRole[])=>[...new Set(sortRoles(roles).flatMap(role=>ROLE_PRESENTATIONS[role].permissionCodes))];
