"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { ChangeEvent, FormEvent, useEffect, useRef, useState } from "react";
import { AuthIntentTabs } from "@/components/auth/AuthIntentTabs";
import { AuthShell } from "@/components/auth/AuthShell";
import { OrganizationSelector } from "@/components/auth/OrganizationSelector";
import { SignupPasswordField } from "@/components/auth/SignupPasswordField";
import { SignupRiskVisual } from "@/components/auth/SignupRiskVisual";
import { organizations, organizationTypeOptions, type OrganizationSelection } from "@/data/organizations";
import { ApiError } from "@/lib/apiClient";
import { authApi } from "@/lib/authApi";
import { operationAccessApi, OperationAccessApiUnavailableError, type OperationRequestRole } from "@/lib/operationAccessApi";
import type { LoginIntent } from "@/types/auth";
import styles from "./signup.module.css";

type SignupStep="form"|"review"|"complete";
type FormFields={name:string;email:string;phone:string;password:string;passwordConfirm:string;requestedRole:OperationRequestRole|"";reason:string;termsAgreed:boolean;privacyAgreed:boolean};
const stepsGeneral=["가입 정보 입력","입력 정보 확인","가입 완료"];
const stepsOperations=["신청 정보 입력","신청 내용 확인","신청 접수 완료"];
const roleOptions:[OperationRequestRole,string][]=[["CONTROL_MANAGER","관제센터 책임자"],["CONTROLLER","관제 담당자"],["RESPONDER","출동 담당자"]];
const initialOrganization:OrganizationSelection={mode:"registered",organizationId:null,organizationName:""};
const initialForm:FormFields={name:"",email:"",phone:"",password:"",passwordConfirm:"",requestedRole:"",reason:"",termsAgreed:false,privacyAgreed:false};
const stepIndex:Record<SignupStep,number>={form:0,review:1,complete:2};
const passwordChecks=(value:string)=>({length:value.length>=8&&value.length<=64,letter:/[A-Za-z]/.test(value),number:/\d/.test(value)});

export default function SignupPage(){
 const router=useRouter();const formRef=useRef<HTMLFormElement>(null);const[intent,setIntent]=useState<LoginIntent>("general");const[step,setStep]=useState<SignupStep>("form");const[submitting,setSubmitting]=useState(false);const[form,setForm]=useState<FormFields>(initialForm);const[organization,setOrganization]=useState<OrganizationSelection>(initialOrganization);const[organizationError,setOrganizationError]=useState("");const[fieldErrors,setFieldErrors]=useState<Record<string,string>>({});const[submitError,setSubmitError]=useState("");const[traceId,setTraceId]=useState<string|null>(null);
 useEffect(()=>{const value=new URLSearchParams(window.location.search).get("intent");setIntent(value==="operation"||value==="operations"?"operations":"general")},[]);
 const selectIntent=(next:LoginIntent)=>{setIntent(next);setStep("form");setOrganizationError("");setFieldErrors({});setSubmitError("");const params=new URLSearchParams(window.location.search);params.set("intent",next==="operations"?"operation":"general");router.replace(`/signup?${params}`,{scroll:false})};
 const update=(field:keyof FormFields)=>(event:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>{const target=event.target;setForm(current=>({...current,[field]:target instanceof HTMLInputElement&&target.type==="checkbox"?target.checked:target.value}));setFieldErrors(current=>({...current,[field]:""}))};
 const isOperations=intent==="operations";const checks=passwordChecks(form.password);const passwordValid=checks.length&&checks.letter&&checks.number;const confirmationValid=form.passwordConfirm.length>0&&form.password===form.passwordConfirm;const generalReady=true;const operationReady=true;
 const organizationIsValid=()=>{if(!isOperations&&organization.mode==="registered"&&!organization.organizationId){setOrganizationError("");return true}if(organization.mode==="registered"){const registered=organizations.find(item=>item.id===organization.organizationId);if(!registered||registered.name!==organization.organizationName){setOrganizationError("목록에서 소속 기관을 선택해주세요.");return false}}else if(organization.organizationName.trim().length<2||!organization.organizationType||!organization.organizationRegion){setOrganizationError("기관 정식 명칭, 기관 유형, 지역을 모두 확인해주세요.");return false}setOrganizationError("");return true};
 const review=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const element=formRef.current;if(!element?.checkValidity()){element?.reportValidity();element?.querySelector<HTMLElement>(":invalid")?.focus();return}if(!organizationIsValid())return;const errors:Record<string,string>={};if(!isOperations){if(!passwordValid)errors.password="비밀번호 조건을 모두 충족해주세요.";if(!confirmationValid)errors.passwordConfirm=form.passwordConfirm?"비밀번호가 일치하지 않습니다.":"새 비밀번호를 다시 입력해주세요.";if(!form.termsAgreed)errors.termsAgreed="서비스 이용약관에 동의해주세요."}if(!form.privacyAgreed)errors.privacyAgreed="개인정보 수집·이용에 동의해주세요.";setFieldErrors(errors);if(Object.keys(errors).length)return;setSubmitError("");setStep("review")};
 const submit=async()=>{if(submitting)return;setSubmitting(true);setSubmitError("");setTraceId(null);try{if(isOperations){if(!form.requestedRole)throw new Error("신청 역할을 선택해주세요.");await operationAccessApi.submit({applicantName:form.name.trim(),organizationName:organization.organizationName.trim(),email:form.email.trim(),phone:form.phone.trim(),requestedRole:form.requestedRole,reason:form.reason.trim(),privacyAgreed:true})}else{await authApi.register({email:form.email.trim(),user_name:form.name.trim(),password:form.password,password_confirmation:form.passwordConfirm})}setForm(current=>({...current,password:"",passwordConfirm:""}));setStep("complete")}catch(error){if(error instanceof ApiError){setTraceId(error.traceId);if(error.code==="AUTH_EMAIL_ALREADY_EXISTS"){setFieldErrors(current=>({...current,email:"이미 가입된 이메일입니다."}));setSubmitError("이미 사용 중인 이메일입니다. 다른 이메일을 입력해주세요.")}else setSubmitError(error.httpStatus===0?"서버에 연결할 수 없습니다. 잠시 후 다시 시도해주세요.":"요청을 처리하지 못했습니다. 입력 정보를 확인하고 다시 시도해주세요.")}else if(error instanceof OperationAccessApiUnavailableError)setSubmitError("운영 계정 신청 API가 아직 준비되지 않았습니다. 작성한 정보는 유지되며 서버에는 전송되지 않았습니다.");else setSubmitError(error instanceof Error?error.message:"요청을 처리하지 못했습니다.")}finally{setSubmitting(false)}};
 const progress=isOperations?stepsOperations:stepsGeneral;const roleLabel=roleOptions.find(([value])=>value===form.requestedRole)?.[1];const organizationType=organizationTypeOptions.find(item=>item.value===organization.organizationType)?.label;
 return <AuthShell pageClassName={styles.page} panelClassName={styles.panel} panelLabel={isOperations?"운영 계정 신청 영역":"일반 회원가입 영역"} visual={<SignupRiskVisual/>}><div className={`${styles.requestPanel} ${step==="complete"?styles.successPanel:""}`}><AuthIntentTabs intent={intent} onChange={selectIntent}/><div key={`${intent}-${step}`} className={styles.panelContent}>
 {step!=="complete"?<><header className={styles.heading}><p>{isOperations?"OPERATIONS ACCESS REQUEST":"GENERAL SIGN UP"}</p><h2>{step==="review"?isOperations?"신청 내용을 확인해주세요":"가입 정보를 확인해주세요":isOperations?"운영 시스템 계정을 신청하세요":"도로보GO를 시작해볼까요?"}</h2><span>{step==="review"?"입력한 정보가 정확한지 확인한 후 최종 요청을 보내주세요.":isOperations?<>소속과 담당 업무를 확인한 후<br/>관리자가 계정 발급 절차를 안내해드립니다.</>:<>안전한 도로 이용을 위한 계정을 만들어주세요.<br/>가입 후 도로보GO의 일반 서비스를 이용할 수 있습니다.</>}</span></header><ol className={styles.progress} aria-label={isOperations?"운영 계정 신청 단계":"회원가입 단계"}>{progress.map((label,index)=><li key={label} className={index===stepIndex[step]?styles.progressCurrent:index<stepIndex[step]?styles.progressDone:""} aria-current={index===stepIndex[step]?"step":undefined}><b>{index<stepIndex[step]?"✓":index+1}</b><span>{label}</span></li>)}</ol>
 {step==="form"?<form ref={formRef} className={styles.form} onSubmit={review}><fieldset disabled={submitting} className={styles.signupFieldset}><div className={isOperations?styles.fieldGrid:styles.generalFields}><div className={styles.field}><label htmlFor="signup-name">{isOperations?"담당자 이름":"이름"}</label><input id="signup-name" value={form.name} onChange={update("name")} minLength={2} maxLength={100} autoComplete="name" required/></div><div className={styles.field}><label htmlFor="signup-phone">연락처</label><input id="signup-phone" value={form.phone} onChange={update("phone")} type="tel" inputMode="tel" autoComplete="tel" required/></div></div><div className={styles.field}><label htmlFor="signup-email">{isOperations?"업무 이메일":"이메일"}</label><input id="signup-email" value={form.email} onChange={update("email")} type="email" inputMode="email" autoComplete="email" aria-invalid={Boolean(fieldErrors.email)} aria-describedby="signup-email-error" required/><p id="signup-email-error" className={styles.fieldError} aria-live="polite">{fieldErrors.email??" "}</p></div><OrganizationSelector value={organization} onChange={setOrganization} email={form.email} error={organizationError} onClearError={()=>setOrganizationError("")} required={isOperations}/>
 {isOperations?<><div className={styles.field}><label htmlFor="requested-role">신청 역할</label><select id="requested-role" value={form.requestedRole} onChange={update("requestedRole")} required><option value="">신청 역할 선택</option>{roleOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><div className={styles.field}><label htmlFor="request-reason">신청 사유</label><textarea id="request-reason" value={form.reason} onChange={update("reason")} minLength={10} maxLength={500} rows={4} required/></div></>:<><SignupPasswordField id="signup-password" label="비밀번호" value={form.password} onChange={value=>setForm(current=>({...current,password:value}))} error={fieldErrors.password} hint="8자 이상, 영문과 숫자를 포함해주세요." disabled={submitting}/><ul className={styles.passwordRules} aria-label="비밀번호 조건"><li className={checks.length?styles.isValid:""}>8자 이상</li><li className={checks.letter?styles.isValid:""}>영문 포함</li><li className={checks.number?styles.isValid:""}>숫자 포함</li></ul><SignupPasswordField id="signup-password-confirm" label="비밀번호 확인" value={form.passwordConfirm} onChange={value=>setForm(current=>({...current,passwordConfirm:value}))} error={fieldErrors.passwordConfirm} hint={!form.passwordConfirm?"새 비밀번호를 다시 입력해주세요.":confirmationValid?"비밀번호가 일치합니다.":"비밀번호가 일치하지 않습니다."} disabled={submitting}/><label className={styles.agreement}><input type="checkbox" checked={form.termsAgreed} onChange={update("termsAgreed")}/><span>서비스 이용약관 동의 <b>필수</b></span></label>{fieldErrors.termsAgreed&&<p className={styles.fieldError}>{fieldErrors.termsAgreed}</p>}</>}
 <label className={styles.agreement}><input type="checkbox" checked={form.privacyAgreed} onChange={update("privacyAgreed")}/><span>개인정보 수집·이용 동의 <b>필수</b></span></label>{fieldErrors.privacyAgreed&&<p className={styles.fieldError}>{fieldErrors.privacyAgreed}</p>}</fieldset><button className={styles.submit} type="submit" disabled={isOperations?!operationReady:!generalReady}>{isOperations?"신청 내용 확인":"가입 정보 확인"}</button></form>:<section className={styles.review}><dl><div><dt>{isOperations?"담당자 이름":"이름"}</dt><dd>{form.name}</dd></div><div><dt>{isOperations?"업무 이메일":"이메일"}</dt><dd>{form.email}</dd></div><div><dt>연락처</dt><dd>{form.phone}</dd></div><div><dt>소속 기관</dt><dd>{organization.organizationName||"입력하지 않음"}</dd></div>{isOperations?<><div><dt>신청 역할</dt><dd>{roleLabel}</dd></div><div><dt>신청 사유</dt><dd>{form.reason}</dd></div></>:<div><dt>약관 동의</dt><dd>서비스 이용약관 · 개인정보 수집·이용 동의 완료</dd></div>}{organization.mode==="new_request"&&<><div><dt>기관 유형</dt><dd>{organizationType}</dd></div><div><dt>지역</dt><dd>{organization.organizationRegion}</dd></div></>}</dl><p className={styles.submitError} role="alert" aria-live="polite">{submitError}</p>{traceId&&<small className={styles.traceId}>확인 코드: {traceId}</small>}<div className={styles.reviewActions}><button type="button" disabled={submitting} onClick={()=>setStep("form")}>이전</button><button type="button" disabled={submitting} aria-busy={submitting} onClick={submit}>{submitting?"처리 중…":isOperations?"운영 계정 신청":"회원가입 완료"}</button></div></section>}<div className={styles.supportLinks}><p>이미 계정이 있으신가요? <Link href={`/login?intent=${isOperations?"operations":"general"}`}>로그인</Link></p><Link className={styles.homeLink} href="/"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 11 9-7 9 7"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></svg>메인으로 돌아가기</Link></div></>:<section className={styles.success} role="status" aria-live="polite"><div className={styles.successIcon}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 4.5 6v5.2c0 4.7 3.2 8.1 7.5 9.8 4.3-1.7 7.5-5.1 7.5-9.8V6L12 3Z"/><path d="m8.5 12 2.2 2.2 4.8-4.9"/></svg></div><p>{isOperations?"REQUEST RECEIVED":"REGISTRATION COMPLETE"}</p><h2>{isOperations?"운영 계정 신청이 접수되었습니다":"가입이 완료되었습니다"}</h2><span>{isOperations?<>관리자가 소속과 신청 역할을 검토한 후<br/>입력하신 업무 이메일로 안내해드립니다.</>:"등록한 이메일과 비밀번호로 로그인해주세요."}</span>{isOperations&&<dl className={styles.completionSummary}><div><dt>신청 이메일</dt><dd>{form.email}</dd></div><div><dt>신청 기관</dt><dd>{organization.organizationName}</dd></div><div><dt>신청 역할</dt><dd>{roleLabel}</dd></div><div><dt>현재 상태</dt><dd>관리자 검토 대기</dd></div></dl>}<div className={styles.successActions}><Link href={isOperations?"/login?intent=operations":"/login?registered=true"}>{isOperations?"로그인 화면으로 이동":"로그인하기"}</Link><Link href="/">메인으로 돌아가기</Link></div></section>}
 </div></div></AuthShell>;
}
