"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {usePathname,useRouter,useSearchParams} from "next/navigation";
import {AdminFilterSelect} from "@/features/user-management/AdminFilterSelect";
import {CctvLocationWorkspace} from "./CctvLocationWorkspace";
import {createCctvNetworkRepository} from "./mockCctvNetworkRepository";
import {compareByReviewPriority,displayStatus,getCctvPaginationItems,getCctvReviewReasons,primaryReviewReason,REVIEW_REASON_ORDER,statusLabel,type CctvDisplayStatus,type CctvReviewReasonCode} from "./cctvNetworkDomain";
import type {CctvNetworkSnapshot,ItsSyncRecord,NetworkCctv} from "./cctvNetworkTypes";
import styles from "./CctvNetworkAtlas.module.css";

const directionLabel={ASC:"상행",DESC:"하행",BOTH:"양방향",UNKNOWN:"방향 미확인"} as const;
const sourceLabel={ITS:"ITS",MANUAL:"수동 기준정보",DEMO:"시연 데이터"} as const;
const validStatuses=new Set<CctvDisplayStatus>(["normal","attention","fault","inactive"]);
const validReasons=new Set(REVIEW_REASON_ORDER.map(reason=>reason.code));
const formatKst=(value:string)=>new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));

export function CctvNetworkAtlas(){
 const repository=useMemo(()=>createCctvNetworkRepository(),[]),params=useSearchParams(),router=useRouter(),pathname=usePathname();
 const[data,setData]=useState<CctvNetworkSnapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[collapsed,setCollapsed]=useState<Set<string>>(new Set()),[drawerView,setDrawerView]=useState<"detail"|"location"|"sync">("detail");
 const listTop=useRef<HTMLElement>(null),drawer=useRef<HTMLElement>(null),rowRefs=useRef(new Map<string,HTMLButtonElement>());
 const update=useCallback((values:Record<string,string|null>)=>{const next=new URLSearchParams(params.toString());for(const[key,value]of Object.entries(values)){if(value&&!(key==="page"&&value==="1")&&!(key==="size"&&value==="10")&&!(key==="sort"&&value==="review_priority"))next.set(key,value);else next.delete(key)}router.replace(`${pathname}${next.size?`?${next}`:""}`,{scroll:false})},[params,pathname,router]);
 const load=useCallback(async()=>{const controller=new AbortController();setLoading(true);setError("");try{setData(await repository.load(controller.signal))}catch(caught){if(!(caught instanceof DOMException&&caught.name==="AbortError"))setError("CCTV 정보를 불러오지 못했습니다. 잠시 후 다시 확인해 주세요.")}finally{setLoading(false)}return()=>controller.abort()},[repository]);
 useEffect(()=>{void load()},[load]);

 const keyword=(params.get("keyword")??"").trim().toLocaleLowerCase("ko-KR"),status=validStatuses.has(params.get("status") as CctvDisplayStatus)?params.get("status") as CctvDisplayStatus|null:null;
 const reason=validReasons.has(params.get("review_reason") as CctvReviewReasonCode)?params.get("review_reason") as CctvReviewReasonCode|null:null;
 const direction=params.get("direction_code"),source=params.get("source_type"),roadId=params.get("road_public_id"),sort=params.get("sort")??"review_priority",selectedId=params.get("cctv");
 const page=Math.max(1,Number(params.get("page"))||1),size=[10,20,50].includes(Number(params.get("size")))?Number(params.get("size")):10;
 const selected=data?.cctvs.find(cctv=>cctv.publicId===selectedId)??null;
 const filtered=useMemo(()=>{if(!data)return[];const result=data.cctvs.filter(cctv=>{const road=data.roads.find(item=>item.publicId===cctv.roadPublicId),section=data.sections.find(item=>item.publicId===cctv.roadSectionPublicId),reasons=getCctvReviewReasons(cctv,data);return(!keyword||[cctv.name,cctv.code,road?.name??"",section?.name??""].some(value=>value.toLocaleLowerCase("ko-KR").includes(keyword)))&&(!status||displayStatus(cctv,data)===status)&&(!reason||reasons.some(item=>item.code===reason))&&(!direction||cctv.directionCode===direction)&&(!source||cctv.sourceType===source)&&(!roadId||cctv.roadPublicId===roadId)});return result.sort((a,b)=>sort==="name"?a.name.localeCompare(b.name,"ko"):sort==="recent"?-(a.lastSuccessfulSyncAt??"").localeCompare(b.lastSuccessfulSyncAt??""):sort==="oldest"?(a.lastSuccessfulSyncAt??"").localeCompare(b.lastSuccessfulSyncAt??""):compareByReviewPriority(a,b,data))},[data,direction,keyword,reason,roadId,sort,source,status]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/size)),safePage=Math.min(page,totalPages),pageItems=filtered.slice((safePage-1)*size,safePage*size);
 const counts=useMemo(()=>{if(!data)return null;const count=(value:CctvDisplayStatus)=>data.cctvs.filter(cctv=>displayStatus(cctv,data)===value).length;return{total:data.cctvs.length,normal:count("normal"),attention:count("attention"),fault:count("fault"),inactive:count("inactive")}},[data]);
 const reviewCounts=useMemo(()=>new Map(REVIEW_REASON_ORDER.map(item=>[item.code,data?.cctvs.filter(cctv=>getCctvReviewReasons(cctv,data).some(reasonItem=>reasonItem.code===item.code)).length??0])),[data]);
 const groups=useMemo(()=>{if(!data)return[];return data.roads.map(road=>({road,items:pageItems.filter(cctv=>cctv.roadPublicId===road.publicId)})).filter(group=>group.items.length)},[data,pageItems]);
 const hasConditions=Boolean(keyword||status||reason||direction||source||roadId||sort!=="review_priority");
 const latestSuccessful=data?.syncHistory.find(item=>item.lastSuccessfulAt)?.lastSuccessfulAt??null;

 useEffect(()=>{if(page>totalPages)update({page:String(totalPages),cctv:null})},[page,totalPages,update]);
 useEffect(()=>{if(selectedId&&!selected&&!loading)update({cctv:null})},[loading,selected,selectedId,update]);
 useEffect(()=>{if(selected){setDrawerView("detail");requestAnimationFrame(()=>drawer.current?.querySelector<HTMLButtonElement>("button")?.focus())}},[selected]);
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape"&&selected){const id=selected.publicId;update({cctv:null});requestAnimationFrame(()=>rowRefs.current.get(id)?.focus())}};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[selected,update]);

 const reset=()=>update({keyword:null,status:null,review_reason:null,direction_code:null,source_type:null,road_public_id:null,sort:null,page:null,cctv:null});
 const select=(cctv:NetworkCctv,node?:HTMLButtonElement)=>{if(node)rowRefs.current.set(cctv.publicId,node);update({cctv:cctv.publicId})};
 const close=()=>{const id=selected?.publicId;update({cctv:null});if(id)requestAnimationFrame(()=>rowRefs.current.get(id)?.focus())};
 const setReason=(value:CctvReviewReasonCode|null)=>update({review_reason:value,page:null,cctv:null});
 const changePage=(value:number)=>{update({page:String(value),cctv:null});requestAnimationFrame(()=>listTop.current?.scrollIntoView({behavior:"smooth",block:"start"}))};
 const statusItems=[["all","전체",counts?.total??0,"●"],["normal","정상",counts?.normal??0,"○"],["attention","확인 필요",counts?.attention??0,"▲"],["fault","장애",counts?.fault??0,"◆"],["inactive","비활성",counts?.inactive??0,"■"]] as const;

 return <main className={styles.page}>
  <header className={styles.heading}><div><span>CCTV OPERATIONS</span><h1>CCTV 운영 관리</h1><p>등록된 CCTV의 운영 정보와 확인 필요 항목을 관리합니다.</p></div><div><small>ITS 기준 {latestSuccessful?`${formatKst(latestSuccessful)} KST`:"정상 동기화 기록 없음"}</small><button type="button" disabled={loading} onClick={()=>void load()}>{loading?"갱신 중…":"목록 새로고침"}</button></div></header>
  <section className={styles.statusFilters} aria-label="CCTV 상태 빠른 필터">{statusItems.map(([key,label,count,shape])=><button type="button" key={key} data-status={key} aria-pressed={key==="all"?!status:status===key} onClick={()=>update({status:key==="all"||status===key?null:key,page:null,cctv:null})}><i aria-hidden="true">{shape}</i><span>{label}</span><b>{count}</b></button>)}</section>
  <section className={styles.reviewBoard}><header><div><h2>확인할 CCTV</h2><p>운영 정보와 ITS 동기화 상태를 기준으로 검토가 필요한 항목입니다.</p></div><b>{counts?.attention??0}개 확인 필요</b></header><div className={styles.reviewReasons}>{REVIEW_REASON_ORDER.filter(item=>(reviewCounts.get(item.code)??0)>0).slice(0,5).map(item=><button type="button" key={item.code} data-severity={item.severity} aria-pressed={reason===item.code} onClick={()=>setReason(reason===item.code?null:item.code)}><span>{item.label}</span><b>{reviewCounts.get(item.code)}</b><small>{item.description}</small></button>)}</div>{!loading&&counts?.attention===0&&<p className={styles.reviewEmpty}>현재 확인이 필요한 CCTV가 없습니다.</p>}</section>
  <section className={styles.toolbar} aria-label="CCTV 검색 및 필터"><input aria-label="CCTV 이름·코드·노선·구간 검색" value={params.get("keyword")??""} placeholder="CCTV 이름·코드·노선·구간 검색" onChange={event=>update({keyword:event.target.value||null,page:null,cctv:null})}/><AdminFilterSelect label="방향" value={direction??""} options={[{value:"",label:"전체"},{value:"ASC",label:"상행"},{value:"DESC",label:"하행"},{value:"BOTH",label:"양방향"},{value:"UNKNOWN",label:"미확인"}]} onChange={value=>update({direction_code:value||null,page:null,cctv:null})}/><AdminFilterSelect label="출처" value={source??""} options={[{value:"",label:"전체"},{value:"ITS",label:"ITS"},{value:"MANUAL",label:"수동 기준정보"},{value:"DEMO",label:"시연 데이터"}]} onChange={value=>update({source_type:value||null,page:null,cctv:null})}/><AdminFilterSelect label="정렬" value={sort} options={[{value:"review_priority",label:"확인 우선순"},{value:"name",label:"이름순"},{value:"recent",label:"최근 반영순"},{value:"oldest",label:"오래된 반영순"}]} onChange={value=>update({sort:value,page:null,cctv:null})}/></section>
  {hasConditions&&<section className={styles.chips} aria-label="적용 조건"><strong>적용 조건</strong>{keyword&&<button onClick={()=>update({keyword:null,page:null,cctv:null})}>검색어 ×</button>}{status&&<button onClick={()=>update({status:null,page:null,cctv:null})}>{statusLabel[status]} ×</button>}{reason&&<button onClick={()=>setReason(null)}>{REVIEW_REASON_ORDER.find(item=>item.code===reason)?.label} ×</button>}{direction&&<button onClick={()=>update({direction_code:null,page:null,cctv:null})}>{directionLabel[direction as keyof typeof directionLabel]} ×</button>}{source&&<button onClick={()=>update({source_type:null,page:null,cctv:null})}>{sourceLabel[source as keyof typeof sourceLabel]} ×</button>}<button onClick={reset}>조건 모두 해제</button></section>}
  {error&&<section className={styles.error} role="alert"><span>{error}</span><button onClick={()=>void load()}>다시 확인</button></section>}
  <section ref={listTop} className={styles.inventory} aria-busy={loading}><header><div><h2>CCTV 디렉터리</h2><p>검색 결과 {filtered.length}개 · 노선별 그룹</p></div><button type="button" onClick={()=>selected?setDrawerView("location"):undefined} disabled={!selected}>선택 CCTV 위치</button></header><div className={styles.columns} aria-hidden="true"><span>상태</span><span>CCTV</span><span>위치</span><span>방향</span><span>최근 반영</span></div>
   {loading&&!data?<div className={styles.skeleton}>{Array.from({length:7},(_,index)=><i key={index}/>)}</div>:!pageItems.length?<div className={styles.empty}><strong>{data?.cctvs.length?"조건에 맞는 CCTV가 없습니다.":"등록된 CCTV가 없습니다."}</strong><p>{data?.cctvs.length?"검색어나 필터 조건을 변경해 주세요.":"현재 MVP에서는 CCTV 등록 기능을 제공하지 않습니다."}</p>{hasConditions&&<button onClick={reset}>조건 모두 해제</button>}</div>:<div className={styles.groups}>{groups.map(group=>{const closed=collapsed.has(group.road.publicId);return <section key={group.road.publicId}><button className={styles.groupHeader} type="button" aria-expanded={!closed} onClick={()=>setCollapsed(current=>{const next=new Set(current);if(next.has(group.road.publicId))next.delete(group.road.publicId);else next.add(group.road.publicId);return next})}><span><strong>{group.road.name}</strong><small>{group.items.length}개 · 정상 {group.items.filter(item=>displayStatus(item,data)==="normal").length} · 확인 필요 {group.items.filter(item=>displayStatus(item,data)==="attention").length} · 장애 {group.items.filter(item=>displayStatus(item,data)==="fault").length}</small></span><i aria-hidden="true">{closed?"⌄":"⌃"}</i></button>{!closed&&<div role="listbox" aria-label={`${group.road.name} CCTV`}>{group.items.map(cctv=><CctvRow key={cctv.publicId} cctv={cctv} data={data} selected={selectedId===cctv.publicId} onSelect={select}/>)}</div>}</section>})}</div>}
   <Pagination page={safePage} totalPages={totalPages} size={size} total={filtered.length} onPage={changePage} onSize={value=>update({size:String(value),page:null,cctv:null})}/>
  </section>
  {selected&&data&&<><button className={styles.drawerBackdrop} aria-label="CCTV 상세 닫기" onClick={close}/><Inspector ref={drawer} cctv={selected} data={data} view={drawerView} onView={setDrawerView} onClose={close}/></>}
 </main>;
}

function CctvRow({cctv,data,selected,onSelect}:{cctv:NetworkCctv;data:CctvNetworkSnapshot|null;selected:boolean;onSelect:(cctv:NetworkCctv,node?:HTMLButtonElement)=>void}){
 if(!data)return null;
 const road=data.roads.find(item=>item.publicId===cctv.roadPublicId),section=data.sections.find(item=>item.publicId===cctv.roadSectionPublicId),state=displayStatus(cctv,data),reason=primaryReviewReason(cctv,data);
 return <button type="button" role="option" aria-selected={selected} aria-label={`${cctv.name} 정보 열기`} onClick={event=>onSelect(cctv,event.currentTarget)}><span className={styles.state} data-status={state}><i aria-hidden="true">{state==="fault"?"◆":state==="attention"?"▲":state==="inactive"?"■":"○"}</i>{statusLabel[state]}</span><span className={styles.identity}><strong title={cctv.name}>{cctv.name}</strong><small>{cctv.code} <em data-source={cctv.sourceType}>{sourceLabel[cctv.sourceType]}</em></small>{reason&&<small className={styles.reason}>{reason.description}</small>}</span><span><strong>{road?.name??"노선 미확인"}</strong><small>{section?.name??"구간 미확인"}</small></span><span>{directionLabel[cctv.directionCode]}</span><span>{cctv.lastSuccessfulSyncAt?<><strong>{formatKst(cctv.lastSuccessfulSyncAt)} KST</strong><small>정상 반영</small></>:<strong>반영 기록 없음</strong>}</span></button>;
}

function Pagination({page,totalPages,size,total,onPage,onSize}:{page:number;totalPages:number;size:number;total:number;onPage:(page:number)=>void;onSize:(size:number)=>void}){
 return <footer className={styles.pagination}><label>페이지당 <select aria-label="페이지당 CCTV 수" value={size} onChange={event=>onSize(Number(event.target.value))}><option>10</option><option>20</option><option>50</option></select></label><span>{total?(page-1)*size+1:0}–{Math.min(page*size,total)} / 총 {total}개</span><nav aria-label="CCTV 목록 페이지"><button aria-label="이전 페이지" disabled={page<=1} onClick={()=>onPage(page-1)}>‹</button>{getCctvPaginationItems(page,totalPages).map((value,index)=>value==="ellipsis"?<span key={`ellipsis-${index}`}>…</span>:<button key={value} aria-current={value===page?"page":undefined} onClick={()=>onPage(value)}>{value}</button>)}<button aria-label="다음 페이지" disabled={page>=totalPages} onClick={()=>onPage(page+1)}>›</button></nav></footer>;
}

function Inspector({cctv,data,view,onView,onClose,ref}:{cctv:NetworkCctv;data:CctvNetworkSnapshot;view:"detail"|"location"|"sync";onView:(view:"detail"|"location"|"sync")=>void;onClose:()=>void;ref:React.Ref<HTMLElement>}){
 const road=data.roads.find(item=>item.publicId===cctv.roadPublicId),section=data.sections.find(item=>item.publicId===cctv.roadSectionPublicId),state=displayStatus(cctv,data),reasons=getCctvReviewReasons(cctv,data);
 return <aside ref={ref} className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="cctv-drawer-title"><header><div><span>SELECTED CCTV</span><h2 id="cctv-drawer-title">{view==="sync"?"ITS 동기화 이력":view==="location"?"설치 위치":cctv.name}</h2><p>{cctv.code}</p></div><button type="button" aria-label="CCTV 상세 닫기" onClick={onClose}>×</button></header><nav aria-label="CCTV 상세 보기"><button aria-current={view==="detail"?"page":undefined} onClick={()=>onView("detail")}>상세 정보</button><button aria-current={view==="location"?"page":undefined} onClick={()=>onView("location")}>위치</button><button aria-current={view==="sync"?"page":undefined} onClick={()=>onView("sync")}>동기화 이력</button></nav><div className={styles.drawerBody}>{view==="location"?<Location cctv={cctv}/>:view==="sync"?<SyncHistory records={data.syncHistory}/>:<><section className={styles.selectedSummary}><div><span className={styles.state} data-status={state}>{statusLabel[state]}</span><em data-source={cctv.sourceType}>{sourceLabel[cctv.sourceType]}</em></div><strong>{road?.name??"노선 미확인"}</strong><p>{section?.name??"구간 미확인"} · {directionLabel[cctv.directionCode]}</p></section><DrawerSection title="확인 사항">{reasons.length?reasons.map(reason=><div className={styles.reviewItem} data-severity={reason.severity} key={reason.code}><strong>{reason.label}</strong><p>{reason.description}</p></div>):<p>현재 확인이 필요한 운영 정보가 없습니다.</p>}</DrawerSection><DrawerSection title="운영 정보"><dl><Row label="운영 상태" value={statusLabel[state]}/><Row label="활성 여부" value={cctv.isActive?"활성":"비활성"}/><Row label="데이터 출처" value={sourceLabel[cctv.sourceType]}/><Row label="최근 정상 반영" value={cctv.lastSuccessfulSyncAt?`${formatKst(cctv.lastSuccessfulSyncAt)} KST`:undefined}/></dl></DrawerSection><DrawerSection title="영상 정보"><dl><Row label="스트림 유형" value={cctv.streamType??undefined}/><Row label="활성 스트림" value={cctv.hasStream?"있음":"없음"}/></dl></DrawerSection></>}</div></aside>;
}
const DrawerSection=({title,children}:{title:string;children:React.ReactNode})=><section className={styles.drawerSection}><h3>{title}</h3>{children}</section>;
const Row=({label,value}:{label:string;value:string|undefined})=><div><dt>{label}</dt><dd>{value??"정보 없음"}</dd></div>;
const Location=({cctv}:{cctv:NetworkCctv})=><CctvLocationWorkspace cctv={cctv}/>;
const SyncHistory=({records}:{records:ItsSyncRecord[]})=><section className={styles.syncHistory}>{records.length?records.map(record=><article key={record.publicId}><header><strong>{record.status==="SUCCESS"?"정상 완료":record.status==="PARTIAL"?"일부 실패":"대체 데이터 사용"}</strong><time>{formatKst(record.attemptedAt)} KST</time></header><dl><Row label="요청" value={`${record.requested}건`}/><Row label="신규" value={`${record.created}건`}/><Row label="갱신" value={`${record.updated}건`}/><Row label="실패" value={`${record.failed}건`}/></dl></article>):<p>동기화 이력이 없습니다.</p>}</section>;
