"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import type {KeyboardEvent as ReactKeyboardEvent} from "react";
import {usePathname,useRouter,useSearchParams} from "next/navigation";
import {getUserPaginationItems,PaginationChevron,UserPageSizeSelect} from "@/features/user-management/UserDirectoryPagination";
import {adminAuditLogRepository} from "./mockAuditLogRepository";
import type {AuditActionGroup,AuditActorType,AuditQuery,AuditRecord,AuditResourceType,AuditResult,AuditSummary} from "./auditLogTypes";
import styles from "./auditLogWorkspace.module.css";

const results={SUCCESS:"성공",FAILURE:"실패",DENIED:"접근 거부"} as const;
const actors:Record<AuditActorType,string>={USER:"사용자",SYSTEM:"시스템",DEVICE:"단말"};
const resources:Record<AuditResourceType,string>={USER:"사용자",ROLE:"역할",INCIDENT:"사건",DISPATCH:"출동",CCTV:"CCTV",SYSTEM:"시스템"};
const actionGroups:Record<AuditActionGroup,string>={AUTH:"인증",ACCOUNT:"계정",ROLE_PERMISSION:"역할 및 권한",INCIDENT_DISPATCH:"사건 및 출동",CCTV_SYSTEM:"CCTV 및 시스템"};
const statusFilters:[AuditResult|"ALL",string][]=[["ALL","전체"],["SUCCESS","성공"],["FAILURE","실패"],["DENIED","접근 거부"]];
const emptySummary:AuditSummary={total:0,success:0,failure:0,denied:0};
const safe=<T extends string>(value:string|null,allowed:readonly T[],fallback:T)=>allowed.includes(value as T)?value as T:fallback;
const mask=(value:unknown):unknown=>Array.isArray(value)?value.map(mask):value&&typeof value==="object"?Object.fromEntries(Object.entries(value).map(([key,item])=>[/password|token|secret|authorization|cookie|key/i.test(key)?[key,"***"]:[key,mask(item)]])):value;
const fullTime=(value:string)=>new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date(value));
const dateTime=(value:string)=>{const parts=new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).formatToParts(new Date(value));const part=(type:Intl.DateTimeFormatPartTypes)=>parts.find(item=>item.type===type)?.value;return{date:`${part("month")}.${part("day")}`,time:`${part("hour")}:${part("minute")}:${part("second")}`}};
const queryOf=(params:URLSearchParams):AuditQuery=>{const requestedSize=Number(params.get("size"));return{mode:"record",quick:"ALL",period:safe(params.get("range")??params.get("period"),["today","7d","30d"],"7d"),actorType:safe(params.get("actor_type"),["ALL","USER","SYSTEM","DEVICE"],"ALL"),actionGroup:safe(params.get("action_group"),["ALL","AUTH","ACCOUNT","ROLE_PERMISSION","INCIDENT_DISPATCH","CCTV_SYSTEM"],"ALL"),resourceType:safe(params.get("resource_type"),["ALL","USER","ROLE","INCIDENT","DISPATCH","CCTV","SYSTEM"],"ALL"),result:safe(params.get("result"),["ALL","SUCCESS","FAILURE","DENIED"],"ALL"),keyword:(params.get("keyword")??"").trim(),sort:safe(params.get("sort"),["latest","oldest","failure","denied"],"latest"),page:Math.max(1,Number(params.get("page"))||1),size:requestedSize===20||requestedSize===50?requestedSize:10,traceId:params.get("trace_id"),auditId:params.get("selected")??params.get("audit")}};
const countFor=(summary:AuditSummary,result:AuditResult|"ALL")=>result==="ALL"?summary.total:result==="SUCCESS"?summary.success:result==="FAILURE"?summary.failure:summary.denied;
type AuditIconKind="all"|"success"|"failure"|"denied"|"search"|"filter"|"sort"|"calendar"|"actor"|"resource"|"reset"|"auth"|"account"|"role"|"operations"|"system"|"copy"|"chevron";
function AuditIcon({kind}:{kind:AuditIconKind}){return <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
 {kind==="all"&&<><path d="M6 3h12v18H6zM9 3V1h6v2"/><path d="M9 8h6M9 12h6M9 16h4"/></>}
 {kind==="success"&&<><circle cx="12" cy="12" r="8.5"/><circle cx="12" cy="12" r="2.3" className="filledDot"/></>}
 {kind==="failure"&&<circle cx="12" cy="12" r="8.5" strokeDasharray="3 2.5"/>}
 {kind==="denied"&&<><path d="M12 2 4 5v6c0 5 3.4 8.7 8 11 4.6-2.3 8-6 8-11V5Z"/><path d="m9 9 6 6m0-6-6 6"/></>}
 {kind==="search"&&<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>}
 {kind==="filter"&&<><path d="M4 7h10M18 7h2M4 17h2M10 17h10"/><circle cx="16" cy="7" r="2"/><circle cx="8" cy="17" r="2"/></>}
 {kind==="sort"&&<><path d="m8 4-3 3 3 3M5 7h14M16 14l3 3-3 3M19 17H5"/></>}
 {kind==="calendar"&&<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4m8-4v4M3 10h18"/></>}
 {kind==="actor"&&<><circle cx="9" cy="8" r="3"/><path d="M3.5 19a5.5 5.5 0 0 1 11 0M18 8v6m-3-3h6"/></>}
 {kind==="resource"&&<><path d="M4 7h16M4 12h16M4 17h10"/><circle cx="18" cy="17" r="2"/></>}
 {kind==="reset"&&<><path d="m4 4 16 16M8 3h8l1 5H7zM7 8l1 13h8l1-13"/></>}
 {kind==="auth"&&<><path d="M12 2 4 5v6c0 5 3.4 8.7 8 11 4.6-2.3 8-6 8-11V5Z"/><path d="m9 12 2 2 4-5"/></>}
 {kind==="account"&&<><circle cx="10" cy="8" r="3"/><path d="M4 19c.5-4 2.5-6 6-6 1.2 0 2.2.2 3 .7M17 14v6M14 17h6"/></>}
 {kind==="role"&&<><circle cx="8" cy="12" r="3"/><path d="M11 12h10M17 12v3M20 12v2"/></>}
 {kind==="operations"&&<><path d="M4 18V9l8-5 8 5v9"/><path d="M8 21v-7h8v7M2 21h20"/></>}
 {kind==="system"&&<><rect x="3" y="4" width="18" height="14" rx="2"/><path d="M8 21h8M12 18v3M7 9h4M7 13h7"/></>}
 {kind==="copy"&&<><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></>}
 {kind==="chevron"&&<path d="m8 10 4 4 4-4"/>}
 </svg>}
const groupIcon:Record<AuditActionGroup,AuditIconKind>={AUTH:"auth",ACCOUNT:"account",ROLE_PERMISSION:"role",INCIDENT_DISPATCH:"operations",CCTV_SYSTEM:"system"};
const resultIcon:Record<AuditResult,AuditIconKind>={SUCCESS:"success",FAILURE:"failure",DENIED:"denied"};
const dateKey=(value:string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value));
const dateLabel=(value:string)=>new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"long",day:"numeric"}).format(new Date(value));
const personLabel=(value:string)=>value.replace(/\s+\d+$/,"");

export function AuditLogWorkspace(){
 const router=useRouter(),pathname=usePathname(),params=useSearchParams(),query=useMemo(()=>queryOf(new URLSearchParams(params.toString())),[params]);
 const[records,setRecords]=useState<AuditRecord[]>([]),[summary,setSummary]=useState(emptySummary),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updated,setUpdated]=useState<string|null>(null),[selected,setSelected]=useState<AuditRecord|null>(null),[trace,setTrace]=useState<AuditRecord[]>([]);
 const[rowRef,setRowRef]=useState<HTMLElement|null>(null);
 const initialSelectionHandled=useRef(false),detailDismissed=useRef(false),previousAuditId=useRef<string|null>(query.auditId);
 const sort=query.sort;
 const update=useCallback((next:Partial<AuditQuery>,mode:"replace"|"push"="replace")=>{const value={...query,...next},url=new URLSearchParams();if(value.period!=="7d")url.set("range",value.period);if(value.actorType!=="ALL")url.set("actor_type",value.actorType);if(value.actionGroup!=="ALL")url.set("action_group",value.actionGroup);if(value.resourceType!=="ALL")url.set("resource_type",value.resourceType);if(value.result!=="ALL")url.set("result",value.result);if(value.keyword)url.set("keyword",value.keyword);if(value.traceId)url.set("trace_id",value.traceId);if(value.sort!=="latest")url.set("sort",value.sort);if(value.page!==1)url.set("page",String(value.page));if(value.size!==10)url.set("size",String(value.size));if(value.auditId)url.set("selected",value.auditId);router[mode](`${pathname}${url.size?`?${url}`:""}`,{scroll:false})},[pathname,query,router]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const result=await adminAuditLogRepository.getRecords(query);setRecords(result.items);setTotal(result.total);setSummary(result.summary);setUpdated(new Date().toISOString())}catch{setError("감사 로그를 불러오지 못했습니다.")}finally{setLoading(false)}},[query]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const previous=previousAuditId.current;if(previous&&!query.auditId)detailDismissed.current=true;if(query.auditId)initialSelectionHandled.current=true;previousAuditId.current=query.auditId},[query.auditId]);
 useEffect(()=>{if(!query.auditId){setSelected(null);setTrace([]);return}void adminAuditLogRepository.getRecord(query.auditId).then(async record=>{if(!record){setSelected(null);setTrace([]);return}setSelected(record);setTrace(record.traceId?await adminAuditLogRepository.getTraceRecords(record.traceId):[])})},[query.auditId]);
 useEffect(()=>{if(loading||initialSelectionHandled.current||detailDismissed.current)return;initialSelectionHandled.current=true;if(records.length&&window.matchMedia("(min-width: 1024px)").matches)update({auditId:records[0].publicId})},[loading,records,update]);
 const choose=(record:AuditRecord,target:HTMLElement)=>{detailDismissed.current=false;setRowRef(target);update({auditId:record.publicId},"push")};
 const close=()=>{detailDismissed.current=true;update({auditId:null});requestAnimationFrame(()=>rowRef?.focus())};
 const clear=()=>router.replace(pathname,{scroll:false});
 const pages=Math.max(1,Math.ceil(total/query.size)),start=total?(query.page-1)*query.size+1:0,end=Math.min(query.page*query.size,total);
 const filterCount=[query.period!=="7d",query.result!=="ALL",query.actorType!=="ALL",query.actionGroup!=="ALL",query.resourceType!=="ALL",Boolean(query.traceId)].filter(Boolean).length;
 const chips=[query.result!=="ALL"?["result",results[query.result]]:null,query.actorType!=="ALL"?["actorType",actors[query.actorType]]:null,query.actionGroup!=="ALL"?["actionGroup",actionGroups[query.actionGroup]]:null,query.resourceType!=="ALL"?["resourceType",resources[query.resourceType]]:null,query.traceId?["traceId",`Trace ID: ${query.traceId.slice(0,8)}…`]:null].filter(Boolean) as [keyof AuditQuery,string][];
 const dateGroups=useMemo(()=>{const groups=new Map<string,AuditRecord[]>();records.forEach(record=>{const key=dateKey(record.occurredAt);groups.set(key,[...(groups.get(key)??[]),record])});return[...groups.values()]},[records]);
 const setSort=(value:string)=>{const next=new URLSearchParams(params.toString());if(value==="latest")next.delete("sort");else next.set("sort",value);next.delete("page");next.delete("audit");next.delete("selected");router.replace(`${pathname}${next.size?`?${next}`:""}`,{scroll:false})};
 return <main className={styles.page}>
  <header className={styles.header}><div><h1>감사 로그</h1><p>사용자와 시스템의 주요 작업, 변경 결과와 요청 흐름을 추적합니다.</p></div><div><time title="한국 표준시">마지막 갱신 {updated?`${dateTime(updated).time} KST`:"조회 중"}</time><button type="button" aria-label="감사 로그 새로고침" onClick={()=>void load()} disabled={loading}><svg className={loading?styles.spin:""} viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11a8 8 0 1 0 2 5M20 4v7h-7"/></svg><span>새로고침</span></button></div></header>
  <section className={styles.statusFilters} aria-label="결과 상태 빠른 필터">{statusFilters.map(([value,label])=><button data-result={value} key={value} aria-pressed={query.result===value} onClick={()=>update({result:query.result===value&&value!=="ALL"?"ALL":value,page:1,auditId:null},"push")}><i><AuditIcon kind={value==="ALL"?"all":resultIcon[value]}/></i><span>{label}</span><b>{countFor(summary,value)}<small>건</small></b></button>)}</section>
  <section className={styles.commandBar} aria-label="감사 로그 검색 및 필터">
   <label className={styles.search}><span className={styles.srOnly}>작업명·사용자·대상·Trace ID 검색</span><i><AuditIcon kind="search"/></i><input value={query.keyword} placeholder="작업명·사용자·대상·Trace ID 검색" onChange={event=>update({keyword:event.target.value,page:1,auditId:null})}/>{query.keyword&&<button type="button" aria-label="검색어 지우기" onClick={()=>update({keyword:"",page:1,auditId:null})}>×</button>}</label>
   <FilterMenu icon="calendar" label="기간" value={({today:"오늘","7d":"최근 7일","30d":"최근 30일"} as const)[query.period]} options={[["today","오늘","오늘 발생한 감사 이벤트"],["7d","최근 7일","최근 7일의 감사 이벤트"],["30d","최근 30일","최근 30일의 감사 이벤트"]]} selected={query.period} onChange={value=>update({period:value as AuditQuery["period"],page:1,auditId:null})}/>
   <FilterMenu icon="filter" label="작업 유형" value={query.actionGroup==="ALL"?"전체 작업":actionGroups[query.actionGroup]} options={[["ALL","전체 작업","모든 작업 유형"],...Object.entries(actionGroups).map(([key,value])=>[key,value,`${value} 감사 이벤트`] as [string,string,string])]} selected={query.actionGroup} onChange={value=>update({actionGroup:value as AuditQuery["actionGroup"],page:1,auditId:null})}/>
   <FilterMenu icon="actor" label="처리 주체" value={query.actorType==="ALL"?"전체":actors[query.actorType]} options={[["ALL","전체","모든 처리 주체"],...Object.entries(actors).map(([key,value])=>[key,value,`${value}가 수행한 기록`] as [string,string,string])]} selected={query.actorType} onChange={value=>update({actorType:value as AuditQuery["actorType"],page:1,auditId:null})}/>
   <FilterMenu icon="resource" label="대상" value={query.resourceType==="ALL"?"전체 대상":resources[query.resourceType]} options={[["ALL","전체 대상","모든 리소스"],...Object.entries(resources).map(([key,value])=>[key,value,`${value} 대상 기록`] as [string,string,string])]} selected={query.resourceType} onChange={value=>update({resourceType:value as AuditQuery["resourceType"],page:1,auditId:null})}/>
   <FilterMenu icon="success" label="결과" value={query.result==="ALL"?"전체 결과":results[query.result]} options={[["ALL","전체 결과","모든 처리 결과"],["SUCCESS","성공","정상 처리된 이벤트"],["FAILURE","실패","처리에 실패한 이벤트"],["DENIED","접근 거부","권한으로 차단된 이벤트"]]} selected={query.result} onChange={value=>update({result:value as AuditQuery["result"],page:1,auditId:null})}/>
   <FilterMenu icon="sort" label="정렬" value={sortOptions.find(([key])=>key===sort)?.[1]??"최신순"} options={sortOptions.map(([key,label])=>[key,label,key==="latest"?"최근 발생한 감사 이벤트부터 표시":key==="oldest"?"오래된 감사 이벤트부터 표시":key==="failure"?"실패 기록을 먼저 표시":"접근 거부 기록을 먼저 표시"])} selected={sort} onChange={setSort}/>
   <button type="button" className={styles.resetFilters} disabled={!query.keyword&&!filterCount&&sort==="latest"} onClick={clear}><AuditIcon kind="reset"/>필터 초기화</button>
  </section>
  {chips.length>0&&<div className={styles.chips} aria-label="적용된 조건">{chips.map(([key,label])=><button key={key} onClick={()=>update({[key]:key==="traceId"?null:"ALL",page:1,auditId:null})}>{label}<span aria-hidden="true">×</span></button>)}<button className={styles.clearAll} onClick={clear}>모두 해제</button></div>}
  <div className={styles.auditWorkspace}><section className={styles.list} aria-busy={loading}><header className={styles.listHeader}><h2>감사 이벤트</h2><span>{query.keyword||filterCount?`검색 결과 ${total}건`:`총 ${total}건`}</span></header><div role="table" aria-label="감사 이벤트">
   {error?<div className={styles.state} role="alert"><strong>{error}</strong><button onClick={()=>void load()}>다시 시도</button></div>:!loading&&!records.length?<div className={styles.state}><strong>{query.keyword||filterCount?"조건에 맞는 감사 기록이 없습니다.":"기록된 감사 로그가 없습니다."}</strong><p>{query.keyword||filterCount?"검색어나 필터 조건을 변경해 다시 확인해 주세요.":"사용자 또는 시스템에서 주요 작업이 발생하면 이곳에 기록됩니다."}</p>{(query.keyword||filterCount)&&<button onClick={clear}>필터 초기화</button>}</div>:<div className={styles.dateGroups} role="rowgroup">{dateGroups.map(group=><section key={dateKey(group[0].occurredAt)}><header><span>{dateLabel(group[0].occurredAt)}</span><b>{group.length}건</b></header><div className={styles.rows}>{group.map(record=>{const value=dateTime(record.occurredAt),actor=record.actorType==="USER"?personLabel(record.actorLabel):record.actorLabel,target=record.resourceType==="USER"?personLabel(record.resourceLabel):record.resourceLabel;return <div key={record.publicId} role="row" data-result={record.result} tabIndex={0} aria-selected={selected?.publicId===record.publicId} onClick={event=>choose(record,event.currentTarget)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();choose(record,event.currentTarget)}}}><time role="cell" title={`${fullTime(record.occurredAt)} KST`}>{value.time}</time><span className={styles.auditEvent} role="cell"><i data-group={record.actionGroup}><AuditIcon kind={groupIcon[record.actionGroup]}/></i><span><span className={styles.eventTitle}><strong>{record.actionLabel}</strong><em>{actors[record.actorType]}</em></span><small>{actor} · {target||resources[record.resourceType]}</small><small className={styles.rowSummary}>{record.summary||record.reasonText||"변경 요약 없음"}</small></span></span><span role="cell"><Result value={record.result}/></span></div>})}</div></section>)}</div>}</div></section>
   {selected?<AuditDetail record={selected} trace={trace} records={records} onClose={close} onSelect={record=>update({auditId:record.publicId},"push")}/>:<section className={styles.detailEmpty}><strong>확인할 감사 이벤트를 선택해 주세요.</strong><p>왼쪽 목록에서 이벤트를 선택하면 변경 정보와 요청 흐름을 확인할 수 있습니다.</p></section>}
  </div>
  {!loading&&<footer className={styles.pagination}><span>{total?`전체 ${total}건 · ${start}–${end}건 표시`:"전체 0건"}</span>{pages>1&&<nav aria-label="감사 이벤트 페이지"><button type="button" aria-label="이전 페이지" disabled={query.page<=1} onClick={()=>update({page:query.page-1,auditId:null})}><PaginationChevron direction="left"/></button>{getUserPaginationItems(query.page,pages).map((item,index)=>item==="ellipsis"?<span key={`ellipsis-${index}`}>…</span>:<button type="button" aria-label={item===query.page?`현재 페이지 ${item}`:`${item}페이지`} key={item} aria-current={item===query.page?"page":undefined} onClick={()=>update({page:item,auditId:null})}>{item}</button>)}<button type="button" aria-label="다음 페이지" disabled={query.page>=pages} onClick={()=>update({page:query.page+1,auditId:null})}><PaginationChevron direction="right"/></button></nav>}<UserPageSizeSelect value={query.size} unit="건" onChange={size=>update({size:size as AuditQuery["size"],page:1,auditId:null})}/></footer>}
 </main>;
}

const sortOptions=[["latest","최신순"],["oldest","오래된순"],["failure","실패 우선"],["denied","접근 거부 우선"]] as const;
function FilterMenu({icon,label,value,options,selected,onChange}:{icon:AuditIconKind;label:string;value:string;options:readonly (readonly [string,string,string])[];selected:string;onChange:(value:string)=>void}){
 const[open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!open)return;const close=(event:PointerEvent)=>{if(!root.current?.contains(event.target as Node)){setOpen(false);trigger.current?.focus()}},key=(event:KeyboardEvent)=>{if(event.key==="Escape"){setOpen(false);trigger.current?.focus()}};document.addEventListener("pointerdown",close);document.addEventListener("keydown",key);requestAnimationFrame(()=>root.current?.querySelector<HTMLElement>('[aria-selected="true"]')?.focus());return()=>{document.removeEventListener("pointerdown",close);document.removeEventListener("keydown",key)}},[open]);
 const move=(event:ReactKeyboardEvent<HTMLDivElement>)=>{if(event.key!=="ArrowDown"&&event.key!=="ArrowUp")return;event.preventDefault();const items=[...event.currentTarget.querySelectorAll<HTMLButtonElement>('[role="option"]')],index=items.indexOf(document.activeElement as HTMLButtonElement),next=event.key==="ArrowDown"?(index+1)%items.length:(index-1+items.length)%items.length;items[next]?.focus()};
 return <div ref={root} className={styles.filterMenu}><button ref={trigger} type="button" aria-haspopup="listbox" aria-expanded={open} data-applied={selected!=="ALL"&&selected!=="7d"&&selected!=="latest"} onClick={()=>setOpen(current=>!current)}><i><AuditIcon kind={icon}/></i><span><small>{label}</small><strong>{value}</strong></span><b><AuditIcon kind="chevron"/></b></button>{open&&<div role="listbox" aria-label={`${label} 선택`} onKeyDown={move}>{options.map(([key,title,description])=><button type="button" role="option" aria-selected={selected===key} tabIndex={selected===key?0:-1} key={key} onClick={()=>{onChange(key);setOpen(false);trigger.current?.focus()}}><strong>{title}</strong><small>{description}</small></button>)}</div>}</div>;
}

function Result({value}:{value:AuditResult}){return <span className={`${styles.result} ${styles[value.toLowerCase()]}`}><AuditIcon kind={resultIcon[value]}/>{results[value]}</span>}
type DetailTab="summary"|"changes"|"trace";
function AuditDetail({record,trace,records,onClose,onSelect}:{record:AuditRecord|null;trace:AuditRecord[];records:AuditRecord[];onClose:()=>void;onSelect:(record:AuditRecord)=>void}){
 const[tab,setTab]=useState<DetailTab>("summary"),[copied,setCopied]=useState(false);
 const drawerRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(!record)return;setTab("summary");setCopied(false);requestAnimationFrame(()=>drawerRef.current?.focus())},[record]);
 useEffect(()=>{if(!record)return;const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&matchMedia("(max-width: 1023px)").matches){event.preventDefault();onClose()}};document.addEventListener("keydown",key);return()=>document.removeEventListener("keydown",key)},[record,onClose]);
 if(!record)return null;
 const index=records.findIndex(item=>item.publicId===record.publicId),category=actionGroups[record.actionGroup];
 const copy=async()=>{if(!record.traceId)return;await navigator.clipboard.writeText(record.traceId);setCopied(true)};
 return <aside ref={drawerRef} className={styles.detail} role="dialog" aria-modal="false" aria-label="감사 이벤트 상세" tabIndex={-1}>
  <header className={styles.detailHeader}><button className={styles.mobileBack} aria-label="감사 기록으로 돌아가기" onClick={onClose}>감사 기록으로 돌아가기</button><div><p>감사 이벤트 상세</p><h2><span className={styles.detailIcon}><AuditIcon kind={groupIcon[record.actionGroup]}/></span>{record.actionLabel}</h2><div className={styles.detailBadges}><Result value={record.result}/><span>{category}</span></div><time>{fullTime(record.occurredAt)} KST<br/>처리 주체: {record.actorType==="USER"?personLabel(record.actorLabel):record.actorLabel||actors[record.actorType]}</time></div></header>
  <nav className={styles.detailTabs} role="tablist" aria-label="감사 증적 탭">{([["summary","요약"],["changes","변경 내용"],["trace","요청 추적"]] as [DetailTab,string][]).map(([value,label])=><button type="button" role="tab" aria-selected={tab===value} key={value} onClick={()=>setTab(value)}>{label}</button>)}</nav>
  <div className={styles.detailBody}>{tab==="summary"?<Summary record={record}/>:tab==="changes"?<Diff before={record.before} after={record.after}/>:<RequestTrace record={record} trace={trace} copied={copied} onCopy={()=>void copy()} onSelect={onSelect}/>}</div>
  <footer className={styles.detailPager}><span>{index>=0?`${index+1} / ${records.length}`:"선택 로그"}</span><div><button type="button" disabled={index<=0} onClick={()=>onSelect(records[index-1])}>이전 로그</button><button type="button" disabled={index<0||index>=records.length-1} onClick={()=>onSelect(records[index+1])}>다음 로그</button></div></footer>
 </aside>;
}
function Summary({record}:{record:AuditRecord}){
 return <div className={styles.summaryContent}><InfoSection title="이벤트 요약" rows={[["작업명",record.actionLabel],["작업 코드",record.actionCode],["처리 결과",results[record.result]],["처리 주체",record.actorType==="USER"?personLabel(record.actorLabel):record.actorLabel||"—"],["대상 리소스",record.resourceType==="USER"?personLabel(record.resourceLabel):record.resourceLabel||"—"],["발생 시각",`${fullTime(record.occurredAt)} KST`]]}/><section className={styles.reasonBlock}><h3>{record.result==="SUCCESS"?"작업 설명":record.result==="DENIED"?"차단 사유":"실패 사유"}</h3><p>{record.reasonText||record.summary||"기록된 설명이 없습니다."}</p></section></div>;
}
function InfoSection({title,rows}:{title:string;rows:[string,string][]}){return <section><h3>{title}</h3><dl>{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>}
function RequestTrace({record,trace,copied,onCopy,onSelect}:{record:AuditRecord;trace:AuditRecord[];copied:boolean;onCopy:()=>void;onSelect:(record:AuditRecord)=>void}){return <><InfoSection title="요청 정보" rows={[["리소스 유형",resources[record.resourceType]],["외부 식별자",record.resourcePublicId??"—"],["요청 결과",results[record.result]],["처리 주체",record.actorType==="USER"?personLabel(record.actorLabel):record.actorLabel||"—"],...(record.reasonText?[["사유",record.reasonText] as [string,string]]:[])]}/><section><h3>Trace ID</h3>{record.traceId?<p className={styles.traceValue}>{record.traceId}<button className={styles.copyButton} aria-label="Trace ID 복사" onClick={onCopy}><AuditIcon kind="copy"/>{copied?"복사됨":"복사"}</button></p>:<p>표시할 요청 추적 정보가 없습니다.</p>}</section>{trace.length>1&&<TraceFlow record={record} trace={trace} onSelect={onSelect}/>}</>}
function TraceFlow({record,trace,onSelect}:{record:AuditRecord;trace:AuditRecord[];onSelect:(record:AuditRecord)=>void}){return <section><h3>동일 요청 흐름</h3><ol className={styles.timeline}>{trace.map(item=><li key={item.publicId} aria-current={item.publicId===record.publicId?"step":undefined}><button type="button" onClick={()=>onSelect(item)}><span className={styles.timelineDot}/><time>{dateTime(item.occurredAt).time}</time><span><b>{item.actionLabel}</b><small>{item.summary||item.reasonText||`${item.actorLabel} · ${results[item.result]}`}</small></span></button></li>)}</ol></section>}
function Diff({before,after}:{before:Record<string,unknown>|null;after:Record<string,unknown>|null}){const keys=[...new Set([...Object.keys(before??{}),...Object.keys(after??{})])].filter(key=>JSON.stringify(before?.[key])!==JSON.stringify(after?.[key])&&!/password|token|secret|authorization|cookie|key/i.test(key));return <section><h3>변경 내용</h3>{!keys.length?<p>이 이벤트에는 별도의 변경 전후 정보가 없습니다.</p>:<><p className={styles.changeCount}>변경된 항목 {keys.length}개</p><div className={styles.diff}>{keys.map(key=><article key={key}><h4>{fieldLabel(key)}</h4><div><span><small>변경 전</small><b>{JSON.stringify(mask(before?.[key]??null))}</b></span><span><small>변경 후</small><b>{JSON.stringify(mask(after?.[key]??null))}</b></span></div></article>)}</div></>}</section>}
function fieldLabel(key:string){return({roles:"역할",status:"계정 상태"} as Record<string,string>)[key]??key}
