"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {usePathname,useRouter,useSearchParams} from "next/navigation";
import {AdminCompactSelect} from "@/features/user-management/AdminCompactSelect";
import {UserPageSizeSelect,getUserPaginationItems,PaginationChevron} from "@/features/user-management/UserDirectoryPagination";
import {adminAuditLogRepository} from "./mockAuditLogRepository";
import type {AuditActorType,AuditQuery,AuditQuickFilter,AuditRecord,AuditResourceType,AuditResult,AuditSummary} from "./auditLogTypes";
import styles from "./auditLogWorkspace.module.css";

const results={SUCCESS:"성공",FAILURE:"실패",DENIED:"접근 거부"} as const;
const actors:Record<AuditActorType,string>={USER:"사용자",SYSTEM:"시스템",DEVICE:"단말"};
const resources:Record<AuditResourceType,string>={USER:"사용자",ROLE:"역할",INCIDENT:"사건",DISPATCH:"출동",CCTV:"CCTV",SYSTEM:"시스템"};
const quicks:[AuditQuickFilter,string][]=[["ALL","전체"],["ACCOUNT","계정·권한"],["OPERATIONS","사건·출동"],["SYSTEM","시스템 작업"],["FAILED","실패·거부"]];
const emptySummary:AuditSummary={total:0,success:0,failure:0,denied:0};
const safe=<T extends string>(value:string|null,allowed:readonly T[],fallback:T)=>allowed.includes(value as T)?value as T:fallback;
const mask=(value:unknown):unknown=>Array.isArray(value)?value.map(mask):value&&typeof value==="object"?Object.fromEntries(Object.entries(value).map(([key,item])=>[/password|token|secret|authorization|cookie|key/i.test(key)?[key,"***"]:[key,mask(item)]])):value;
const fullTime=(value:string)=>new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date(value));
const shortTime=(value:string)=>new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date(value));
const queryOf=(params:URLSearchParams):AuditQuery=>{const size=Number(params.get("size"));return{mode:"record",quick:safe(params.get("quick"),quicks.map(item=>item[0]),"ALL"),period:safe(params.get("period"),["today","7d","30d"],"7d"),actorType:safe(params.get("actor_type"),["ALL","USER","SYSTEM","DEVICE"],"ALL"),actionGroup:"ALL",resourceType:"ALL",result:safe(params.get("result"),["ALL","SUCCESS","FAILURE","DENIED"],"ALL"),keyword:(params.get("keyword")??"").trim(),page:Math.max(1,Number(params.get("page"))||1),size:size===20||size===50?size:10,traceId:null,auditId:params.get("audit")}};

export function AuditLogWorkspace(){
 const router=useRouter(),pathname=usePathname(),params=useSearchParams(),query=useMemo(()=>queryOf(new URLSearchParams(params.toString())),[params]);
 const[records,setRecords]=useState<AuditRecord[]>([]),[summary,setSummary]=useState(emptySummary),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updated,setUpdated]=useState<string|null>(null),[selected,setSelected]=useState<AuditRecord|null>(null),[trace,setTrace]=useState<AuditRecord[]>([]),[detailsOpen,setDetailsOpen]=useState(false);
 const[rowRef,setRowRef]=useState<HTMLElement|null>(null),searchRef=useRef<HTMLInputElement>(null);
 const update=useCallback((next:Partial<AuditQuery>)=>{const value={...query,...next},url=new URLSearchParams();if(value.quick!=="ALL")url.set("quick",value.quick);if(value.period!=="7d")url.set("period",value.period);if(value.actorType!=="ALL")url.set("actor_type",value.actorType);if(value.result!=="ALL")url.set("result",value.result);if(value.keyword)url.set("keyword",value.keyword);if(value.page!==1)url.set("page",String(value.page));if(value.size!==10)url.set("size",String(value.size));if(value.auditId)url.set("audit",value.auditId);router.replace(`${pathname}${url.size?`?${url}`:""}`,{scroll:false})},[pathname,query,router]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const result=await adminAuditLogRepository.getRecords(query);setRecords(result.items);setTotal(result.total);setSummary(result.summary);setUpdated(new Date().toISOString())}catch{setError("감사 로그를 불러오지 못했습니다.")}finally{setLoading(false)}},[query]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!query.auditId){setSelected(null);setTrace([]);return}void adminAuditLogRepository.getRecord(query.auditId).then(async record=>{setSelected(record);setTrace(record?.traceId?await adminAuditLogRepository.getTraceRecords(record.traceId):record?[record]:[])})},[query.auditId]);
 const choose=(record:AuditRecord,target:HTMLElement)=>{setRowRef(target);update({auditId:record.publicId})};
 const close=()=>{update({auditId:null});requestAnimationFrame(()=>rowRef?.focus())};
 const clear=()=>update({quick:"ALL",period:"7d",actorType:"ALL",result:"ALL",keyword:"",page:1,auditId:null});
 const pages=Math.max(1,Math.ceil(total/query.size)),start=total?(query.page-1)*query.size+1:0,end=Math.min(query.page*query.size,total);
 const chips=[query.period!=="7d"?["period",query.period==="today"?"오늘":"최근 30일"]:null,query.result!=="ALL"?["result",results[query.result]]:null,query.actorType!=="ALL"?["actor_type",actors[query.actorType]]:null,query.quick!=="ALL"?["quick",quicks.find(item=>item[0]===query.quick)?.[1]??""]:null].filter(Boolean) as string[][];
 return <main className={styles.page}>
  <header className={styles.header}><div><h1>감사 로그</h1><p>사용자와 시스템의 주요 작업 및 변경 이력을 확인합니다.</p></div><div><time>{updated?`최근 갱신 ${fullTime(updated)} KST`:"조회 중"}</time><button onClick={()=>void load()} disabled={loading} aria-label="감사 로그 새로고침"><span className={loading?styles.spin:""} aria-hidden="true">↻</span> 새로고침</button></div></header>
  <section className={styles.summary} aria-label="현재 조회 범위 요약"><span>전체 <b>{summary.total}</b></span><span>성공 <b>{summary.success}</b></span><span className={styles.failure}>실패 <b>{summary.failure}</b></span><span className={styles.denied}>접근 거부 <b>{summary.denied}</b></span></section>
  <section className={styles.filters}>
   <label className={styles.search}><span className={styles.srOnly}>작업·처리자·대상·Trace 검색</span><i aria-hidden="true">⌕</i><input ref={searchRef} value={query.keyword} placeholder="작업·처리자·대상·Trace 검색" onChange={event=>update({keyword:event.target.value,page:1,auditId:null})}/>{query.keyword&&<button aria-label="검색어 지우기" onClick={()=>update({keyword:"",page:1,auditId:null})}>×</button>}</label>
   <div className={styles.basicFilters}><AdminCompactSelect label="기간" value={query.period} placeholder="기간" options={[{value:"today",label:"오늘"},{value:"7d",label:"최근 7일"},{value:"30d",label:"최근 30일"}]} onChange={value=>update({period:value,page:1,auditId:null})}/><AdminCompactSelect label="결과" value={query.result} placeholder="전체 결과" options={[{value:"ALL",label:"전체 결과"},{value:"SUCCESS",label:"성공"},{value:"FAILURE",label:"실패"},{value:"DENIED",label:"접근 거부"}]} onChange={value=>update({result:value,page:1,auditId:null})}/><AdminCompactSelect label="처리 주체" value={query.actorType} placeholder="전체 주체" options={[{value:"ALL",label:"전체 주체"},{value:"USER",label:"사용자"},{value:"SYSTEM",label:"시스템"},{value:"DEVICE",label:"단말"}]} onChange={value=>update({actorType:value,page:1,auditId:null})}/><button className={styles.detailToggle} aria-expanded={detailsOpen} onClick={()=>setDetailsOpen(value=>!value)}>상세 조건</button></div>
   <div className={styles.quickFilters}>{quicks.map(([value,label])=><button key={value} aria-pressed={query.quick===value} onClick={()=>update({quick:value,page:1,auditId:null})}>{label}</button>)}</div>
   {detailsOpen&&<div className={styles.detailFilters}><p>현재 데이터에서 신뢰할 수 있는 대상 유형·작업 분류 조건은 빠른 분류에서 제공합니다.</p></div>}
  </section>
  {chips.length>0&&<div className={styles.chips}><span>적용된 조건</span>{chips.map(([key,label])=><button key={key} onClick={()=>update({[key]:key==="period"?"7d":"ALL",page:1,auditId:null})}>{label} ×</button>)}<button onClick={clear}>모두 초기화</button></div>}
  <div className={`${styles.workspace}${selected?` ${styles.hasDetail}`:""}`}>
   <section className={styles.list} aria-busy={loading}><header className={styles.listHeader}><h2>감사 로그 목록</h2><span>{total}건</span></header><div className={styles.tableHead}><span>발생 시각</span><span>처리자</span><span>작업 및 변경 내용</span><span>대상</span><span>결과</span></div>
   {error?<div className={styles.state} role="alert"><strong>{error}</strong><button onClick={()=>void load()}>다시 조회</button></div>:!loading&&!records.length?<div className={styles.state}><strong>{chips.length||query.keyword?"조건에 맞는 감사 로그가 없습니다":"감사 로그가 없습니다"}</strong><p>검색어나 필터 조건을 변경해 다시 확인해 주세요.</p><button onClick={clear}>필터 초기화</button></div>:<div className={styles.rows}>{records.map(record=><button key={record.publicId} aria-pressed={selected?.publicId===record.publicId} onClick={event=>choose(record,event.currentTarget)}><time title={`${fullTime(record.occurredAt)} KST`}>{shortTime(record.occurredAt)}<small>KST</small></time><span><b>{record.actorLabel||actors[record.actorType]}</b><small>{actors[record.actorType]}</small></span><span><b>{record.actionLabel}{record.traceId&&trace.length>1?<em>{trace.length}단계</em>:null}</b><small>{record.summary||record.reasonText||"변경 요약 없음"}</small></span><span><b>{record.resourceLabel||record.resourcePublicId||"—"}</b><small>{resources[record.resourceType]}</small></span><Result value={record.result}/></button>)}</div>}
   <footer className={styles.pagination}><span>전체 {total}건 · {start}–{end}건 표시</span><nav aria-label="감사 로그 페이지"><button disabled={query.page<=1} aria-label="이전 페이지" onClick={()=>update({page:query.page-1,auditId:null})}><PaginationChevron direction="left"/></button>{getUserPaginationItems(query.page,pages).map((item,index)=>item==="ellipsis"?<i key={index}>…</i>:<button key={item} aria-current={item===query.page?"page":undefined} onClick={()=>update({page:item,auditId:null})}>{item}</button>)}<button disabled={query.page>=pages} aria-label="다음 페이지" onClick={()=>update({page:query.page+1,auditId:null})}><PaginationChevron direction="right"/></button></nav><UserPageSizeSelect value={query.size} onChange={value=>update({size:value as 10|20|50,page:1,auditId:null})}/></footer></section>
   <AuditDetail record={selected} trace={trace} onClose={close} onSelect={record=>update({auditId:record.publicId})}/>
  </div>
 </main>;
}

function Result({value}:{value:AuditResult}){return <span className={`${styles.result} ${styles[value.toLowerCase()]}`}>{results[value]}</span>}
function AuditDetail({record,trace,onClose,onSelect}:{record:AuditRecord|null;trace:AuditRecord[];onClose:()=>void;onSelect:(record:AuditRecord)=>void}){const[copied,setCopied]=useState(false);if(!record)return <aside className={`${styles.detail} ${styles.detailEmpty}`}><strong>감사 로그를 선택해 주세요</strong><p>처리 내용과 변경 전후, 같은 Trace의 작업 흐름을 확인할 수 있습니다.</p></aside>;return <aside className={styles.detail} aria-label="선택 감사 로그 상세"><header><div><h2>{record.actionLabel}</h2><Result value={record.result}/></div><button aria-label="상세 조사 닫기" onClick={onClose}>×</button></header><div className={styles.detailBody}>{record.result!=="SUCCESS"&&<section className={styles.reason}><h3>처리 사유</h3><p>{record.reasonText??"기록된 처리 사유가 없습니다."}</p></section>}<section><h3>기본 정보</h3><dl>{[["발생 시각",`${fullTime(record.occurredAt)} KST`],["처리자",record.actorLabel],["주체 유형",actors[record.actorType]],["작업 코드",record.actionCode],["대상",record.resourceLabel],["대상 유형",resources[record.resourceType]],["대상 public ID",record.resourcePublicId??"—"],["결과",results[record.result]]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{record.traceId?<div className={styles.trace}><code>{record.traceId.slice(0,4)}···{record.traceId.slice(-2)}</code><button aria-label="Trace ID 복사" onClick={async()=>{await navigator.clipboard.writeText(record.traceId!);setCopied(true)}}>{copied?"복사됨":"복사"}</button></div>:<p>Trace 없음</p>}</section><Diff before={record.before} after={record.after}/><section><h3>처리 사유</h3><p>{record.reasonText??"기록된 처리 사유가 없습니다."}</p></section><section><h3>같은 Trace 작업 흐름</h3><ol className={styles.timeline}>{trace.map(item=><li key={item.publicId} aria-current={item.publicId===record.publicId?"step":undefined}><button onClick={()=>onSelect(item)}><time>{shortTime(item.occurredAt).split(" ").at(-1)}</time><span><b>{item.actionLabel}</b><small>{item.actorLabel}</small></span><Result value={item.result}/></button></li>)}</ol></section><details><summary>원본 데이터 보기</summary><pre>{JSON.stringify(mask(record),null,2)}</pre></details></div></aside>}
function Diff({before,after}:{before:Record<string,unknown>|null;after:Record<string,unknown>|null}){const keys=[...new Set([...Object.keys(before??{}),...Object.keys(after??{})])].filter(key=>JSON.stringify(before?.[key])!==JSON.stringify(after?.[key])&&!/password|token|secret|authorization|cookie|key/i.test(key));if(!keys.length)return <section><h3>변경 전후 비교</h3><p>변경 전후 정보가 기록되지 않았습니다.</p></section>;return <section><h3>변경 전후 비교</h3><div className={styles.diff}>{keys.map(key=><div key={key}><b>{key}</b><span><small>변경 전</small><code>{JSON.stringify(mask(before?.[key]??null))}</code></span><i>→</i><span><small>변경 후</small><code>{JSON.stringify(mask(after?.[key]??null))}</code></span></div>)}</div></section>}
