import type{AdminAuditLogRepository,AuditFlow,AuditQuery,AuditRecord,AuditResult}from"./auditLogTypes";
const day=(minutes:number)=>new Date(Date.now()-minutes*60000).toISOString();
export const mockAuditRecords:AuditRecord[]=[
 {publicId:"audit-role-1",traceId:"9ac3b754-e04d-4f2b-a377-47f18d76c1fa",occurredAt:day(18),actorType:"USER",actorPublicId:"admin-1",actorLabel:"김관리",actionCode:"AUTH.ROLE_CHANGE_REQUESTED",actionLabel:"역할 변경 요청",actionGroup:"ROLE_PERMISSION",resourceType:"USER",resourcePublicId:"user-6",resourceLabel:"한관리 6",result:"SUCCESS",reasonText:null,summary:"관제센터 책임자 역할 추가 요청",before:{roles:["CONTROLLER"],password:"masked"},after:{roles:["CONTROLLER","CONTROL_MANAGER"],password:"masked"},requestIpHash:"a47f9c2d821d"},
 {publicId:"audit-role-2",traceId:"9ac3b754-e04d-4f2b-a377-47f18d76c1fa",occurredAt:day(17),actorType:"SYSTEM",actorPublicId:null,actorLabel:"도로보GO 시스템",actionCode:"AUTH.SESSION_REVOKED",actionLabel:"기존 세션 폐기",actionGroup:"AUTH",resourceType:"USER",resourcePublicId:"user-6",resourceLabel:"한관리 6",result:"SUCCESS",reasonText:null,summary:"권한 변경에 따라 기존 세션 폐기",before:null,after:null,requestIpHash:null},
 {publicId:"audit-role-3",traceId:"9ac3b754-e04d-4f2b-a377-47f18d76c1fa",occurredAt:day(16),actorType:"SYSTEM",actorPublicId:null,actorLabel:"도로보GO 시스템",actionCode:"AUTH.ROLE_CHANGED",actionLabel:"역할 변경 완료",actionGroup:"ROLE_PERMISSION",resourceType:"USER",resourcePublicId:"user-6",resourceLabel:"한관리 6",result:"SUCCESS",reasonText:null,summary:"관제센터 책임자 역할 1개 추가",before:{roles:["CONTROLLER"]},after:{roles:["CONTROLLER","CONTROL_MANAGER"]},requestIpHash:null},
 {publicId:"audit-disable",traceId:"3b52452f-e15a-4b69-961a-c6c14565ac07",occurredAt:day(72),actorType:"USER",actorPublicId:"admin-1",actorLabel:"김관리",actionCode:"USER.DEACTIVATE",actionLabel:"계정 비활성화",actionGroup:"ACCOUNT",resourceType:"USER",resourcePublicId:"user-8",resourceLabel:"이출동",result:"SUCCESS",reasonText:"담당 업무 변경",summary:"계정 상태 활성에서 비활성으로 변경",before:{status:"ACTIVE",token:"secret"},after:{status:"INACTIVE",token:"secret"},requestIpHash:"93c18275f1ab"},
 {publicId:"audit-denied",traceId:null,occurredAt:day(103),actorType:"USER",actorPublicId:"controller-2",actorLabel:"박관제",actionCode:"AUTH.LOGIN_DENIED",actionLabel:"비활성 계정 로그인 차단",actionGroup:"AUTH",resourceType:"USER",resourcePublicId:"user-8",resourceLabel:"이출동",result:"DENIED",reasonText:"비활성 상태의 계정입니다.",summary:"변경 없이 로그인 요청 거부",before:null,after:null,requestIpHash:"1e74aa71c042"},
 {publicId:"audit-incident",traceId:"703768d6-99b4-4804-95e3-9e487bfcbb61",occurredAt:day(155),actorType:"USER",actorPublicId:"controller-1",actorLabel:"최관제",actionCode:"INCIDENT.ACKNOWLEDGE",actionLabel:"사건 확인",actionGroup:"INCIDENT_DISPATCH",resourceType:"INCIDENT",resourcePublicId:"11111111-1111-4111-8111-111111111107",resourceLabel:"INC-20260730-0012",result:"SUCCESS",reasonText:null,summary:"사건 상태 NEW에서 ACKNOWLEDGED로 변경",before:{status:"NEW"},after:{status:"ACKNOWLEDGED"},requestIpHash:null},
 {publicId:"audit-dispatch-fail",traceId:"703768d6-99b4-4804-95e3-9e487bfcbb61",occurredAt:day(151),actorType:"SYSTEM",actorPublicId:null,actorLabel:"도로보GO 시스템",actionCode:"DISPATCH.ASSIGN",actionLabel:"출동 배정",actionGroup:"INCIDENT_DISPATCH",resourceType:"DISPATCH",resourcePublicId:"dispatch-31",resourceLabel:"DSP-20260730-0031",result:"FAILURE",reasonText:"배정 가능한 출동 담당자가 없습니다.",summary:"출동 배정 실패 · 변경 없음",before:null,after:null,requestIpHash:null},
 {publicId:"audit-cctv",traceId:null,occurredAt:day(221),actorType:"DEVICE",actorPublicId:null,actorLabel:"RPI-DEVICE-014",actionCode:"CCTV.STATUS_SYNC",actionLabel:"CCTV 상태 동기화",actionGroup:"CCTV_SYSTEM",resourceType:"CCTV",resourcePublicId:"cctv-014",resourceLabel:"CAM 014",result:"SUCCESS",reasonText:null,summary:"연결 상태를 정상으로 반영",before:{status:"WARNING"},after:{status:"ACTIVE"},requestIpHash:null},
];
const resultRank:Record<AuditResult,number>={SUCCESS:1,DENIED:2,FAILURE:3};
const applies=(record:AuditRecord,q:AuditQuery)=>{
 const days=q.period==="today"?1:q.period==="7d"?7:30;if(Date.now()-Date.parse(record.occurredAt)>days*86400000)return false;
 if(q.quick==="FAILED"&&!["FAILURE","DENIED"].includes(record.result))return false;
 if(q.quick==="ACCOUNT"&&!["AUTH","ACCOUNT","ROLE_PERMISSION"].includes(record.actionGroup))return false;
 if(q.quick==="OPERATIONS"&&record.actionGroup!=="INCIDENT_DISPATCH")return false;
 if(q.quick==="SYSTEM"&&record.actorType==="USER")return false;
 if(q.actorType!=="ALL"&&record.actorType!==q.actorType||q.actionGroup!=="ALL"&&record.actionGroup!==q.actionGroup||q.resourceType!=="ALL"&&record.resourceType!==q.resourceType||q.result!=="ALL"&&record.result!==q.result)return false;
 if(q.traceId&&record.traceId!==q.traceId)return false;
 const keyword=q.keyword.trim().replace(/\s+/g," ").toLocaleLowerCase();return!keyword||[record.actorLabel,record.actionCode,record.actionLabel,record.resourceLabel,record.resourcePublicId,record.traceId,record.reasonText].some(value=>value?.toLocaleLowerCase().includes(keyword));
};
const summary=(records:AuditRecord[])=>({total:records.length,success:records.filter(record=>record.result==="SUCCESS").length,failure:records.filter(record=>record.result==="FAILURE").length,denied:records.filter(record=>record.result==="DENIED").length});
const page=<T>(items:T[],q:AuditQuery,records:AuditRecord[]):{items:T[];total:number;page:number;size:number;summary:ReturnType<typeof summary>}=>{const max=Math.max(1,Math.ceil(items.length/q.size)),current=Math.min(q.page,max);return{items:items.slice((current-1)*q.size,current*q.size),total:items.length,page:current,size:q.size,summary:summary(records)}};
function flows(records:AuditRecord[]):AuditFlow[]{const groups=new Map<string,AuditRecord[]>();records.forEach(record=>{const key=record.traceId??`record:${record.publicId}`;(groups.get(key)??groups.set(key,[]).get(key)!).push(record)});return[...groups.entries()].map(([id,entries])=>{const sorted=entries.sort((a,b)=>Date.parse(a.occurredAt)-Date.parse(b.occurredAt)),last=sorted.at(-1)!;return{id,traceId:last.traceId,occurredAt:last.occurredAt,actorLabel:sorted[0].actorLabel,actorType:sorted[0].actorType,actionLabel:last.actionLabel,resourceLabel:last.resourceLabel,resourceType:last.resourceType,summary:last.summary,recordCount:entries.length,result:entries.reduce((result,item)=>resultRank[item.result]>resultRank[result]?item.result:result,"SUCCESS" as AuditResult),records:sorted}}).sort((a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt))}
export class MockAdminAuditLogRepository implements AdminAuditLogRepository{
 async getFlows(q:AuditQuery){const records=mockAuditRecords.filter(record=>applies(record,q));return page(flows(records),q,records)}
 async getRecords(q:AuditQuery){const records=mockAuditRecords.filter(record=>applies(record,q)).sort((a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt));return page(records,q,records)}
 async getRecord(id:string){return structuredClone(mockAuditRecords.find(record=>record.publicId===id)??null)}
 async getTraceRecords(traceId:string){return structuredClone(mockAuditRecords.filter(record=>record.traceId===traceId).sort((a,b)=>Date.parse(a.occurredAt)-Date.parse(b.occurredAt)))}
}
export const adminAuditLogRepository:AdminAuditLogRepository=new MockAdminAuditLogRepository();
