"use client";
import Link from "next/link";
import {usePathname,useSearchParams} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {useAuth} from "@/components/auth/AuthContext";
import {createDispatchAdapter} from "@/features/dispatch/dispatchAdapterFactory";
import {dispatchProgressStatuses,terminalDispatchStatuses} from "@/features/dispatch/dispatchDomain";
import type {DispatchStatus} from "@/features/control-dashboard/dashboardTypes";
import styles from "./dispatchLocalNavigation.module.css";
type View="home"|"requested"|"active"|"history"; type Icon="home"|"inbox"|"route"|"history";
const adapter=createDispatchAdapter();
const destinations:Array<{view:View;label:string;href:string;icon:Icon}>=[{view:"home",label:"출동 홈",href:"/dispatch",icon:"home"},{view:"requested",label:"신규 요청",href:"/dispatch?view=requested",icon:"inbox"},{view:"active",label:"진행 중",href:"/dispatch?view=active",icon:"route"},{view:"history",label:"완료 이력",href:"/dispatch?view=history",icon:"history"}];
export const classifyDispatchNavigationStatus=(status:DispatchStatus):Exclude<View,"home">|null=>status==="REQUESTED"?"requested":dispatchProgressStatuses.includes(status)?"active":terminalDispatchStatuses.includes(status)?"history":null;
function NavIcon({kind}:{kind:Icon}){return <svg viewBox="0 0 24 24" aria-hidden="true">{kind==="home"?<><path d="M4 10.5 12 4l8 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 4 18.5z"/><path d="M9 20v-6h6v6"/></>:kind==="inbox"?<><path d="M5 4h14l2 9v6H3v-6z"/><path d="M3 13h6l2 3h2l2-3h6"/></>:kind==="route"?<><circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M8 18h3a3 3 0 0 0 3-3V9a3 3 0 0 1 3-3"/></>:<><path d="M6 4h12v16H6zM9 8h6M9 12h6"/><path d="m9 16 1.5 1.5L14 14"/></>}</svg>}
export function DispatchLocalNavigation(){const{user}=useAuth(),pathname=usePathname(),searchParams=useSearchParams();const[counts,setCounts]=useState<Partial<Record<Exclude<View,"home">,number>>>({}),[detailView,setDetailView]=useState<View>("active");const allowed=Boolean(user?.apiPermissions.includes("DISPATCH.READ_OWN"));const current=useMemo<View>(()=>{if(pathname==="/dispatch"){const value=searchParams.get("view");return value==="requested"||value==="active"||value==="history"?value:"home"}return detailView},[pathname,searchParams,detailView]);useEffect(()=>{if(!allowed)return;let mounted=true;void adapter.list({page:1,size:50,activeOnly:false}).then(page=>{if(!mounted)return;const next={requested:0,active:0,history:0};page.items.forEach(item=>{const group=classifyDispatchNavigationStatus(item.status);if(group)next[group]++});setCounts(next)}).catch(()=>{});const id=pathname.match(/^\/dispatch\/([^/]+)/)?.[1];if(id)void adapter.detail(decodeURIComponent(id)).then(detail=>{const group=detail&&classifyDispatchNavigationStatus(detail.status);if(mounted&&group)setDetailView(group)}).catch(()=>{});return()=>{mounted=false}},[allowed,pathname]);if(!allowed)return null;return <nav className={styles.nav} aria-label="출동 업무 메뉴"><div>{destinations.map(item=>{const count=item.view==="home"?undefined:counts[item.view];return <Link key={item.view} href={item.href} aria-current={current===item.view?"page":undefined}><NavIcon kind={item.icon}/><span>{item.label}</span>{count!==undefined&&<small aria-label={`${count}건`}>{count}</small>}</Link>})}</div></nav>}
